kubeshop/testkube

.github/kubectl-kubetest-builder
.github/workflows/go-build.yml
.github/workflows/kubectl-kubetest-releaser.yaml

Adding GO binaries release actions.

---

docs/installing.md

changed helm-charts repo name from kubtest to helm-charts

---

cmd/kubectl-kubtest/commands/scripts/common.go
pkg/api/client/factory.go
pkg/api/client/proxy.go

fixed namespaces

---

internal/app/api/v1/scripts.go

- API server namespaces query param

fixed namespace query param

---

test/e2e/e2e_test.go
test/e2e/kubtest/kubtest.go

added default namespace to e2e test

---

assets/grafana-dasboard.json
docs/metrics.md

This PR...
- added Prometheus docs
-

Prometheus config in docs

---

cmd/kubectl-kubtest/commands/scripts/create_script.go
pkg/ui/printers.go

added empty file check

---

pkg/executor/server/executor.go
pkg/executor/server/executor_test.go
pkg/executor/server/handlers.go

added executor api server as library

---

cmd/api-server/main.go
pkg/executor/server/executor_test.go

- error handling when api server starts

fixed api error handling

---

internal/app/api/v1/scripts.go

fixed sigsegv

---

Makefile
cmd/api-server/main.go
go.mod
internal/app/api/v1/scripts.go
pkg/api/client/direct.go

added name for the mongo container and --rm flag so it cleans up after being stopped
This PR...
-
-

fixed typo databse -> database

---

cmd/api-server/main.go

fixed kubeconfig check

---

cmd/kubectl-kubtest/commands/scripts.go
pkg/ui/config.go
pkg/ui/errors.go

fixed cd verbosity

---

Makefile
api/v1/kubtest.yaml
build/api-server/Dockerfile
cmd/api-server/main.go
docs/installing.md
pkg/api/client/direct.go
pkg/api/client/proxy.go
pkg/api/client/proxy_test.go
pkg/ui/errors.go
pkg/worker/worker.go
test/e2e/e2e_test.go

Script duration fix + ports fix

---

cmd/kubectl-kubtest/commands/scripts/renderer.go
go.mod
pkg/version/version_test.go

fixed sigsegv in renderer

---

cmd/kubectl-kubtest/commands/scripts/common.go
cmd/kubectl-kubtest/commands/scripts/list_script_executions.go
cmd/kubectl-kubtest/commands/scripts/renderer.go
cmd/kubectl-kubtest/commands/scripts/start_script.go
cmd/kubectl-kubtest/commands/scripts/watch_script_execution.go
internal/app/api/v1/scripts.go
pkg/api/kubtest/model_script_execution_extended.go

polishing cli ui a little

---

README.md

added link to Discord

---

Makefile
test/e2e/Kubtest-Sanity.postman_collection.json

Fix for cluster tests

---

internal/pkg/api/repository/result/mongo.go
pkg/executor/repository/result/mongo.go

fixed executionResult in mongop

---

cmd/kubectl-kubtest/commands/install.go
cmd/kubectl-kubtest/commands/root.go
cmd/kubectl-kubtest/commands/uninstall.go

added uninstall command

---

api/v1/kubtest.yaml
cmd/kubectl-kubtest/commands/scripts/start_script.go

fixed api-docs

---

Makefile
cmd/kubectl-kubtest/commands/install.go
cmd/tools/commands/release.go
pkg/ui/errors.go

updated release info

---

cmd/kubectl-kubtest/commands/constants.go
cmd/kubectl-kubtest/commands/install.go
cmd/kubectl-kubtest/commands/uninstall.go
docs/installing.md
pkg/jobs/jobclient.go
pkg/k8sclient/k8sclient.go
pkg/ui/errors.go

feat: Add option to install/uninstall ingress.

---

mkdocs.yml

reverting changes introduces in #310

---

CONTRIBUTING.md
Makefile
docs/development.md
docs/getting-started.md
docs/installing.md

docs update - uninstall

---

cmd/tools/commands/release.go
install.sh

added install script version replace during release

---

pkg/jobs/jobclient.go

I yanked out PVs and PVCs from current implementation as we said that artifacts should be stored in min.io. 
So back to the drawing board

removed persistent volume and pvc from k8s jobs

---

pkg/api/v1/kubtest/model_execution_result_extended.go
pkg/worker/worker_test.go

unit tests for worker

---

pkg/api/v1/client/direct_test.go
pkg/api/v1/client/factory_test.go
pkg/api/v1/client/proxy.go
pkg/api/v1/client/proxy_test.go
pkg/executor/client/executors.go

unit tests for factory, and direct client

---

docs/install.sh

An upgrade to exiting install script so it defaults to default

getting latest by default

---

docs/requirements.txt

added missing plugin

---

docs/Dockerfile
docs/docker-compose.yml
docs/requirements.txt

Fix mkdocs  makefile port 8080

---

pkg/process/exec.go
pkg/runner/agent/agent.go
pkg/runner/output/output.go
pkg/runner/output/writer.go
pkg/runner/output/writer_test.go
test/e2e/Local-API-Health.postman_collection.json

feat: runner structured output - json in - json stream out

---

api/v1/testkube.yaml
internal/app/api/v1/server.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/proxy.go

Task: https://github.com/kubeshop/testkube/issues/14 
-
-
-

feat: Make abort execution as DELETE method.

---

cmd/kubectl-testkube/commands/scripts/start_script.go

fix: added exit code in case of test failure

---

internal/app/api/v1/filter.go
internal/app/api/v1/filter_test.go

fix: Date filter to pass when time si between or equal start and end.

---

cmd/kubectl-testkube/commands/scripts/create_script.go

fix: added type validator

---

cmd/kubectl-testkube/commands/executors/create_executor.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/proxy.go

added executors endpoints for proxied api client

---

Makefile
cmd/api-server/main.go
docs/installing.md
docs/telemetry.md
go.mod
go.sum
mkdocs.yml
pkg/telemetry/telemetry.go

Added data anonymous data collection.  Basically it collects information about the host in form like this:
```
{
"anonymousId": "a4652358effb311a074bf84d2aed5a7d270dee858bff10e847df2a9ea132bb38",
"context": {
"library": {
"name": "analytics-go",
"version": "3.0.0"
}
},
"event": "testkube-heartbeat",
"integrations": {},
"messageId": "2021-11-04 19:54:40.029549 +0100 CET m=+0.148209228",
"originalTimestamp": "2021-11-04T19:54:40.029571+01:00",
"receivedAt": "2021-11-04T18:54:41.004Z",
"sentAt": "2021-11-04T18:54:40.029Z",
"timestamp": "2021-11-04T18:54:41.004Z",
"type": "track"
}
```
If we are going to proceed with this we need to make sure that LD_FLAG is passed 
```
LD_FLAGS += -X github.com/kubeshop/testkube/pkg/telemetry.telemetryToken=$(TELEMETRY_TOKEN)
```
Also …

added segmentio telemetry

---

internal/app/api/v1/scripts.go
pkg/server/httpserver.go

feat: extended problem with context

---

docs/installing.md

updated install instructions

---

cmd/kubectl-testkube/commands/install.go

closes #483 
Added helm binary check before running install command
-
-
-

added helm binary validation

---

cmd/kubectl-testkube/commands/scripts/common.go
cmd/kubectl-testkube/commands/scripts/start_script.go
cmd/kubectl-testkube/commands/scripts/watch_script_execution.go
internal/app/api/v1/scripts.go
pkg/api/v1/client/common.go
pkg/api/v1/client/common_test.go
pkg/executor/client/job.go
pkg/jobs/jobclient.go
pkg/ui/printers.go

feat: watch based on logs

---

docs/installing.md
internal/app/api/v1/server.go
pkg/jobs/jobclient.go

passing storage envars to k8s jobs

---

internal/app/api/v1/scripts.go
internal/pkg/api/repository/result/filter.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go

Task: https://github.com/kubeshop/testkube/issues/448
-
-
-

feat: Get filtered data from db directly.

---

CODE_OF_CONDUCT.md
README.md
docs/index.md

updated docs with recent logo

---

.github/workflows/docker-build.yaml

Passed telemetry token from the secrets to th ebuild process

---

go.mod
go.sum
pkg/api/v1/client/direct.go
pkg/api/v1/client/proxy.go

fix: DeleteScript strange behavior.

---

docs/installing.md

Fixed storage endpoint

---

.github/workflows/test.yml
internal/app/api/v1/scripts.go
internal/pkg/api/repository/result/filter.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go

Completion for the previous PR with db filters
closes #517 
-
-
-

feat: Improve filters and add integration tests (reloaded).

---

docs/installing.md

feat: added docs for HomeBrew upgrades

---

internal/app/api/v1/scripts.go

Fix for not working get execution from command.
-
-
-

fix: [api-server]Get executions from CLI.

---

pkg/jobs/jobclient.go

increased wait backoff to half a second and total of 10 retries
- [ x] tested locally
- [x ] tested on cluster
Instead of initial wait period of 50 milliseconds i increased it to 500 milliseconds and added 10 retries cound
fixes #516

increased wait backoff to half a second and total of 10 retries

---

cmd/kubectl-testkube/commands/artifacts.go
go.mod
go.sum
internal/app/api/v1/scripts.go
internal/app/api/v1/server.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/proxy.go
pkg/storage/minio/minio.go

Strange doubled message when listing artifacts without id passed #518
Signed-off-by: jasmingacic <jasmin.gacic@gmail.com>

fix: Error reporting for artifacts.

---

docs/installing.md

Added description of possibility to turn off minio if needed.

---

go.mod
go.sum
internal/app/api/v1/scripts.go
internal/pkg/api/datefilter/filter.go
internal/pkg/api/datefilter/filter_test.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go

fix: Soritng of the executions latest first, move datefilter to separate package.

---

pkg/storage/minio/minio.go

feat: minio scrape multiple directories

---

pkg/storage/minio/minio.go

Just removing leftover debug logs
-
-
-

removed debug leftovers

---

.github/workflows/docker-build.yaml
build/api-server/Dockerfile

fix for telemetry

---

build/api-server/Dockerfile

telemetry token fix ofr docker build

---

build/api-server/Dockerfile

Fixed broken build command
-
-
-

fixing broken command

---

cmd/kubectl-testkube/commands/scripts.go
docs/executor-curl.md

Documentation minor fixes
-
-
-

curl script example fix

---

cmd/kubectl-testkube/commands/scripts/create_script.go

fix: adutodetecting file based executor type

---

cmd/kubectl-testkube/commands/scripts/delete.go
docs/getting-started.md
docs/scripts-running.md

fix(scripts delete and docs): Delete command not checking for empty script name, improve docs

---

.goreleaser.yml
go.mod
go.sum
pkg/telemetry/telemetry.go

fix: added LDFlag to .goreleaser

---

cmd/kubectl-testkube/commands/scripts/list_script_executions.go
docs/dashboard.md
internal/app/api/v1/scripts.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/direct_test.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/proxy.go

fix(docs, list executions): limit to 10 most recent ones, fix minor docs issue

---

docs/executor-custom.md

fix: minor spelling/naming updates

---

pkg/k8sclient/k8sclient.go

Setting query per second setting so Pod log streaming does not time out
-
-
-

fix: k8s client QPS

---

cmd/kubectl-testkube/commands/scripts/watch_script_execution.go

fix(execution watch): check execution status before trying to get logs

---

api/v1/kusk.yaml

feat: added kusk configuration

---

cmd/kubectl-testkube/commands/constants.go

The dashboard was messed up and the certificates don't work.
-
-
-

fix(dashboard command): use temporary the demo instead of dashboard

---

pkg/telemetry/telemetry.go

fix: removed telemetry token

---

api/v1/testkube.yaml
internal/app/api/v1/scripts.go
internal/pkg/api/repository/result/filter.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go

feat: added searching in api by name of script or execution

---

go.mod
go.sum
pkg/ui/errors.go
pkg/ui/logo.go
pkg/ui/printers.go
pkg/ui/utils.go

fix(cli ui package): change colors lib

---

.goreleaser.yml

Added snapcraft and deb packaging as indicated int #161 
-
-
-

feat: Snap deb (not tested)

---

.github/workflows/release.yaml
Makefile
internal/app/api/v1/server.go

fix: removed release builds for beta versions

---

.goreleaser.yml

Fixes snaps in goreleaser
-
-
-

fix: Added missing summary for snaps

---

.goreleaser-dev.yml
.goreleaser.yml

Removed snapcraft since it was not building properly
-
-
-

fix: remove snapcraft

---

internal/app/api/v1/scripts.go

fix(script create): do not add resource version on create

---

docs/getting-started.md

fix: update getting-started.md

---

cmd/kubectl-testkube/commands/constants.go
cmd/kubectl-testkube/commands/dashboard.go

fix(dashboard): change dashboard url

---

cmd/kubectl-testkube/commands/scripts/watch_script_execution.go

fix(watch execution): url of the get script

---

pkg/mapper/scripts/kube_openapi.go

fix(get script): script creation time

---

README.md

Signed-off-by: jasmingacic <jasmin.gacic@gmail.com>
Readme badges
-
-
-

feat: added stargazer and downloads badges

---

README.md

fix: removed duplicate logo

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/root.go
pkg/api/v1/client/direct.go
pkg/api/v1/testkube/model_test_base_extended.go
pkg/api/v1/testkube/model_test_step_delay.go
pkg/api/v1/testkube/model_test_step_execute_script.go
pkg/api/v1/testkube/model_test_step_interface.go
pkg/mapper/tests/kube_openapi.go

feat: tests lists with all data based on inheritance

---

docs/executor-postman.md

Typo
Typo in postman executor doc
-
-
- Fix spelling typo

style: update executor-postman.md spelling typo

---

cmd/kubectl-testkube/commands/tests/common.go
internal/app/api/v1/tests.go

fix: fixed test status and cli display

---

internal/pkg/api/repository/result/mongo.go

refactor: use agregate to get execution totals from mongo db

---

api/v1/testkube.yaml
internal/app/api/v1/scripts.go
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
pkg/mapper/tests/kube_openapi.go

feat: added filtering to scripts

---

api/v1/testkube.yaml
internal/app/api/v1/executions.go
internal/app/api/v1/server.go
internal/app/api/v1/tags.go
internal/app/api/v1/tests.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go

feat(tags): add tags endpoint

---

internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go

fix(tags): slice access out of range

---

.github/workflows/mkdocs.yml

fix: trigger mkdocs on testkube openapi spec changes

---

api/v1/testkube.yaml
internal/app/api/v1/server.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/proxy.go
pkg/executor/client/job.go

fix: openapi spec for tests

---

cmd/kubectl-testkube/commands/install.go

fix: bypass repo exsits warning

---

README.md
cmd/kubectl-testkube/commands/scripts/create_script.go
cmd/kubectl-testkube/commands/scripts/list_script_executions.go
cmd/kubectl-testkube/commands/scripts/list_scripts.go
cmd/kubectl-testkube/commands/scripts/update_script.go
cmd/kubectl-testkube/commands/tests/create.go
cmd/kubectl-testkube/commands/tests/list.go
cmd/kubectl-testkube/commands/tests/update.go
go.mod
internal/app/api/v1/tests.go
pkg/mapper/tests/kube_openapi.go
test/e2e/example-test.json

fix: tests list returns empty records

---

cmd/kubectl-testkube/commands/install.go

fix: install script panics on repo add success

---

docs/development.md

This pr updates development documentation to the latest version
Closes #747 
-
-
Changes to the development documentation
-

fix: update development documentation

---

internal/app/api/v1/server.go

list possible routes like in HATEOAS endpoints
-
-
-

feat: enpoints list enpoint 

---

.gitignore
Makefile
cmd/kubectl-testkube/commands/tests/start.go
docs/tests-creating.md
docs/tests-getting-results.md
docs/tests-running.md
mkdocs.yml
pkg/api/v1/testkube/model_test_executions_result_extended.go

docs: tests documentation

---

pkg/api/v1/client/common_test.go

Add unit test for output parsing
-
-
-

refactor: add unit tests for output parsing

---

README.md

fix: Discord link in README

---

Makefile
test/e2e/test-example-1.json
test/e2e/test-example-2.json

docs: added more test examples

---

Makefile

feat: added port forward helpers to Makefile

---

cmd/kubectl-testkube/commands/scripts.go
cmd/kubectl-testkube/commands/scripts/common.go
cmd/kubectl-testkube/commands/scripts/executions.go
cmd/kubectl-testkube/commands/scripts/get_script_execution.go
cmd/kubectl-testkube/commands/scripts/start.go
cmd/kubectl-testkube/commands/scripts/watch.go
internal/app/api/v1/executions.go
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/direct_test.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/proxy.go

fix: don't use dash for get all executions

---

cmd/kubectl-testkube/commands/common/client.go
cmd/kubectl-testkube/commands/scripts/create.go
cmd/kubectl-testkube/commands/scripts/delete.go
cmd/kubectl-testkube/commands/scripts/deleteall.go
cmd/kubectl-testkube/commands/scripts/get.go
cmd/kubectl-testkube/commands/scripts/update.go
pkg/api/v1/client/common.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/proxy.go

fix: testkube installation namespace

---

cmd/kubectl-testkube/commands/scripts/deleteall.go

fix: scripts delete all removed script name arg

---

cmd/kubectl-testkube/commands/tests.go
cmd/kubectl-testkube/commands/tests/delete.go
cmd/kubectl-testkube/commands/tests/deleteall.go
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
pkg/api/v1/client/direct.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/proxy.go

fix: allow to delete tests

---

cmd/kubectl-testkube/commands/tests/executions.go

fix: test execution removed unnecessary validator

---

internal/app/api/v1/executions.go
internal/app/api/v1/scripts.go
pkg/executor/client/common.go
pkg/executor/client/job.go
pkg/jobs/jobclient.go
pkg/secret/client.go

Allow to work with scripts created withput secrets
-
- Add Apply method to secret client
- Ignore missed secrets on scripts deletion
- Use Apply method on script update
- Don't create env vars for jobs without secrets

fix: ignore missing secrets for scripts to

---

cmd/kubectl-testkube/commands/constants.go
cmd/kubectl-testkube/commands/dashboard.go
pkg/process/exec.go

Allow to run local dashboard
Closes #796 
-
- Add port forwarding for dashboard service
- Add additional use-global-dashboard flag to dashboard command
-

feat: allow to run local dashboard

---

internal/app/api/v1/tests.go

Provide namespace for test step execution request
Closes #837 
-
-
-  Provide namespace for test step execution request

fix: provide namespace for test step execution request

---

cmd/kubectl-testkube/commands/scripts/executions.go
internal/app/api/v1/tests.go
test/e2e/test-example-3.json

feat: passing test params to to each script execution

---

test/run.sh

feat: delete all optional in test suite

---

docs/testkube-automation.md

Fixed typo/copy-past error in the documentation

---

README.md

- A few general changes to the README file.

docs: add general README improvements

---

.github/workflows/test.yml
Makefile
cmd/kubectl-testkube/commands/scripts/common.go
internal/app/api/v1/executions.go
internal/pkg/api/repository/result/mongo_test.go
pkg/api/v1/client/factory.go
pkg/executor/client/job.go
pkg/jobs/jobclient.go
test/e2e/e2e_test.go

fix: pass errors in case of pod failure

---

cmd/kubectl-testkube/commands/scripts/common.go
cmd/kubectl-testkube/commands/scripts/start.go

fix: small ui fixes

---

LICENSE
cmd/kubectl-testkube/commands/tests/common.go
internal/app/api/v1/tests.go
mkdocs.yml
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_execution_result_extended.go
pkg/api/v1/testkube/model_script_extended.go
pkg/api/v1/testkube/model_test_base_extended.go
pkg/api/v1/testkube/model_test_execution_extended.go
pkg/api/v1/testkube/model_test_step_execute_script_extended.go
pkg/api/v1/testkube/model_test_step_execution_result_extended.go

Partially implement #864 
-
-
-

feat: added queued steps on test run

---

internal/app/api/v1/executions.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go

fix: better filters totals

---

cmd/kubectl-testkube/commands/install.go
docs/installing.md

Enabling/disabling jetstack installation
-
- Add addition flag for installation command to enable/disable jetstack
-

feat: enable/disable jetstack installation

---

cmd/kubectl-testkube/commands/migrate.go
cmd/kubectl-testkube/commands/root.go
internal/migrations/init.go
internal/migrations/version_0.8.8.go
pkg/migrator/migrator.go
pkg/migrator/migrator_test.go
pkg/process/exec.go
pkg/version/version.go

feat: added migrator for 0.8.8

---

cmd/kubectl-testkube/commands/uninstall.go

fix: remove tests crds on uninstall

---

test/run.sh

fix: run cli tests with default binary

---

internal/migrations/version_0.8.8.go

Remove quotes from migration command
-
-
-

fix: update migration command

---

cmd/kubectl-testkube/commands/common.go
cmd/kubectl-testkube/commands/migrate.go
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/commands/uninstall.go
cmd/kubectl-testkube/commands/upgrade.go

feat: migrate on upgrade

---

internal/app/api/v1/server.go

Fix: don't process empty executor list
-
-
-

fix: check for empty env var

---

cmd/kubectl-testkube/commands/tests/run.go

fix: no output when failed test execution

---

cmd/kubectl-testkube/commands/analytics/disable.go
cmd/kubectl-testkube/commands/analytics/enable.go
cmd/kubectl-testkube/commands/analytics/status.go
cmd/kubectl-testkube/commands/artifacts.go
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/config/config.go
cmd/kubectl-testkube/config/config_test.go
cmd/kubectl-testkube/config/storage.go
cmd/kubectl-testkube/config/wtiter.go

fix: creating config file

---

mkdocs.yml

- [ x] tested locally
- [ x] updated the docs
-
-
-

docs: enable search in docs

---

pkg/executor/content/fetcher.go

fix: renamed test content file name for fetcher

---

docs/getting-started.md

fix: updated getting started docs

---

cmd/kubectl-testkube/commands/crds/tests_crds.go

Non-tested
Fixes the type of the CRD created
-
-
-

fix: create correct CRD type

---

pkg/jobs/jobclient.go

fix: add debug info

---

pkg/jobs/jobclient.go

fix: pass unit tests

---

go.mod
go.sum
pkg/analytics/analytics.go

fix: analytics tracking id from const to var

---

Makefile

fix(Makefile): replace spaces with tabs

---

api/v1/testkube.yaml

fix: openapispec fixes

---

mkdocs.yml

fix: enabling back swagger renderer

---

cmd/kubectl-testkube/commands/root.go
pkg/analytics/analytics.go

fix: remove non anonymous data and send data on post run root cmd

---

Makefile
cmd/proxy/main.go

feat: added reverse proxy to local API server based on kubeproxy

---

cmd/kubectl-testkube/commands/root.go

fix: autocompletion fix

---

cmd/kubectl-testkube/commands/tests/create.go

fix: added validator to executor type when creating test

---

README.md

feat: added contributors

---

api/v1/testkube.yaml
internal/app/api/v1/executions.go
pkg/api/v1/testkube/common.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_execution_summary.go
pkg/api/v1/testkube/model_executions_result_extended.go
pkg/api/v1/testkube/model_test_base_extended.go

fix: labels on tests and executions lists

---

cmd/kubectl-testkube/commands/abort.go
cmd/kubectl-testkube/commands/common/validator/version.go
cmd/kubectl-testkube/commands/create.go
cmd/kubectl-testkube/commands/delete.go
cmd/kubectl-testkube/commands/download.go
cmd/kubectl-testkube/commands/generate.go
cmd/kubectl-testkube/commands/get.go
cmd/kubectl-testkube/commands/run.go
cmd/kubectl-testkube/commands/tests/create.go
cmd/kubectl-testkube/commands/update.go
cmd/kubectl-testkube/commands/version.go
cmd/kubectl-testkube/commands/watch.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_executions_result_extended.go

fix: autodetect type before validator + version is not populated correctly fix 

---

.github/workflows/release.yaml

Add github action to homebrew upgrade
-
-
-

feat: add homebrew folmulae bump

---

pkg/analytics/analytics.go

Info in the event name is more useful for GA dashboard.
-
-
-

fix(analytics): put command in the event category

---

cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
cmd/kubectl-testkube/commands/tests/run.go
docs/executor-custom.md
test/e2e/e2e_test.go

fix: add kubectl-testkube watchCmd to rootCmd

---

docs/getting-started.md

fix: git-uri in docs about cypress tests creating

---

api/v1/testkube.yaml
internal/app/api/v1/executions.go
internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_execution_summary.go
pkg/types/duration.go
pkg/types/duration_test.go

feat: added duration to executons and ts executions

---

.github/workflows/docker-build.yaml
.github/workflows/release-dev.yaml
.github/workflows/release.yaml
.goreleaser-dev.yml
.goreleaser.yml
Makefile
build/api-server/Dockerfile
go.mod
go.sum
pkg/analytics/analytics.go

fix: use GA4 analytics

---

Makefile
test/perf/api-server.js
test/perf/testkube-homepage.js

feat: added simple k6 test

---

cmd/kubectl-testkube/commands/common.go
cmd/kubectl-testkube/commands/install.go
cmd/kubectl-testkube/commands/upgrade.go

closes #1134 
✓ blocked by https://github.com/kubeshop/helm-charts/pull/124
-
-
-

feat: added possibility to not install mongodb

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/tests/get.go
cmd/kubectl-testkube/commands/testsuites/get.go
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/client/api.go
pkg/api/v1/client/interface.go
pkg/api/v1/testkube/model_test_suite_with_execution_base_extended.go
pkg/api/v1/testkube/model_test_with_execution_base_extended.go

Api methods to list test and test suites with executions
-
-
-

feat: Api methods to list test and test suites with executions

---

pkg/secret/client.go

fix: fixed missing namespace

---

api/v1/testkube.yaml
pkg/api/v1/testkube/model_test_suite_with_execution.go
pkg/api/v1/testkube/model_test_with_execution.go

Rename json key without _
-
-
-

fix: rename json key without _

---

docs/testsuites-creating.md
internal/app/api/v1/testsuites.go
test/postman/Testkube-API.postman_collection.json

fix: docs for testsuites - new model used + postman test fix

---

internal/app/api/v1/testsuites.go

fix: status fix for test suites

---

pkg/api/v1/client/api.go

Get proper method path for executions
-
-
-

fix: get proper method path for executions

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml

fix: update checksum after adding windows installer

---

Makefile

fix: makefile sanity reload remove secret before

---

internal/app/api/v1/executions.go

fix: passing params file to executor

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml
.github/workflows/test.yml
build/api-server/Dockerfile
cmd/debug-server/Dockerfile
go.mod
go.sum

fix: upgrade go to 1.18

---

test/postman/Params-test.postman_collection.json
test/postman/env.postman_environment.json

feat: params test example with env file

---

docs/dashboard.md
mkdocs.yml

fix: update navigation

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml
.github/workflows/test.yml
build/api-server/Dockerfile
cmd/debug-server/Dockerfile
go.mod
go.sum

Update to go 1.18 and upgrade fiber to latest version
-
-
-

fix: update to golang 1.18 and latest fiber

---

mkdocs.yml

Was accidentally deleted in https://github.com/kubeshop/testkube/pull/1025
https://github.com/kubeshop/testkube/pull/1025/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2L68
- [ x ] updated the docs
-
-
-

docs: enable back search in docs

---

docs/installing.md

Update brew installation docs
-
-
-

fix: update brew installation docs

---

.gitignore
docs/executor-curl.md
docs/executor-custom.md
docs/executor-cypress.md
docs/executor-postman.md
docs/executor-soapui.md
mkdocs.yml

This PR adds documentation on how to use the SoapUI executor
-
-
-

docs: SoapUI executor docs

---

Makefile
cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/create.go
cmd/kubectl-testkube/commands/tests/get.go
cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
cmd/kubectl-testkube/commands/tests/renderer/test_obj.go
cmd/kubectl-testkube/commands/testsuites/create.go
cmd/kubectl-testkube/commands/testsuites/get.go
cmd/kubectl-testkube/commands/testsuites/renderer/testsuite_obj.go
internal/app/api/v1/testsuites.go
pkg/mapper/tests/kube_openapi.go

fix: tests create by command

---

.github/CODEOWNERS
docs/executor-k6.md
docs/index.md

docs: k6 executor docs

---

docs/scheduling.md
mkdocs.yml

feat: add scheduling docs

---

pkg/test/detector/detector.go
pkg/test/detector/detector_test.go
pkg/test/detector/k6.go
pkg/test/detector/k6_test.go

feat: added K6 files detector

---

docs/executor-k6.md

docs: added mention about autodetect type for files

---

internal/app/api/v1/executions.go
internal/app/api/v1/executions_test.go

fix: params in case of non existing go object

---

docs/installing.md

Updating documentation will resolve issue https://github.com/kubeshop/testkube/issues/1309
-
-
-

docs: Update installing.md to prevent installation error

---

docs/executor-cypress.md

docs: change from --uri to --git-uri in Cypress example

---

docs/executor-soapui.md

One outcome of the acceptance test was that there should be an example xml in the docs. This PR addresses that.
-
-
-

docs: add example xml for soapui tests

---

docs/scripts-creating.md

Apologies for not checking earlier all the other instances where it was wrong 🙏🏽  
This should be it :) 
-
-
-

docs: change more instances of --git-uri for cypress

---

api/v1/testkube.yaml
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/result/filter.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go
internal/pkg/api/repository/testresult/filter.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_execution_status_extended.go
pkg/api/v1/testkube/model_test_suite_status_extended.go

Support filtering bu multiple status values
-
-
-

feat: support filtering by multiple status values

---

cmd/kubectl-testkube/commands/root.go
internal/app/api/v1/server.go
pkg/analytics/analytics.go

feat: Analytics for api server

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml

feat: add caching for go modules to speed up the build.

---

.github/workflows/test.yml

feat: add go cache step for test action

---

.github/workflows/docker-build.yaml

feat: add cache for docke and go on docker image build action

---

.github/workflows/docker-build.yaml
.github/workflows/release-dev.yaml
.github/workflows/release.yaml
.goreleaser-dev.yml
.goreleaser.yml
Makefile
build/api-server/Dockerfile
cmd/api-server/main.go
cmd/kubectl-testkube/commands/root.go
go.mod
internal/app/api/v1/server.go
pkg/analytics/analytics.go
pkg/utils/text/obfuscate.go
pkg/utils/text/obfuscate_test.go
pkg/utils/text/slug.go
pkg/utils/text/slug_test.go

fix: analytics debug

---

cmd/kubectl-testkube/commands/dashboard.go
pkg/executor/content/fetcher.go
pkg/http/client.go
pkg/http/client_test.go

fix: timeouts in http clients

---

cmd/kubectl-testkube/commands/tests/create.go

fix: added flags validation into create test

---

docs/installing.md

Add cert manager dependency
-
-
-

fix: add cert manager dependency

---

docs/executor-soapui.md

Update SoapUI test types in docs
-
-
-

docs: update soapui test types

---

docs/installing.md

docs: helm is required to install cluster comp.

---

pkg/analytics/analytics.go

feat: added os and arch to params=

---

pkg/storage/minio/minio.go

Return error message for non existing artifacts
-
-
-

fix: return error message for non existing artifacts

---

cmd/kubectl-testkube/commands/common/validator/version.go
cmd/kubectl-testkube/commands/common/validator/version_test.go

feat: minor version warning only

---

internal/app/api/v1/executions.go
mkdocs.yml

fix: include slack documentation in index and imporve slack message

---

docs/installing.md

This PR adds instructions to the installation guide on apt
-
-
-

docs: apt installation

---

cmd/kubectl-testkube/commands/common/validator/version.go
cmd/kubectl-testkube/commands/common/validator/version_test.go

fix: added tests for version check

---

pkg/process/exec.go

fix: error was not treated on cmd.Start

---

cmd/kubectl-testkube/commands/root.go

fix: version param passed to GA correctly fot CLI

---

.github/workflows/lint.yaml
docs/installing.md
docs/slack-integration.md
internal/app/api/v1/executions.go
pkg/slacknotifier/slack.go

feat: improve slack message format, improve docs

---

Makefile
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/config/data.go
pkg/analytics/analytics.go
pkg/ui/ui.go

feat: added init event on first cmd run

---

pkg/analytics/analytics.go

fix: panic in analytics send

---

pkg/executor/scraper/scraper.go

Renamed the folder but not the Go package
-
-
-

fix: update package name

---

.github/workflows/lint.yaml

fix: improve linting workflow

---

.github/workflows/lint.yaml
.github/workflows/lint_pr.yaml

fix: make go lint workflow on pull_request instead of pull_request_target

---

docs/tests-creating.md

As discussed today, test input types needed to be updated in the docs. This PR takes care of that.
-
- docs
-

docs: updated test input types in docs

---

api/v1/testkube.yaml

fix: typo s/htto/http/

---

cmd/kubectl-testkube/commands/generate.go

Remove server check for generate command
-
-
-

fix: remove server check for generate command

---

pkg/analytics/analytics.go

fix: remove host names poassed to ananlytics logs

---

.github/workflows/docker-build-stage.yaml

Added a separate workflow file to build a Docker image and to trigger helm release upgrade in `helm-charts` repo to STAGE k8s cluster on every push to `main` branch.
No changes. A new file was added.

build: Deploy to stage cluster

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml

fix expired creds

---

.golangci.yml

fix: golangci-linter add config file

---

.gitignore
api/v1/testkube.yaml
internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_execution_result_extended.go
pkg/api/v1/testkube/model_execution_status.go
pkg/api/v1/testkube/model_execution_status_extended.go
pkg/api/v1/testkube/model_test_suite_execution_status.go
pkg/api/v1/testkube/model_test_suite_status_extended.go

feat: cancelled steps when stop test on failure

---

cmd/kubectl-testkube/commands/common/client.go
cmd/kubectl-testkube/commands/oauth/config.go
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/config/data.go
cmd/kubectl-testkube/config/storage.go
internal/app/api/v1/handlers.go
internal/app/api/v1/server.go
pkg/api/v1/client/direct_client.go
pkg/api/v1/client/factory.go
pkg/oauth/github.go
pkg/oauth/interface.go
pkg/oauth/oauth.go
pkg/utils/utils.go

Server oauth token validation
-
-
-

fix: server oauth token validation

---

docs/development-crds.md
mkdocs.yml

Add documentation on Custom Resources used in Testkube
-
-
-

docs: add Custom Resources to the docs

---

docs/demo-video/index.md
docs/demo-video/resources/Dockerfile
docs/demo-video/resources/deployment.yaml
docs/demo-video/resources/go.mod
docs/demo-video/resources/service.go

docs: Demo video plan

---

mkdocs.yml

docs: add artillery.io to mkdocs

---

internal/app/api/v1/server.go

feat: added results endpoint on localhost

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/create.go
cmd/kubectl-testkube/commands/executors/create.go
cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/create.go
cmd/kubectl-testkube/commands/tests/update.go
cmd/kubectl-testkube/commands/testsuites/create.go
cmd/kubectl-testkube/commands/webhooks/create.go
docs/cli/kubectl-testkube_create.md
docs/cli/kubectl-testkube_create_executor.md
docs/cli/kubectl-testkube_create_test.md
docs/cli/kubectl-testkube_create_testsuite.md
docs/cli/kubectl-testkube_create_webhook.md
internal/app/api/v1/executor.go
internal/app/api/v1/handlers.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/app/api/v1/webhook.go
pkg/crd/template.go
pkg/crd/templates/executor.tmpl
pkg/crd/templates/test.tmpl
pkg/crd/templates/testsuite.tmpl
pkg/crd/templates/webhook.tmpl

CRD generation for cli and api
-
-
-

feat: CRD generation for cli and api

---

test/postman/TestKube-Sanity.postman_collection.json
test/postman/Testkube-API-Failing.postman_collection.json
test/postman/Testkube-API.postman_collection.json

Update postman reponse code for test creation
-
-
-

fix: update postman reponse code for test creation

---

internal/app/api/v1/executions_test.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_execution_extended.go

Delete executions when deleting test or test suite
-
-
-

fix: delete executions when deleting test or test suite

---

cmd/kubectl-testkube/commands/renderer/executionResult.go
cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/run.go
cmd/kubectl-testkube/commands/testsuites/common.go
internal/app/api/v1/executions.go
pkg/executor/agent/agent.go
pkg/executor/output/output.go
pkg/ui/errors.go
pkg/ui/printers.go
pkg/ui/ui.go

feat: add stderr ui

---

pkg/ui/errors.go

Conditional stderr write
-
-
-

fix: conditional stderr write

---

cmd/kubectl-testkube/commands/crds/tests_crds.go
cmd/kubectl-testkube/commands/dashboard.go

Use crd package for crd generation
-
-
-

fix: use crd package for crd generation

---

api/v1/testkube.yaml
internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_test_suite_execution_request.go

sync test suite execution flag
-
-
-

feat: sync test suite execution flag

---

internal/app/api/v1/testsuites.go

pass test suite execution by reference
-
-
-

fix: pass test suite execution by reference

---

.github/workflows/release.yaml

Trigger build of ArgoCD Docker image in `kubeshop/testkube-argocd` repo, when a new release was created, passing a tag version.

build: Trigger argocd image

---

docs/executor-custom.md

https://github.com/kubeshop/testkube/issues/1678
-
-
-

refactor: update crd docs

---

pkg/executor/client/job.go
pkg/jobs/jobclient.go

fix: capture init log errors

---

internal/app/api/v1/executions.go
pkg/mapper/tests/kube_openapi.go
pkg/slacknotifier/slack.go

fix: slack blocks template as it complains when there are empty strings

---

Makefile

I didn't understand the purpose of these vars. Any ideas, why do we need additional vars, why env vars are not enough?
-
-
-

fix: remove vars

---

pkg/crd/templates/test.tmpl

use latest test crd version
-
-
-

fix: use latest test crd version

---

internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go

fix: escape data for crd

---

build/api-server/Dockerfile

fix: fixed docker build

---

pkg/telemetry/sender_sio_test.go
pkg/telemetry/telemetry.go

fix: added segmentio to list of senders

---

cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/config/storage.go
docs/cli/kubectl-testkube.md
docs/cli/kubectl-testkube_completion.md
docs/cli/kubectl-testkube_completion_bash.md
docs/cli/kubectl-testkube_completion_fish.md
docs/cli/kubectl-testkube_completion_powershell.md
docs/cli/kubectl-testkube_completion_zsh.md
docs/cli/kubectl-testkube_get_executor.md
docs/cli/kubectl-testkube_get_test.md
docs/cli/kubectl-testkube_get_testsuite.md
docs/cli/kubectl-testkube_get_webhook.md
internal/app/api/v1/crd.go
internal/app/api/v1/executor.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/app/api/v1/webhook.go
pkg/crd/crd.go
pkg/crd/crd_test.go

fix: default api uri value

---

.github/workflows/docker-build-stage.yaml
.github/workflows/docker-build.yaml
build/api-server/Dockerfile
pkg/telemetry/sender_sio.go

feat: added segmentio build keys for api server

---

internal/app/api/v1/server.go

feat: send heartbeat event on server start

---

internal/app/api/v1/server.go
pkg/server/config.go
pkg/server/httpserver.go
pkg/telemetry/payload.go
pkg/telemetry/telemetry.go

fix: server start should be clusterId based

---

cmd/api-server/main.go
internal/app/api/v1/server.go
pkg/server/httpserver.go

fix: improved telemetry debug on cluster

---

cmd/api-server/main.go
internal/app/api/v1/server.go

fix: telemetry heartbeat event based on valid config data

---

cmd/kubectl-testkube/commands/common/crd.go

Print crd without special chars
-
-
-

fix: print crd without special chars

---

cmd/kubectl-testkube/commands/tests/run.go

feat: split args

---

docs/getting-started.md

restructured the executable commands on the page
- while copying the executable commands the output were also being copied
- seperated the commands and corresponding output  
- updated the doc

docs: Updated getting-started.md

---

cmd/kubectl-testkube/commands/dashboard.go

automatic dashboard port selection
-
-
-

feat: automatic dashboard port selection

---

cmd/kubectl-testkube/commands/tests/update.go
cmd/kubectl-testkube/commands/testsuites/update.go

Check name parameter for test and testsuite update
-
-
-

fix: check name parameter for test and testsuite update

---

cmd/kubectl-testkube/commands/tests/run.go
test/perf/testkube-homepage.js

fix: change test string

---

docs/getting-started.md

Correction of delete command order
-
-
-

fix: correction of delete command order

---

docs/executor-kubepug.md
mkdocs.yml

This PR adds documentation for the KubePug executor.
-
- docs
-

docs: KubePug executor

---

cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
internal/app/api/v1/executions.go
pkg/api/v1/testkube/model_execution.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_execution_request.go
pkg/api/v1/testkube/model_execution_summary.go
pkg/mapper/executions/sumary_test.go
pkg/mapper/executions/summary.go

feat: add execution number to executions

---

test/postman/TestKube-Sanity.postman_collection.json

fix: status code change

---

pkg/api/v1/testkube/model_test_suite_with_execution_base_extended.go
pkg/api/v1/testkube/model_test_with_execution_base_extended.go

fix: segmentation fault on getting execution labels

---

cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
internal/app/api/v1/executions.go
internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_executions_result_extended.go

feat: merge test name and execution number into execution name

---

pkg/slacknotifier/slack.go

fix: range panic

---

pkg/git/checkout.go

checkout commit from history
-
-
-

feat: checkout commit from history

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml
.goreleaser.yml
build/installer/windows/testkube.wxs
build/installer/windows/tk.bat

feat: added tk symlinks 

---

build/installer/windows/testkube.wxs

fix: windows build keypath error

---

.goreleaser.yml

fix: full path for symlinks

---

internal/app/api/v1/labels.go
pkg/data/set/set.go
pkg/data/set/set_test.go

fix: make labels unique

---

.goreleaser.yml
api/v1/testkube.yaml
build/installer/windows/testkube.bat
build/installer/windows/testkube.wxs
internal/app/api/v1/executor.go
internal/app/api/v1/server.go
pkg/api/v1/testkube/model_executor.go
pkg/api/v1/testkube/model_executor_create_request.go

fix: features loaded in executors

---

.github/workflows/release.yaml
choco/testkube.nuspec
choco/tools/VERIFICATION.txt
choco/tools/chocolateyInstall.ps1
choco/update.ps1

Added a step for creating a PR since we cannot push to `main` branch to update Testkube version for choco.
-
-
-

fix: choco ci adjusting

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml

missed copy for testkube.bat
-
-
-

fix: missed copy for testkube.bat

---

.github/workflows/release.yaml

Comment out flow to push packages to chocolatey repo because of 403 error. Looks like an IP block. To be investigated once I'm back next week.
https://docs.chocolatey.org/en-us/troubleshooting#im-getting-a-403-unauthorized-issue-when-attempting-to-use-the-community-package-repository
```
Attempting to push testkube.1.3.42.nupkg to https://push.chocolatey.org/
Failed to process request. 'Forbidden'. 
The remote server returned an error: (403) Forbidden..
```
-
-
-

comment out choco flow

---

docs/postman-executors.md

Remove unavailable video.
-
-
-

docs: Update postman-executors.md

---

mkdocs.yml

Remove "Tests" from items in the "TestTypes" menu.
-
-
-

docs: Update mkdocs.yml

---

docs/artifacts-storage.md
internal/app/api/v1/executions.go
pkg/api/v1/client/test.go

fix: pass env vars

---

docs/testkube-automation.md

`GitHUb` is changed into `GitHub`

fix: `GitHUb` is changed into `GitHub`

---

docs/scheduling.md

`In order start` changed to `In order to start` .
-
-
-

fix: Update scheduling.md

---

docs/getting-started.md

follow-up to discord conversation
-
-
-

docs: update branch name in getting started docs

---

.goreleaser-dev.yml
.goreleaser.yml

fix: brew symlink fix

---

docs/executor-postman.md

Remove video with broken link from Postman doc.
-
-
-

docs: Update executor-postman.md

---

.github/workflows/release.yaml
choco/update.ps1

Uncommented CI for pushing packages to our own choco repository - http://chocolatey.testkube.io
-
-
-

fix: Ci for chocolatey repo

---

README.md
docs/executor-ginkgo.md
mkdocs.yml

docs: added Ginkgo executor

---

docs/cli/kubectl-testkube.md
docs/cli/kubectl-testkube_create-ticket.md
docs/cli/kubectl-testkube_debug.md

Found the `make docs` command, ran it, and noticed some things were missing for the debug commands.
-
-
-

docs: generate cli docs

---

docs/cypress-executors.md

Extra Punctuation was used.
-
-
-

docs: update cpress-executors.md

---

internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go
internal/pkg/api/repository/testresult/mongo.go
internal/pkg/api/repository/testresult/mongo_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

feat: metrics better duration format

---

api/v1/testkube.yaml
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_test_metrics.go
pkg/api/v1/testkube/model_test_metrics_executions.go
pkg/api/v1/testkube/model_test_suite_metrics.go
pkg/api/v1/testkube/model_test_suite_metrics_executions.go

feat: additional durations as ms

---

.github/CODEOWNERS
Makefile
build/api-server/Dockerfile

feat: Testkube API server root-less

---

docs/scheduling.md

fix: scheduling docs

---

internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_test_suite_execution_extended.go

fix: add nil check

---

choco/update.ps1

Update link for choco repo from `http` to `https`
-
-
-

fix: update url for choco repo

---

.github/workflows/release-dev.yaml
.github/workflows/release.yaml

to address apt error:
```
{"FailedFiles":["/srv/aptly/.aptly/upload/testkube/testkube_1.2.0_linux_386.deb",
"/srv/aptly/.aptly/upload/testkube/testkube_1.2.0_linux_amd64.deb","/srv/aptly/
.aptly/upload/testkube/testkube_1.2.0_linux_arm64.deb"],"Report":{"Warnings"
:["Unable to add package to repo testkube_1.2.0_i386: conflict in package test
kube_1.2.0_i386","Unable to add package to repo testkube_1.2.0_amd64: conf
lict in package testkube_1.2.0_amd64","Unable to add package to repo testkub
e_1.2.0_arm64: conflict in package testkube_1.2.0_arm64"],"Added":["testkub
e_1.4.23_i386 added","testkube_1.4.23_amd64 added","testkube_1.4.23_arm
64 added"],"Removed":[]}}
```
-
-
-

ci: force replace already existing packages

---

.goreleaser-dev.yml
.goreleaser.yml
docs/install.sh

fix: added deps and symlinks to install.sh

---

api/v1/testkube.yaml
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_test_metrics_executions.go
pkg/api/v1/testkube/model_test_suite_metrics_executions.go

feat: metrics added name and start time to stats

---

docs/executor-cypress.md
docs/executor-k6.md
docs/executor-soapui.md
mkdocs.yml

Cypress, k6, and SoapUI updated.
-
-
-

docs: Add blog link to executor docs

---

internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/mongo.go

fix: order descending in metrics

---

api/v1/testkube.yaml
internal/app/api/v1/executions_test.go
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/common/metrics.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go
internal/pkg/api/repository/testresult/mongo_test.go
pkg/api/v1/testkube/model_executions_metrics.go

feat: last n days for metrics

---

Makefile
internal/app/api/v1/executions.go
internal/app/api/v1/executions_test.go
internal/app/api/v1/server.go
pkg/executor/client/interface.go
pkg/executor/client/job.go

Closes #1964
Test Suite individual test execution end time was missing due to pointer issue. Removed functions were not used.
-
-
-

fix: missing end time

---

internal/app/api/v1/server.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/result/filter.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/filter.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go

feat: last n days for executions

---

docs/testkube-automation.md
pkg/crd/templates/executor.tmpl
pkg/crd/templates/test.tmpl
pkg/crd/templates/testsuite.tmpl
pkg/crd/templates/webhook.tmpl

fix: empty crd maps and arrays

---

README.md

docs: added license badge in README.md

---

docs/installing.md

Updates the Installation docs to make it more simple

docs: Update Installation doc

---

api/v1/testkube.yaml
internal/app/api/v1/executions.go
internal/app/api/v1/executions_test.go
internal/pkg/api/repository/common/metrics.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_artifact.go
pkg/api/v1/testkube/model_execution.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_execution_request.go
pkg/api/v1/testkube/model_execution_summary.go
pkg/api/v1/testkube/model_executions_metrics.go
pkg/api/v1/testkube/model_executions_metrics_executions.go
pkg/api/v1/testkube/model_executions_totals.go
pkg/api/v1/testkube/model_problem.go
pkg/api/v1/testkube/model_test_suite.go
pkg/api/v1/testkube/model_test_suite_execution.go
pkg/api/v1/testkube/model_test_suite_execution_request.go
pkg/api/v1/testkube/model_test_suite_execution_summary.go
pkg/api/v1/testkube/model_test_suite_step_delay.go
pkg/api/v1/testkube/model_test_suite_upsert_request.go
pkg/mapper/tests/kube_openapi.go
pkg/mapper/tests/openapi_kube.go
pkg/mapper/testsuites/kube_openapi.go
pkg/mapper/testsuites/openapi_kube.go
pkg/storage/minio/minio.go
pkg/types/duration.go

feat: added ms to testsuites executions and last and rewritten openapi spec

---

docs/installing.md

docs: Update installing.md formatting

---

.github/workflows/release-dev.yaml
choco/testkube.nuspec

Added deps to chocolatey. Tested it as well.
-
-
-

feat: install helm and kubectl automatically with chocolatey

---

cmd/kubectl-testkube/commands/tests/create.go
cmd/kubectl-testkube/commands/tests/get.go
cmd/kubectl-testkube/commands/tests/renderer/test_obj.go
internal/app/api/v1/executions.go
internal/app/api/v1/tests.go

fix: pass variable file from crd

---

internal/app/api/v1/executions.go
internal/app/api/v1/server.go
test/postman/VeryLong.postman_collection.json

feat: websockets for logs

---

api/v1/testkube.yaml

Typos in test-suite step definition examples.
-
-
-

fix: update testkube.yaml

---

internal/app/api/v1/server.go

fix: variable names

---

docs/executor-k6.md
docs/installing.md

This PR updates docs on k6 test results and adds info on dependencies.
-
- docs
-

docs: add dependency & k6 updates

---

cmd/kubectl-testkube/commands/crds/tests_crds.go
docs/generate-test-crds.md
mkdocs.yml
pkg/test/detector/curltest.go
pkg/test/detector/detector.go
pkg/test/detector/detector_test.go
pkg/test/detector/interface.go
pkg/test/detector/k6.go
pkg/test/detector/postmancollection.go
pkg/test/detector/postmancollection_test.go

feat: generate tests with env files

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json

Fixing the search config to enable better search results and add redirects for executors
-
-
-

docs: fix search and add redirects

---

cmd/api-server/main.go
cmd/kubectl-testkube/commands/executors/create.go
docs/docs/5-cli-reference/kubectl-testkube_create_executor.md
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go

fix: change sorting for test and testsuite

---

docs/src/css/custom.css

Fixing the testkube logo size 
-
-
-

docs: fix testkube logo 

---

.github/CODEOWNERS
pkg/api/v1/testkube/model_event_extended.go

fix: valid event type for testsuite start event

---

.github/CODEOWNERS
pkg/api/v1/testkube/model_event_extended.go
pkg/api/v1/testkube/model_event_extended_test.go
pkg/api/v1/testkube/model_execution_result_extended.go
pkg/api/v1/testkube/model_test_suite_execution_extended.go
pkg/event/kind/slack/listener.go
pkg/slacknotifier/slack.go

feat: event for testsuites in Slack notifier

---

pkg/event/emitter.go

fix: nil pointer panic on log for notify test suite based event

---

docs/package-lock.json
docs/package.json

chore: upgrade docusaurus to 2.1.0

---

api/v1/testkube.yaml

fix: remove readonly for secret reference

---

.github/workflows/manual-choco-release.yaml
.github/workflows/release.yaml
choco/update.ps1

Added a manual action flow that triggers packaging and pushing packages to official chocolatey repo.
-
-
-

ci: add manual trigger for choco flow

---

cmd/kubectl-testkube/commands/constants.go
docs/docs/1-installing.md
docs/package-lock.json

docs: OpenShift installation

---

pkg/crd/templates/test.tmpl
pkg/crd/templates/testsuite.tmpl

fix: change crd for variables

---

api/v1/testkube.yaml
internal/app/api/v1/executions_test.go
internal/app/api/v1/testsuites.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/interface.go
internal/pkg/api/repository/testresult/mongo.go
pkg/api/v1/testkube/model_execution.go
pkg/api/v1/testkube/model_execution_extended.go
pkg/api/v1/testkube/model_execution_step_result.go
pkg/api/v1/testkube/model_test_suite_execution_extended.go
pkg/executor/client/job.go

feat: duration ms in execution

---

docs/README.md

docs: include more local development instructions

---

docs/docs/1-installing.md

updated spelling to install
-
-
-

docs: Update 1-installing.md

---

cmd/kubectl-testkube/commands/crds/tests_crds.go

fix: copy Execution Request

---

pkg/executor/utils.go
pkg/executor/utils_test.go

fix: init container failure hungs whole test

---

cmd/kubectl-testkube/commands/tests/update.go

fix: remove alias

---

README.md

I was reading through the README and saw a broken link
-
-
-

docs: Fixed link in README

---

api/v1/testkube.yaml
internal/app/api/v1/testtriggers.go
pkg/crd/templates/testtrigger.tmpl
pkg/mapper/testtriggers/kube_openapi.go
pkg/mapper/testtriggers/openapi_kube.go

Fix issues with test trigger CRUD api and fix openapi docs
-
- improved test triggers openapi docs
- bugs with test triggers CRUD api

fix: test triggers api

---

cmd/api-server/main.go
pkg/scheduler/service.go
pkg/triggers/executor_test.go

fix: missed metrics init

---

docs/docs/3-using-testkube/triggers.md

add docs for test triggers
-
-
-

docs: test triggers

---

pkg/executor/content/config_files.go
pkg/executor/content/config_files_test.go

Related to https://github.com/kubeshop/testkube/pull/2488 - placing files was not updated
-
-
-

fix: update PlaceFiles signature

---

pkg/event/emitter.go
pkg/event/emitter_test.go
pkg/event/kind/common/interface_test.go
pkg/event/kind/common/interfaces.go
pkg/event/kind/dummy/listener.go
pkg/event/kind/slack/listener.go
pkg/event/kind/websocket/listener.go

fix: change listeners update

---

cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/run.go
internal/app/api/v1/executions.go
internal/app/api/v1/tests.go
pkg/api/v1/testkube/model_test_base_extended.go

fix: use same binary args formatting in cli and api

---

pkg/scheduler/test_scheduler.go

fix: support empty tests

---

api/v1/testkube.yaml
cmd/api-server/main.go
internal/app/api/metrics/metrics.go
internal/app/api/v1/server.go
internal/app/api/v1/testtriggers.go

Add support for bulk update test triggers
-
- adds bulk update test triggers endpoint
- generate trigger name from spec if name is not provided
- wipe & clean approach
-

feat: add bulk update test triggers endpoint

---

pkg/scheduler/test_scheduler.go

fix: use test source content when test content is empty

---

pkg/scheduler/test_scheduler.go

fix: use default content type

---

docs/CNAME

fix: docs cname

---

docs/docusaurus.config.js

fix: doc baseurl

---

test/cli-tests/.babelrc
test/cli-tests/.env
test/cli-tests/.gitignore
test/cli-tests/helpers/api-helpers.js
test/cli-tests/helpers/output-validators.js
test/cli-tests/helpers/test-data-handlers.js
test/cli-tests/package-lock.json
test/cli-tests/package.json
test/cli-tests/test-data/tests.json
test/cli-tests/tests/create-test.js
test/cli-tests/tests/run-test.js
test/cli-tests/tests/test.js

- Mocha+Chai+Babel
- API helpers
- Output validators
- Test Data (matching API structure)
- Create and Run tests for Cypress, K6 and Postman

feat: CLI tests - setup, initial create and run test scenarios

---

test/cli-tests/helpers/api-helpers.js
test/cli-tests/helpers/output-validators.js
test/cli-tests/test-data/tests.json
test/cli-tests/tests/run-test.js
test/cli-tests/tests/test-results.js

- CLI tests - execution results and validation - 5 cases covered:
- Cypress, K6 and Postman - positive cases
- Negative cases for test failure and test init failure
- API helpers
- output validators

feat: CLI tests - execution results and validation, API helpers extended, test output validators

---

cmd/kubectl-testkube/commands/testsuites/create.go
cmd/kubectl-testkube/commands/testsuites/update.go

fix: change name validation for testsuite upsert

---

docs/docs/1-installing.md
docs/docs/3-using-testkube/scheduling.md
docs/docs/3-using-testkube/tests/tests-getting-results.md
docs/docs/4-test-types/executor-custom.md
docs/docs/4-test-types/executor-cypress.md
docs/docs/7-integrations/testkube-automation.md
docs/docs/8-authentication/oauth-cli.md
docs/docs/8-authentication/oauth-ui.md
docs/docs/9-contributing/contributing.md
docs/docs/9-contributing/development/developments.md

fix: various typos in documentation

---

cmd/choco-stub/main.go

feat: choco-stub

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/tests/common.go
internal/app/api/v1/server.go
internal/app/api/v1/uploads.go
internal/app/api/v1/uploads_test.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/uploads.go
pkg/api/v1/testkube/model_test_base.go
pkg/api/v1/testkube/model_test_upsert_request.go
pkg/executor/content/uploads.go
pkg/mapper/tests/kube_openapi.go
pkg/mapper/tests/openapi_kube.go
pkg/storage/minio/minio.go
pkg/storage/storage.go

* use more consistent naming
* update endpoint that caused issue
-
-
-

fix: upload files

---

internal/app/api/v1/uploads.go
internal/app/api/v1/uploads_test.go
pkg/executor/content/uploads.go
pkg/storage/minio/minio.go
pkg/storage/minio/minio_test.go
pkg/storage/storage.go

fix: shorten bucket names

---

cmd/api-server/main.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_test.go
internal/pkg/api/repository/testresult/mongo.go
internal/pkg/api/repository/testresult/mongo_test.go

fix: allow disk use parameter for mongo

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/tests/run.go
docs/docs/3-using-testkube/tests/tests-running.md
pkg/api/v1/client/interface.go
pkg/api/v1/client/test.go
pkg/api/v1/testkube/model_execution.go
pkg/api/v1/testkube/model_execution_request.go
pkg/executor/content/uploads.go
pkg/scheduler/test_scheduler.go

Use bucketname instead of execution name
-
-
-

fix: uploads execution

---

docs/docs/index.mdx

docs: 1.7 Blog Post

---

pkg/telemetry/payload.go
pkg/triggers/service.go

fix: source steps telemetry fields

---

pkg/executor/containerexecutor/templates/job.tmpl
pkg/telemetry/sender_sio.go
pkg/telemetry/sender_sio_test.go

fix: segmentio mapping

---

pkg/telemetry/payload.go
pkg/telemetry/sender_sio.go

fix: remove empty segment.io fields

---

api/v1/testkube.yaml
internal/app/api/v1/tests.go
internal/app/api/v1/testsuites.go

feat: paging for test and test suite

---

cmd/api-server/main.go

fix: env var name

---

pkg/executor/containerexecutor/templates/job.tmpl

fix: adjust container template

---

docs/docs/4-test-types/container-executor.md

fix: artifacts docs

---

DESIGN.md
README.md

We'd like to also foster design contributions by the community on Testkube and get in front of potential designer who might have ideas on how to improve specific flows and get more reputation. 
Therefor we're adding a first iteration of design contribution guidelines to our repo

docs: add design contribution guidelines

---

docs/docs/4-test-types/executor-jmeter.md

docs: fixed jmeter example

---

cmd/kubectl-testkube/commands/artifacts/artifacts.go
cmd/kubectl-testkube/commands/download.go

During the demo, this was printed out as "File %s..."
-
-
-

fix: filename is not shown

---

docs/docs/3-using-testkube/tests/tests-creating.md
docs/docs/4-test-types/container-executor.md
pkg/crd/templates/test.tmpl

feat: artifact job template examples

---

docs/docs/3-using-testkube/dependencies.md

Fix file reference in docs
-
-
-

docs: update docs on mongo ssl connection file config in secret

---

docs/docs/0-cloud.md
docs/docs/0-testkube-cloud/installing-agent.md
docs/docs/index.mdx

docs: added basic Testkube Cloud docs

---

docs/docs/3-using-testkube/dependencies.md

Line numbers in helm charts are changing often as seen in team s&t, so they will be removed.
-
-
-

docs: remove line number from links as helm chart is often changing

---

.github/workflows/codeql-analysis.yml

Added `paths` filter to run code analysis against so that it won't scan all code in the repo and take less time to execute the job.
-
-
-

ci: update codeql flow

---

docs/docs/0-testkube-cloud/1-installing-agent.md

docs: fix creating environment screenshot  remove test uri

---

cmd/kubectl-testkube/commands/context/get.go
cmd/kubectl-testkube/commands/context/set.go
cmd/kubectl-testkube/commands/context/ui.go
cmd/kubectl-testkube/commands/get.go
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/commands/set.go
cmd/kubectl-testkube/config/data.go

feat: added context configuration to testkube cli

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/testsuites/run.go
docs/docs/5-cli-reference/testkube_run_testsuite.md
pkg/api/v1/client/interface.go
pkg/api/v1/client/test.go
pkg/api/v1/client/testsuite.go
pkg/api/v1/testkube/model_test_suite_execution_request.go
pkg/api/v1/testkube/model_test_suite_execution_update_request.go
pkg/scheduler/testsuite_scheduler.go

feat: testsuite dynamic repo

---

internal/app/api/v1/executions.go
pkg/api/v1/testkube/model_execution_result_extended.go
pkg/executor/agent/agent.go
pkg/executor/client/job.go
pkg/executor/common_test.go
pkg/ui/config.go
pkg/ui/icons.go

Addresses issues https://github.com/kubeshop/testkube/issues/2669 and https://github.com/kubeshop/testkube/issues/2536, touches on https://github.com/kubeshop/testkube/issues/2396
-
-
-

fix: show error messages in output for dashboard

---

cmd/kubectl-testkube/commands/dashboard.go
cmd/kubectl-testkube/commands/delete.go
cmd/kubectl-testkube/commands/migrate.go
cmd/kubectl-testkube/commands/tests/update.go
cmd/kubectl-testkube/commands/testsources/get.go
cmd/kubectl-testkube/commands/webhooks/get.go
docs/docs/5-cli-reference/testkube_dashboard.md
docs/docs/5-cli-reference/testkube_delete.md
docs/docs/5-cli-reference/testkube_delete_executor.md
docs/docs/5-cli-reference/testkube_delete_test.md
docs/docs/5-cli-reference/testkube_delete_testsource.md
docs/docs/5-cli-reference/testkube_delete_testsuite.md
docs/docs/5-cli-reference/testkube_delete_webhook.md
docs/docs/5-cli-reference/testkube_get_testsource.md
docs/docs/5-cli-reference/testkube_get_webhook.md
docs/docs/5-cli-reference/testkube_migrate.md
pkg/api/v1/testkube/model_test_base_extended.go
pkg/api/v1/testkube/model_test_with_execution_summary_base_extended.go

fix: remove duplicated namespace flags

---

cmd/kubectl-testkube/config/config.go
cmd/kubectl-testkube/config/config_test.go
cmd/kubectl-testkube/config/storage.go
pkg/telemetry/payload.go
pkg/telemetry/sender_sio.go
pkg/telemetry/telemetry.go

Changed getting initialized storage to on-demand storage 
-
-
-

fix: telemetry config warning

---

api/v1/testkube.yaml
internal/app/api/v1/handlers.go
pkg/api/v1/testkube/model_server_info.go

feat: return namespace in server info

---

pkg/event/emitter.go
pkg/event/emitter_test.go

fix: clean missing listener kinds

---

pkg/crd/templates/testsuite.tmpl

fix: testsuite crd template

---

pkg/executor/output/writer.go
pkg/executor/secret/manager.go

fix: obfuscate error

---

cmd/kubectl-testkube/commands/crds/tests_crds.go
cmd/kubectl-testkube/commands/tests/get.go
cmd/kubectl-testkube/commands/testsources/get.go
cmd/kubectl-testkube/commands/testsuites/create.go
cmd/kubectl-testkube/commands/testsuites/get.go
internal/app/api/v1/executor.go
internal/app/api/v1/testsource.go
internal/app/api/v1/testsuites.go
pkg/api/v1/testkube/model_test_base_extended.go
pkg/api/v1/testkube/model_test_suite_base_extended.go
pkg/api/v1/testkube/model_test_suite_upsert_request_extended.go
pkg/api/v1/testkube/model_test_upsert_request_extended.go
pkg/crd/templates/test.tmpl
pkg/crd/templates/testsuite.tmpl

fix: add missing quotes

---

cmd/kubectl-testkube/commands/executors/create.go
cmd/kubectl-testkube/commands/executors/get.go
internal/app/api/v1/executor.go
pkg/api/v1/testkube/model_executor_extended.go
pkg/api/v1/testkube/model_executor_upsert_request_extended.go
pkg/api/v1/testkube/model_test_base_extended.go
pkg/api/v1/testkube/model_test_upsert_request_extended.go

fix: quote args and command

---

cmd/api-server/main.go
internal/app/api/v1/executions_test.go
internal/app/api/v1/uploads_test.go
internal/pkg/api/repository/result/interface.go
internal/pkg/api/repository/result/minio_output.go
internal/pkg/api/repository/result/mock_repository.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/result/mongo_output.go
pkg/slack/slack.go
pkg/storage/minio/minio.go
pkg/storage/storage.go

Stage 2 for https://github.com/kubeshop/testkube/issues/2497
-
-
-

feat: implement log(output) storage for minio

---

pkg/envs/variables.go
pkg/executor/content/fetcher.go
pkg/executor/process.go
pkg/executor/scraper/scraper.go

This PR extracts params handling and adds logs to common parts of the executors located in the Testkube repo.
See: https://github.com/kubeshop/testkube/issues/2396
-
-
-

feat: add logs to common executor parts

---

pkg/executor/process.go

fix: check for nil pointer

---

api/v1/testkube.yaml
pkg/api/v1/client/common_test.go
pkg/api/v1/testkube/model_executor_output.go
pkg/executor/output/output.go

Adding timestamp to output logs
-
-
-

fix: add timestamp to logs

---

pkg/executor/content/uploads.go
pkg/storage/minio/minio.go
pkg/ui/icons.go

fix: downgrade uploads errors

---

cmd/api-server/main.go
internal/pkg/api/repository/result/mongo.go
internal/pkg/api/repository/testresult/mongo.go

fix: optional allow disk use

---

pkg/slack/slack.go

Closes https://github.com/kubeshop/testkube/issues/3055
-
-
-

fix: test type is not set on testsuite slack message

---

docs/docs/index.mdx

With new blog posts and release notes.
-
-
-

docs: Update Welcome Page

---

cmd/api-server/main.go
pkg/storage/minio/minio.go

Related to https://github.com/kubeshop/testkube/issues/3036
-
-
-

fix: fallback on mongo for logs storage when minio is not available

---

docs/docs/1-installing.md
docs/docs/13-Logging.md

docs: add documentation for logs storage

---

pkg/telemetry/sender_sio.go

fix: new segmentio cli key

---

docs/docs/3-using-testkube/triggers.md

Update documentation for Test Triggers
-
-
-

docs: update test triggers doc

---

pkg/triggers/diff.go
pkg/triggers/executor_test.go
pkg/triggers/matcher.go
pkg/triggers/matcher_test.go
pkg/triggers/scraper.go
pkg/triggers/service.go

Add backoff when between conditions check iterations and add tests for retries
-
-
-

feat: add backoff and test for conditions timeout

---

pkg/api/v1/testkube/model_artifact_update_request_extended.go
pkg/api/v1/testkube/model_repository_update_exetended.go
pkg/mapper/tests/openapi_kube.go
pkg/mapper/testsources/mapper.go

fix: support empty repo and artifacts for update

---

pkg/cloud/data/command.go
pkg/repository/result/interface.go
pkg/repository/result/minio_output.go
pkg/repository/result/mongo.go
pkg/repository/result/mongo_output.go

refactor result repository to support new fields
Cloud API is a lot more performant now because it utilises the fields
-
-
-

feat: refactor result repository to support new fields

---

pkg/executor/client/job.go

Related to https://github.com/kubeshop/testkube/issues/2482
-
-
-

fix: negative test output message + some more logging

---

docs/docs/1-installing.md
docs/docs/4-test-types/executor-cypress.md

-
- added embeds for video tutorials on installation and cypress executor
-

docs: add video tutorials to docs

---

api/v1/testkube.yaml
build/api-server/Dockerfile
internal/app/api/v1/repository.go
internal/app/api/v1/server.go

feat: validate repo

---

pkg/storage/minio/minio.go

Related to https://github.com/kubeshop/testkube/issues/3160
-
-
-

fix: trim id prefix from list files

---

pkg/api/v1/testkube/model_execution_result_extended.go
pkg/repository/result/mongo.go
pkg/scheduler/test_scheduler.go

Issue: https://github.com/kubeshop/testkube/issues/3106
The problem seemed to be that we were updating a field of an object that had pointer attributes, and were updating the original object that was supposed to stay the same.
-
-
-

fix: no logs in test suites

---

cmd/kubectl-testkube/commands/common.go
cmd/kubectl-testkube/commands/context/set.go
cmd/kubectl-testkube/commands/context/ui.go
cmd/kubectl-testkube/commands/root.go
cmd/kubectl-testkube/commands/upgrade.go
cmd/kubectl-testkube/config/data.go
pkg/ui/input.go
pkg/ui/printers.go
pkg/ui/ui.go

Updated UI of upgrade command and handled Cloud upgrade if cloud context is set
-
-
-

feat: upgrade confirmation and context info

---

api/v1/testkube.yaml

fix: duplicate op ids

---

docs/docs/1-installing.md

Since we now use MongoDB chart version `12.1.31` there is no need to install custom one manually. We just need to include the configuration to the `values.yaml` file. Besides that, it's required to add security Context to webhook for tk-operator.
-
-
-

docs: update TK installation on Openshift

---

docs/docs/7-integrations/testkube-automation.md

docs: fix github action url

---

README.md
docs/docs/test-types/container-executor.md
docs/docs/test-types/executor-custom.md
docs/docs/test-types/executor-playwright.md

docs: add playwright executor docs

---

docs/sidebars.js

docs: add test types category page

---

install.sh

Adding back at the top of the repository, as the previous location isn't where it could be expected to be. 
-
-
-

fix: add back install.sh script

---

cmd/kubectl-testkube/commands/common/flags.go
cmd/kubectl-testkube/commands/crds/tests_crds.go
cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/commands/tests/run.go
cmd/kubectl-testkube/commands/testsuites/common.go
cmd/kubectl-testkube/commands/testsuites/run.go

fix: sync generate crds with latest flags

---

docs/docs/using-testkube/test-suites/testsuites-creating.md

removed duplicated `steps:` line to ensure YAML example was valid
-
-
-

docs: remove duplicate line

---

docs/docs/overview/does-testkube-replace-cicd.md

docs: Update does-testkube-replace-cicd.md

---

docs/docs/using-testkube/common-issues.md

docs: Update common-issues.md

---

docs/docs/concepts/common-issues.md
docs/docs/concepts/dashboard.md
docs/docs/concepts/secrets.md
docs/docs/concepts/test-suites/testsuites-creating.md
docs/docs/concepts/test-suites/testsuites-getting-results.md
docs/docs/concepts/test-suites/testsuites-running.md
docs/docs/concepts/tests/tests-getting-results.md
docs/docs/concepts/tests/tests-running.md
docs/docs/contributing/development/crds.md
docs/docs/contributing/development/index.md
docs/docs/guides/slack-integration.md
docs/docs/guides/webhooks.md
docs/docs/reference/architecture.md
docs/docs/reference/helm-chart.md
docs/docs/reference/telemetry.md
docs/docs/test-types/container-executor.md
docs/docs/testkube-cloud/intro.md

docs: standarize style

---

docs/docs/test-types/container-executor.mdx

Signed-off-by: Abdallah Abedraba
<aabedraba@gmail.com>
-
-
-

docs: start using tabs for Dashboard vs CLI instructions

---

pkg/executor/common.go
pkg/storage/minio/minio.go

Closes https://github.com/kubeshop/testkube/issues/2699
-
-
-

fix: cutting executor log lines

---

api/v1/testkube.yaml

fix: invalid spec

---

docs/docs/index.mdx
docs/docs/test-types/executor-cypress.mdx
docs/src/css/custom.css
test/cypress/executor-tests/crd/crd.yaml
test/playwright/executor-tests/crd/crd.yaml
test/playwright/executor-tests/playwright-project/package-lock.json
test/playwright/executor-tests/playwright-project/package.json
test/playwright/executor-tests/playwright-project/playwright.config.js
test/playwright/executor-tests/playwright-project/tests/smoke.spec.js
test/scripts/executor-tests/run.sh
test/suites/executor-playwright-smoke-tests.json

changed sidebar color for styling
-
-
-

docs: minor style update

---

docs/docs/overview/testkube-benefits.md
docs/src/theme/NotFound/index.js

docs: add testkube-benefits page

---

docs/docs/guides/cicd/github-actions.md
docs/docs/guides/going-to-production/aws.md
docs/docs/reference/helm-chart.md

fix: unifying helm repo name

---

cmd/kubectl-testkube/commands/common.go
cmd/kubectl-testkube/commands/upgrade.go

feat: update cloud upgrade command

---

docs/docs/concepts/artifacts-storage.md
docs/docs/concepts/common-issues.md
docs/docs/guides/cicd/github-actions.md
docs/docs/guides/going-to-production/aws.md
docs/docs/reference/helm-chart.md

fix: repo references to kubeshop instead of old ones 

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/abort.go
cmd/kubectl-testkube/commands/generate/docs.go
cmd/kubectl-testkube/commands/tests/abort.go
docs/docs/reference/cli/testkube_abort.md
docs/docs/reference/cli/testkube_abort_executions.md
internal/app/api/v1/executions.go
internal/app/api/v1/server.go
internal/app/api/v1/tests.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/test.go

Closes https://github.com/kubeshop/testkube/issues/2925
-
-
-

feat: add abort all executions for a test

---

docs/docs/concepts/triggers.md

add Test Triggers video to docs
-
-
-

docs: add test trigger video to docs

---

pkg/api/v1/testkube/model_event_extended.go
pkg/api/v1/testkube/model_event_extended_test.go

feat: websockets data without logs

---

cmd/kubectl-testkube/commands/common/client.go

fix: set default config type

---

pkg/api/v1/testkube/model_event_extended.go
pkg/api/v1/testkube/model_event_extended_test.go

This reverts commit 4b9b5282e171323366eb3633b7bd16944dd622cb.
-
-
-

feat: websockets data without logs (#3310) REVERT

---

pkg/envs/variables.go

feat: update runner env variables

---

pkg/telemetry/payload.go
pkg/telemetry/sender_sio.go
pkg/telemetry/sender_sio_test.go
pkg/telemetry/telemetry.go
pkg/telemetry/telemetry_test.go

Closes https://github.com/kubeshop/testkube/issues/3268
-
-
-

feat: add cluster type to the telemetry events

---

docs/docs/test-types/executor-cypress.mdx
docs/src/css/custom.css

added new admonition to Cypress executor with blog post copy
-
-
-

docs: add new info section to cypress executor

---

docs/docs/test-types/container-executor.mdx

Fix command line sample with arg "--command" for executor creation

docs: update container-executor.mdx

---

internal/app/api/v1/repository.go

fix: repo validate typo

---

pkg/git/checkout.go

fix: git sparse mode

---

cmd/api-server/main.go
internal/app/api/v1/server.go
pkg/executor/common.go

Refactor slack config to be loaded either through file or envvar
-
-
-

feat: refactor slack config

---

api/v1/testkube.yaml
internal/app/api/v1/crd.go
internal/app/api/v1/tests.go
pkg/api/v1/testkube/model_test_content_extended.go
pkg/crd/crd.go

https://github.com/kubeshop/testkube/issues/3065
-
-
-

feat: improve test errors

---

pkg/slack/slack.go

fix: add more logging to slack

---

pkg/telemetry/telemetry.go

fix: telemetry panic

---

.dockerignore

add .dockerignore to reduce context sent to Docker Daemon
-
-
-

feat: add dockerignore

---

pkg/executor/output/parser.go
pkg/executor/output/parser_test.go

Clean empty log lines from execution output
-
-
-

fix: do not append empty log lines

---

pkg/repository/common/metrics.go

fix: bloating calculate log error

---

pkg/api/v1/client/direct_client.go
pkg/api/v1/client/proxy_client.go

fix: use dir strcuture for downloading

---

.github/workflows/docker-build-prelease.yaml
.github/workflows/executor_docker-build.yaml

fix: mono flows

---

.github/workflows/docker-build-prelease.yaml
.github/workflows/docker-build.yaml
.github/workflows/executor_docker-build.yaml
.github/workflows/executor_helm-releaser.yaml

fix: tune monorepo cd

---

test/jmeter/executor-tests/crd/smoke.yaml
test/suites/executor-jmeter-smoke-tests.json

feat: JMeter executor tests extended with directory

---

contrib/executor/cypress/cmd/agent/main.go
contrib/executor/cypress/pkg/runner/cypress.go
go.mod

fix: sync cypress

---

docs/docs/concepts/triggers.md

Fixes a typo in the docs
- NA
-
-

docs: Fix typo in Triggers.md

---

docs/docs/guides/slack-integration.md
pkg/slack/slack.go

feat: execution id for slack

---

cmd/kubectl-testkube/commands/common/render/common.go
cmd/kubectl-testkube/commands/tests/executions.go
cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
cmd/kubectl-testkube/commands/tests/run.go
docs/docs/reference/cli/testkube.md
docs/docs/reference/cli/testkube_agent.md
docs/docs/reference/cli/testkube_agent_debug.md
docs/docs/reference/cli/testkube_get_execution.md
docs/docs/reference/cli/testkube_set_context.md

feat: logs only

---

internal/app/api/v1/testtriggers.go

Remove cluster scope call
-
-
-

fix: clean triggers only in installation namespace

---

cmd/kubectl-testkube/commands/context/set.go

feat: allow to set default namespace in context

---

docs/docs/getting-started/index.md
docs/docs/guides/going-to-production/authentication/oauth-cli.md
docs/docs/guides/going-to-production/index.md
docs/docs/reference/architecture.md

docs: clarify rationales for oauth authentication
Thanks to @vsukhin for his related support in this thread https://discord.com/channels/884464549347074049/885185660808474664/1088040873465487390 
Disclaimer: I'm still a testkube newcomer, I hope did not misunderstood things 
-
-
-

docs: clarify rationales for oauth authentication

---

docs/docs/reference/cli/testkube_generate_tests-crds.md

Refine description of the testkube generate tests-crds command to clarify on which types of files it supports, and the content of the generated CRD test files
-
-
- Refine description of the testkube generate tests-crds command to clarify on which types of files it supports, and the content of the generated CRD test files

docs: refine description of the testkube generate tests-crds command

---

docs/docs/concepts/tests/tests-creating.md

fix: doc typos

---

config/job-container-template.yml
config/job-template.yml
docs/docs/concepts/tests/tests-creating.md
pkg/executor/containerexecutor/templates/job.tmpl

Fixes https://github.com/kubeshop/testkube/issues/3570
-
-
-

fix: escape job name

---

pkg/triggers/matcher.go

fix: selector namespace match

---

cmd/api-server/main.go
cmd/kubectl-testkube/commands/crds/tests_crds.go
pkg/api/v1/testkube/model_test_base_extended.go
pkg/executor/client/job.go
pkg/executor/containerexecutor/containerexecutor.go
pkg/executor/containerexecutor/containerexecutor_test.go
pkg/executor/containerexecutor/tmpl.go
pkg/triggers/service.go
pkg/triggers/service_test.go
pkg/triggers/watcher.go
pkg/utils/utils.go
pkg/utils/utils_test.go

feat: add labels to test and job

---

pkg/repository/result/mongo.go
pkg/repository/result/mongo_test.go

https://github.com/kubeshop/testkube/issues/3463
During a live debug session we've found out that the Output is not the field causing the JMeter issue, but the number of steps is getting too big. This fix trims the array
-
-
-

fix: trim the steps before persisting them

---

contrib/executor/curl/pkg/runner/runner.go

fix: error log typo

---

cmd/kubectl-testkube/commands/common/validator/version.go

fix: removed warning when cant get version

---

config/job-container-template.yml
config/job-scraper-template.yml
config/job-template.yml
pkg/executor/containerexecutor/templates/job.tmpl

fix: use IfNotPresent instead of Always for imagePullPolicy

---

docs/src/theme/CodeBlock/CopyButton/index.js
docs/src/theme/CodeBlock/CopyButton/styles.module.css

docs: add analytics to button clicks

---

api/v1/testkube.yaml
internal/app/api/v1/configs.go
internal/app/api/v1/debug.go
internal/app/api/v1/executions.go
internal/app/api/v1/executor.go
internal/app/api/v1/handlers.go
internal/app/api/v1/labels.go
internal/app/api/v1/repository.go
internal/app/api/v1/testsource.go
internal/app/api/v1/testsuites.go
internal/app/api/v1/testtriggers.go
internal/app/api/v1/uploads.go
internal/app/api/v1/webhook.go
pkg/api/v1/testkube/model_repository.go
pkg/api/v1/testkube/model_repository_update.go

Closes https://github.com/kubeshop/testkube/issues/3398
No changes in logic. Made sure the returned errors are consistent over the different entities: 500 for minio & mongo, 502 for Kubernetes cluster. Added a few 404s from where it was missing
-
-
-

feat: improve errors

---

pkg/executor/containerexecutor/tmpl.go

fix: escape args and command for template

---

docs/docs/concepts/test-suites/testsuites-getting-results.md

Fixed a typo in the `testsuites-getting-results.md` documentation page.
-
-
-

docs: Fixed typo in testsuites-getting-results.md

---

docs/docusaurus.config.js

docs: add cookie consent form

---

pkg/executor/client/job.go
pkg/executor/common.go
pkg/executor/containerexecutor/containerexecutor.go

fix: store pod error in execution result

---

docs/docs/concepts/tests/tests-creating.md

Add an example on default job template.
-
-
-

docs: update doc

---

.github/workflows/executor_docker-build.yaml

add cypress11 suffix as Docker image tag
-
-
-

ci: add cypress11 suffix as a tag Docker image

---

pkg/storage/minio/artifacts_storage.go

fix: minio panic

---

.github/workflows/executor_docker-build.yaml

Add specific cypress tag
-
-
-

ci: add cypress tag

---

docs/docs/concepts/dependencies.md

docs: DocDB docs

---

cmd/kubectl-testkube/commands/common/client.go
cmd/kubectl-testkube/commands/config.go
cmd/kubectl-testkube/commands/config/api_server_name.go
cmd/kubectl-testkube/commands/config/api_server_port.go
cmd/kubectl-testkube/commands/config/dashboard_name.go
cmd/kubectl-testkube/commands/config/dashboard_port.go
cmd/kubectl-testkube/commands/constants.go
cmd/kubectl-testkube/commands/dashboard.go
cmd/kubectl-testkube/commands/tests/common.go
cmd/kubectl-testkube/config/data.go
cmd/kubectl-testkube/config/storage.go
docs/docs/reference/cli/testkube_config.md
docs/docs/reference/cli/testkube_config_api-server-name.md
docs/docs/reference/cli/testkube_config_api-server-port.md
docs/docs/reference/cli/testkube_config_dashboard-name.md
docs/docs/reference/cli/testkube_config_dashboard-port.md
pkg/api/v1/client/api_test.go
pkg/api/v1/client/apiconfig.go
pkg/api/v1/client/factory.go
pkg/api/v1/client/factory_test.go
pkg/telemetry/payload.go

feat: use config for service params

---

docs/docs/overview/testkube-benefits.md
docs/docs/test-types/executor-ginkgo.md

added copy on benefits and ginkgo executor
-
-
-

docs: ginkgo and benefits content

---

cmd/api-server/main.go
internal/config/config.go
pkg/storage/minio/minio.go

Related to https://github.com/kubeshop/testkube/issues/3218
-
-
-

feat: add expiration for artifacts

---

cmd/api-server/main.go
docs/docs/concepts/dependencies.md
internal/config/config.go

https://github.com/kubeshop/testkube/issues/3140
-
-
-

feat: mongo ssl cert secret keys configurable

---

docs/docs/reference/helm-chart.md

Added docs for TK multinamespace feature.
-
-
-

docs: add docs for TK multinamespace

---

docs/docusaurus.config.js

docs: create universal redirects

---

docs/docs/test-types/executor-artillery.mdx
docs/docs/test-types/executor-jmeter.md
docs/docs/test-types/executor-maven.md
docs/docs/test-types/executor-playwright.md

updated artillery, maven, and playwright learn sections
-
-
-

docs: add missing copy to executors

---

cmd/api-server/main.go
config/job-container-template.yml
config/job-scraper-template.yml
config/job-template.yml
internal/config/config.go
pkg/executor/client/job.go
pkg/executor/containerexecutor/containerexecutor.go
pkg/executor/containerexecutor/containerexecutor_test.go
pkg/executor/containerexecutor/templates/job.tmpl
pkg/executor/containerexecutor/tmpl.go

fix: use registry for executors

---

cmd/api-server/main.go
internal/app/api/v1/executor.go
internal/config/config.go
pkg/executor/client/job.go
pkg/executor/common.go
pkg/executor/containerexecutor/containerexecutor.go
pkg/executor/containerexecutor/logs.go
pkg/git/checkout.go

fix: test result timeout parameter

---

pkg/git/checkout.go

fix: print git parameters

---

pkg/api/v1/testkube/model_test_base_extended.go
pkg/executor/client/job.go
pkg/executor/containerexecutor/containerexecutor.go
pkg/executor/containerexecutor/tmpl.go

fix: more labels

---

pkg/executor/scraper/minio_scraper_integration_test.go
pkg/repository/result/mongo.go
pkg/repository/result/mongo_numbers.go

Close https://github.com/kubeshop/testkube/issues/3553
-
-
-

fix: delete execution numbers when test/testsuite is deleted

---

cmd/kubectl-testkube/commands/tests/run.go
cmd/kubectl-testkube/commands/testsuites/run.go
docs/docs/reference/cli/testkube_run_test.md
docs/docs/reference/cli/testkube_run_testsuite.md

feat: add running context option to cli

---

pkg/scheduler/testsuite_scheduler.go
pkg/slack/slack.go

Closes https://github.com/kubeshop/testkube/issues/3706
-
-
-

fix: endtime on notifications

---

pkg/executor/client/job.go
pkg/executor/output/output.go
pkg/executor/output/parser.go

Closes https://github.com/kubeshop/testkube/issues/3285
-
-
-

fix: show output parsing log errors

---

docs/docs/test-types/executor-k6.mdx

added k6 video to executor page
-
-
-

docs: add k6 video

---

api/v1/testkube.yaml
cmd/kubectl-testkube/commands/abort.go
cmd/kubectl-testkube/commands/testsuites/abort.go
docs/docs/reference/cli/testkube_abort.md
docs/docs/reference/cli/testkube_abort_testsuiteexecutions.md
internal/app/api/v1/server.go
internal/app/api/v1/testsuites.go
pkg/api/v1/client/interface.go
pkg/api/v1/client/testsuite.go
pkg/repository/result/filter.go
pkg/slack/slack.go

Related to https://github.com/kubeshop/testkube/issues/2852
-
-
-

feat: add abort all test suite executions

---

test/dashboard-e2e/tests/create-test.spec.ts
test/dashboard-e2e/tests/executors.spec.ts
test/dashboard-e2e/tests/test-settings.spec.ts
test/dashboard-e2e/tests/test-sources.spec.ts
test/dashboard-e2e/tests/tests-dashboard.spec.ts
test/dashboard-e2e/tests/testsuite-settings.spec.ts
test/dashboard-e2e/tests/testsuites-dashboard.spec.ts
test/dashboard-e2e/tests/triggers.spec.ts

Empty scenarios added (.skip) - for test coverage calculation

feat: Dashboard E2E tests - test scenarios added (.skip)

---

docs/docs/guides/slack-integration.md
docs/docs/reference/helm-chart.md

Related to https://github.com/kubeshop/testkube/issues/3630
-
-
-

docs: add explanation how to use helm values to configure slack

---

.github/workflows/docker-build-develop.yaml

Test commit to trigger CI flow
-
-
-

test commit

---

.github/workflows/docker-build-api-executors-tag.yaml

Test PR to trigger flow.
-
-
-

ci: trigger flow

---

.github/workflows/codeql-analysis.yml
.github/workflows/test.yaml

Add tests for develop branch
-
-
-

ci: add tests for develop branch

---

pkg/http/client.go

fix: http timeout

---

.github/workflows/docker-build-api-executors-tag.yaml

ci: fix typo

---

.github/workflows/docker-build-api-executors-tag.yaml

ci: add check for release branch

---

goreleaser_files/.goreleaser-docker-build-api-commit-only.yml
goreleaser_files/.goreleaser-docker-build-api.yml

build:  fix ldflags

---

.github/workflows/docusaurus.yml

feat: add develop branch to docs workflow!

---

contrib/executor/artillery/pkg/runner/artillery.go
contrib/executor/artillery/pkg/runner/artillery_test.go
contrib/executor/curl/pkg/runner/runner.go
contrib/executor/cypress/pkg/runner/cypress.go
contrib/executor/ginkgo/pkg/runner/runner.go
contrib/executor/ginkgo/pkg/runner/runner_integration_test.go
contrib/executor/gradle/pkg/runner/runner_integration_test.go
contrib/executor/jmeter/pkg/runner/runner.go
contrib/executor/kubepug/pkg/runner/runner.go
contrib/executor/kubepug/pkg/runner/runner_test.go
contrib/executor/postman/pkg/runner/newman/newman.go
contrib/executor/postman/pkg/runner/newman/newman_test.go
contrib/executor/soapui/pkg/runner/runner.go
contrib/executor/soapui/pkg/runner/runner_test.go
contrib/executor/template/cmd/agent/main.go
contrib/executor/template/pkg/runner/runner.go
contrib/executor/template/pkg/runner/runner_test.go
pkg/executor/content/fetcher.go
pkg/executor/content/fetcher_test.go

feat: container init data for executors

---

docs/redirects.js

docs: add more redirects

---

docs/docs/articles/creating-tests.md

docs for https://github.com/kubeshop/testkube/issues/3299
-
-
-

docs: variables file changes

---

.github/workflows/docker-build-api-executors-beta-tag.yaml
.github/workflows/docker-build-api-executors-tag.yaml
contrib/executor/cypress/build/agent/Dockerfile.cypress12
goreleaser_files/.goreleaser-docker-build-executor-cypress-commit-only.yml
test/executors/cypress.yaml

Add support of cypress12. It will be built with the latest image tag now.
-
-
-

feat: add cypress12

---

docs/docs/test-types/executor-jmeter.md

As multiple users have bumped into this issue, it is worth adding a section about it into our docs
-
-
-

docs: JMeter memory consumption

---

.github/workflows/docker-build-develop.yaml
.github/workflows/docker-build-release.yaml

exclude docs folder not to build on every commit.
-
-
-

ci: exclude building docs on every commit

---

pkg/telemetry/telemetry.go

feat: detect more kubernetes distributions

---

docs/docusaurus.config.js

docs: enable doc search from /search page

---

.github/workflows/test.yaml

chore: do not run test pipeline on docs

---

docs/redirects.js

docs: redirects

---

test/dashboard-e2e/pages/TestExecutionsPage.ts

fix: Dashboard E2E tests - selector fixed

---

test/scripts/executor-tests/run.sh

Test run script - overwrite branch from the CRDs with the target one

feat: Test run script - branch overwrite

---

internal/app/api/v1/tests.go

… on update test
user issue from discord
-
-
-

fix: update test metrics nil exception

---

.github/workflows/docker-build-api-executors-tag.yaml
.github/workflows/docker-build-release.yaml

Renaming release branch.
-
-
-

ci: rename release branch

---

.github/workflows/docker-build-api-executors-tag.yaml
.github/workflows/docker-build-release.yaml

Update release branch name.
-
-
-

ci: update release branch name

---

test/container-executor/executor-smoke/crd/cypress.yaml
test/executors/container-executor-cypress.yaml

Second example for: https://github.com/kubeshop/testkube/issues/3723

feat: Custom container executor for Cypress - tests - artifacts

---

docs/docs/articles/step3-creating-first-test.md

There is a type on the docs. 
-
-
-

fix: typo on the docs for Creating Your First Test

---

docs/docs/test-types/executor-tracetest.md
docs/sidebars.js

added tracetest executor docs and embed video
-
-
-

docs: add tracetest executor

---

docs/docs/articles/metrics.md
docs/docs/articles/telemetry.md

refine metrics doc, relates to https://github.com/kubeshop/helm-charts/pull/515#issuecomment-1558956397
Refine services to which telemetry are sent
-
-
-

docs: telemetry and metrics refinements

---

contrib/executor/playwright/pkg/runner/playwright_test.go
pkg/http/client.go
pkg/oauth/oauth.go

fix: support http proxy

---

contrib/executor/zap/examples/zap-executor.yaml
contrib/executor/zap/pkg/runner/zap.go
docs/docs/test-types/executor-zap.md

docs: add zap executor

---

.github/workflows/docker-build-api-executors-tag.yaml
.github/workflows/docker-build-develop.yaml

Add GH action for uploading README file to API server Docker registry and executors.
-
-
-

ci: add docker registry description

---

docs/docs/articles/supported-tests.mdx
docs/sidebars.js
docs/src/theme/DocCard/index.js

docs: zap references

---

contrib/executor/postman/pkg/runner/newman/envfile.go

fix: postman plain secret

---

contrib/executor/artillery/pkg/runner/artillery.go
contrib/executor/cypress/pkg/runner/cypress.go
contrib/executor/ginkgo/pkg/runner/runner.go
contrib/executor/gradle/pkg/runner/runner.go
contrib/executor/jmeter/pkg/runner/runner.go
contrib/executor/k6/pkg/runner/runner.go
contrib/executor/kubepug/pkg/runner/runner.go
contrib/executor/maven/pkg/runner/runner.go
contrib/executor/playwright/pkg/runner/playwright.go
contrib/executor/postman/pkg/runner/newman/newman.go
contrib/executor/soapui/pkg/runner/runner.go
contrib/executor/zap/pkg/runner/runner.go
pkg/executor/content/fetcher.go
pkg/executor/process.go

fix: support multiline commands

---

docs/docs/articles/exposing-testkube-with-ingress-nginx.md

Updated docs for Ingress configuration.
-
-
-

docs: update Ingress set-up
