kubeshop/testkube

cmd/kubectl-kubtest/commands/scripts/listrenderer.go, pkg/api/v1/client/direct.go, pkg/api/v1/client/interface.go, pkg/api/v1/client/proxy.go, pkg/api/v1/kubtest/model_executions_result_extended.go
Fix after last refactor kubectl plugin was using invalid (old) data structures - API was updated 
-
-
-
=> fixed executions summary

Makefile, cmd/kubectl-testkube/commands/scripts/start_script.go, cmd/tools/commands/versions.go, go.mod, go.sum, internal/app/api/v1/scripts.go, internal/app/api/v1/server.go, pkg/api/v1/client/common.go, pkg/api/v1/client/direct.go, pkg/api/v1/client/interface.go, pkg/api/v1/client/proxy.go, pkg/executor/client/job.go, pkg/jobs/jobclient.go, pkg/log/log.go, pkg/runner/output/output.go, pkg/storage/minio/minio.go, pkg/ui/printers.go
SSE (Server Sent Events) endpoint for API 
No OpenAPI spec yet as of : https://github.com/OAI/OpenAPI-Specification/issues/396  https://github.com/wechaty/openapi/issues/20 
Works for now on direct API client (from local machine) proxied need to be implemented 
-
-
-
=> sse in api - logs piped from pod

go.mod, go.sum, pkg/storage/minio/minio.go
Strips the filename if the path is longer than 3 subdirectories /dir/sub1/sub2/ -> /sub1/sub2
- [ x] tested locally
- [ x] tested on cluster
-
-
=> fix: stripping root dir from filename before storing it inminio's bucket

cmd/kubectl-testkube/commands/artifacts.go, cmd/kubectl-testkube/commands/install.go, cmd/kubectl-testkube/commands/root.go, cmd/kubectl-testkube/commands/scripts/common.go, cmd/kubectl-testkube/commands/scripts/start_script.go, internal/app/api/v1/scripts.go, pkg/api/v1/client/common.go, pkg/api/v1/client/direct.go, pkg/api/v1/client/proxy.go, pkg/executor/client/job.go, pkg/jobs/jobclient.go
- added download all artifacts by default download is now download-one
- fix for Cypress logs on GKE 
- simplified passing/closing channel to logs stream
- simplified reading streams
- kubectl plugin UI fixes
- closes #533 
- closes #560 
-
-
-
=> fix: Cypress executor logs broken

docs/getting-started.md, test/e2e/Kubeshop.postman_collection.json
=> fix: getting started fixed with valid test

docs/installing.md
=> fix(installing.md): fix typo in MacOS and minor formatting fixes.

cmd/kubectl-testkube/commands/install.go, docs/installing.md
Updated installation command with minio and dasboard options
Dashboard is installed by default now.
colses #536
-
-
-
=> feat: added dashboard install option as default to install command

internal/app/api/v1/server.go
Dashboard needs to access scripts endpoint from the api-server.
-
-
-
=> feat(/scripts): add cors settings

cmd/kubectl-testkube/commands/scripts.go, cmd/kubectl-testkube/commands/scripts/crd_script.go, pkg/ui/printers.go
=> feat: Create CRDs based on scripts directory

.github/workflows/release-dev.yaml, .goreleaser-dev.yml
=> feat: added dev build

build/api-server/Dockerfile
Remove libssl upgrade for latest alpine Docker image, because it alreday contains libssl1.1
It fixes issue #699
Proof:
```
docker run -it --rm alpine:latest ash
/ # apk --no-cache add ca-certificates libssl1.1
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r7)
Executing busybox-1.34.1-r3.trigger
Executing ca-certificates-20191127-r7.trigger
OK: 6 MiB in 15 packages
/ # cd /lib
/lib # ls
apk                    libapk.so.3.12.0       libssl.so.1.1          mdev
firmware               libc.musl-x86_64.so.1  libz.so.1              modules-load.d
ld-musl-x86_64.so.1    libcrypto.so.1.1       libz.so.1.2.11         sysctl.d
/lib # strings …
```
=> fix: remove docker libssl upgrade

internal/app/api/v1/executions.go, pkg/api/v1/client/direct.go, pkg/api/v1/client/proxy.go
We use url parameter escaping when we prepate url for http request. But net http client automatically escapes url parameter
Closes #740 
-
-
- Update comments for golint
- Remove double escaping/unescaping for url parameters
-
=> fix: remove api double parameter unescaping

internal/app/api/v1/executions.go
Reuse existing output method for printing errors
Closes #704 
-
-
Update method to print error output
=> refactor: reuse existing output method for printing errors

api/v1/testkube.yaml, cmd/kubectl-testkube/commands/scripts/execution_renderer.go, cmd/kubectl-testkube/commands/tests/common.go, cmd/kubectl-testkube/commands/tests/execution.go, cmd/kubectl-testkube/commands/tests/start.go, cmd/kubectl-testkube/commands/tests/watch.go, docs/installing.md, internal/app/api/v1/executions.go, internal/app/api/v1/tests.go, internal/pkg/api/repository/result/interface.go, internal/pkg/api/repository/result/mongo.go, internal/pkg/api/repository/testresult/interface.go, internal/pkg/api/repository/testresult/mongo.go, pkg/api/v1/testkube/model_execution.go, pkg/api/v1/testkube/model_execution_extended.go, pkg/api/v1/testkube/model_execution_result_extended.go, pkg/api/v1/testkube/model_test_execution.go, pkg/api/v1/testkube/model_test_execution_extended.go, pkg/api/v1/testkube/model_test_execution_summary.go, pkg/jobs/jobclient.go, pkg/rand/common.go, pkg/rand/names.go, pkg/rand/string.go, pkg/server/httpserver.go
As api client I want to have duration calculated on backend.
closes #781 
closes #784
closes #785
-
-
-
=> feat: duration for testexecutions and for executions + small fixes

internal/app/api/v1/executions.go, pkg/api/v1/client/direct.go, pkg/api/v1/client/proxy.go
This reverts commit f744accc246450d7eea4f660ab1ae36a3be65953.
-
-
-
=> fix: Revert "fix: remove api double parameter unescaping (#740)"

internal/app/api/v1/tests.go
Mark test as failed if one of the steps fails and record step if it stops on fialure
Closed #867, #866
-
-
- Refactor step execution loop to break on failure and mark test as failed for any failed steps
=> fix: mark test failed if one of the steps fails and record step if it stops on failure

internal/app/api/v1/scripts.go
=> feat: added scripts filtering by type

api/v1/testkube.yaml, internal/app/api/v1/server.go, internal/pkg/api/repository/result/filter.go, internal/pkg/api/repository/result/interface.go, internal/pkg/api/repository/result/mongo.go
=> feat: executions list filtered by type

internal/app/api/v1/server.go
=> fix: scriptName in filters

pkg/analytics/analytics.go
=> fix: check if the os.Args have more than one element before cutting down the first element

docs/executor-custom.md
When creating a new executor, the docs suggested to use contentTypes, despite all other params using snake case. This PR fixes that.
- none
- just the docs
- just the docs
=> docs: update parameter casing in docs

.github/workflows/release-dev.yaml, .github/workflows/release.yaml, .github/workflows/test.yml, build/api-server/Dockerfile, cmd/debug-server/Dockerfile, go.mod, go.sum
This reverts commit 8bffcfbe67d6d98905ff46b016afe23452baceb3.
Fix: revert upgrade go to 1.18
-
-
-
=> fix: revert upgrade go to 1.18

docs/executor-custom.md
When adding the Testkube cli command to the custom executor docs, some information was lost. This PR aims to fix that.
-
-
-
=> docs: added executor crd yaml back

.github/workflows/lint.yaml, pkg/executor/scraper/scraper.go, pkg/executor/scrapper/scrapper.go
In https://github.com/kubeshop/testkube-executor-soapui/pull/4 it came up that this struct should belong here. This PR adds it.
-
-
-
=> refactor: move interface from the executor to the testkube repo

.builds-darwin.goreleaser-dev.yml, .builds-linux.goreleaser-dev.yml, .builds-windows.goreleaser-dev.yml, .goreleaser-dev.yml
- speed up children builds by skipping archiving
- fixed paths
=> fix: goreleaser prebuilt config

docs/installing.md
Apparently, the >> is run by the shell and sudo didn't apply to it.
-
-
-
=> docs: updating the apt install command in the docs as sudo was in the wrong place

internal/app/api/v1/server.go, pkg/executor/client/job.go, pkg/jobs/jobclient.go
Test execution counter is not increased after execution finishes, i.e. the result is stuck at `running` even after the execution succeeded or failed. This change fixes that.
```
testkube_executions_count{name="xyz",result="running",type="universal-package-test"} 1
```
-
-
-
=> fix: Increase counter after an execution

cmd/kubectl-testkube/commands/dashboard.go
Use dll to open windows browser
-
-
-
=> fix: use dll to open windows browser

pkg/jobs/jobclient.go
* Issue is that the status of a test run continues to hold the original status of "running" because execution object never gets pass/fail status assigned before incrementing metrics on it.
* So, this change will fix that issue by updating execution object to have up to date result status before incrementing metrics on it.
* The result is that instead of metrics being stuck as "running" regardless of whether the corresponding test passed or failed as shown below:
`testkube_executions_count{name="kubeshop-site",result="running",type="postman/collection"} `
now we have the following when the corresponding test fails:
`testkube_executions_count{name="kubeshop-site",result="failed",type="postman/collection"}`
and the following when the corresponding test passes: …
=> fix: Update execution object to have up to date result status before incrementing metrics on it

cmd/kubectl-testkube/commands/crds/tests_crds.go, cmd/kubectl-testkube/commands/executors/create.go, cmd/kubectl-testkube/commands/tests/common.go, cmd/kubectl-testkube/commands/tests/run.go, cmd/kubectl-testkube/commands/testsuites/create.go, cmd/kubectl-testkube/commands/testsuites/update.go, cmd/kubectl-testkube/config/config_test.go, cmd/kubectl-testkube/config/storage.go, cmd/proxy/main.go, internal/app/api/v1/slack_oauth.go, pkg/analytics/analytics.go, pkg/api/v1/client/direct_client.go, pkg/executor/agent/agent.go, pkg/executor/content/fetcher.go, pkg/executor/content/fetcher_test.go, pkg/git/checkout.go, pkg/helm/chart.go, pkg/oauth/github.go, pkg/tmp/files.go, pkg/tmp/files_test.go, pkg/webhook/emitter.go
Signed-off-by: Fahed DORGAA <fahed.dorgaa@gmail.com>
Deprecation of `io/ioutil` (https://go.dev/doc/go1.16#:~:text=FS%20implementations.-,Deprecation%20of%20io%2Fioutil,been%20moved%20to%20other%20packages.)
- N/A
- switch to `os` and  `io` package
- switch to `os` and  `io` package
=> feat: remove io/ioutil pkg

pkg/executor/client/job.go, pkg/jobs/jobclient.go
Move log closing channel back to goroutine (kubectl-testkube was waiting forever for channel closing)
-
-
-
=> fix: move log closing channel back to goroutine

internal/app/api/v1/executions.go, internal/app/api/v1/executor.go, internal/app/api/v1/tests.go, internal/app/api/v1/testsuites.go, internal/app/api/v1/webhook.go, test/postman/Testkube-API.postman_collection.json
=> fix: use net/http statuses

api/v1/testkube.yaml, pkg/api/v1/testkube/model_execution_request.go
While working on issue #1647 it came up that some of the already implemented properties from the Go code do not appear in the Swagger definition.
This commit makes sure that the newly generated models using `make openapi-generate-model` will not break old functionality.
-
- updated swagger yaml to match go code
-
=> fix: update Testkube Swagger definition

docs/tests-getting-results.md
a is placed at the correct position according to the issue
=> fix: `a` is placed at correct position

docs/installing.md
`PortNmae` is changed into `PortName` and also `Upack` is corrected to `Unpack`
=> fix: `PortNmae` is changed into `PortName` 

.github/workflows/release.yaml
Changed GH action to a new `bump formula` step.
The PR in homebrew repo was created for a new version.
-
-
-
=> fix: replace homebrew formulae

internal/app/api/v1/executions.go, pkg/api/v1/client/api.go, pkg/api/v1/client/direct_client.go, pkg/api/v1/client/factory.go, pkg/event/kind/slack/loader.go, pkg/executor/client/job.go, pkg/http/client.go, pkg/http/client_test.go
Looks like during the rewrite  of our clients we've started using a configured client with valid timeouts, it's good for most endpoints, but not for SSE like ;) 
I've introduced an additional client who is able to wait for the SSE stream. 
-
-
-
=> fix: test transport with SSE client

.github/workflows/manual-bump-formula.yaml
This PR adds a workflow that can be run manually, passing a needed tag release number as an input, to bump `homebrew` formula. If a tag is not passed, then the latest one will be used. 
There is also a cron expression that is scheduled to run once a week. 
The caveat: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/
**Downgrade of versions cannot be done!**
I have tested this on my own repo for now, however, in a few days we can release to `homebrew-core`. 
-
-
-
=> ci: add manual flow to trigger formula bump

api/v1/testkube.yaml, cmd/kubectl-testkube/commands/tests/common.go, cmd/kubectl-testkube/commands/tests/common_test.go, pkg/api/v1/client/interface.go, pkg/api/v1/testkube/model_execution.go, pkg/api/v1/testkube/model_execution_request.go, pkg/scheduler/test_scheduler_test.go
This PR fixes the
```
Structural error at components.schemas.ExecutionRequest.properties.copyFiles.additionalProperties.items.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
```
swagger error
-
-
-
=> fix: byte is unrecognized

test/cypress/executor-smoke/crd/crd.yaml, test/postman/executor-smoke/crd/crd.yaml, test/suites/executor-postman-smoke-tests.json
Blocked by: https://github.com/kubeshop/testkube/issues/2560 - don't merge before it
=> feat: [DON'T MERGE before #2560 fix] executor tests - TestSources - overwrite tests

api/v1/testkube.yaml, pkg/api/v1/testkube/model_test_trigger_upsert_request.go
Swagger was complaining about duplicated IDs, this `patch` entry is the same as the one above it. This change does not affect the generated code.
-
-
-
=> fix: duplicated patch in openapi yaml

test/dashboard-e2e/cypress.config.js
Video recording disabled for Dashboard E2E tests because of this issue: https://github.com/kubeshop/testkube/issues/1540#issuecomment-1304850859
=> fix: Dashboard E2E tests - Cypress video recording disabled

pkg/executor/containerexecutor/containerexecutor.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/executor/containerexecutor/templates/job.tmpl
Pass workingDir to container executor as stated in #2683 
When workingDir is containing a relative path it is added on top of container executor repository path (/data/repo) and when the path is absolute it is used as it is.
-
-
-
=> feat: Pass workingDir to container executor

pkg/storage/minio/minio.go
There should be logs in the init container when a file was placed so that the user has better visibility.
-
-
-
=> fix: make file placement logs visible

test/cypress/executor-tests/crd/crd.yaml, test/suites/demo-testsuite.json, test/suites/staging-testsuite.json
- Cypress tests - default switched to Cypress 11
- Staging and Demo testsuites updated (testsuites updated with Cypress tests, Dashboard E2E tests temporary removed because of stability problems)
=> feat: Cypress tests - default switched to Cypress 11, Staging and Demo testsuites updated

cmd/api-server/main.go
mongo ssl cert environment variable name was out of date with the docs, this pr fixes that
-
-
-
=> fix: use right environment variable name

cmd/kubectl-testkube/commands/common.go
Fixes https://github.com/kubeshop/testkube/issues/3036 and addresses comments on https://github.com/kubeshop/testkube/issues/2906
-
-
-
=> fix: set logs storage to mongo when minio is not enabled

pkg/executor/client/job.go, pkg/executor/output/parser.go, pkg/executor/output/parser_test.go
Relates to https://github.com/kubeshop/testkube/issues/3023
When getting the result of an execution, Testkube checks the last log line to see if it was either an error or a log of type Result. The purpose of this PR is to check for the last log line by timestamp.
-
-
-
=> fix: invalid statuses on unordered logs

pkg/api/v1/testkube/model_execution_result_extended.go, pkg/executor/client/job.go, pkg/executor/output/parser.go, pkg/executor/output/parser_test.go
Made logs parsing clearer, fixed issue on logs with no timestamp, issue on executions seemingly running forever and added the logs to the output to have a more consistent behaviour.
-
-
-
=> fix: refactor execution logs parsing

README.md
Updated user handle link from @andrei-n-cosma to @ancosma
In the ``` Contributing ``` section [@andrei-n-cosma](https://github.com/andrei-n-cosma) is showing error after opening. User's new userId is [@ancosma](https://github.com/ancosma).
=> docs: Updated README file

docs/docs/8-authentication/oauth-ui.md
Really small fixes in the docs, but currently copying the command returns the following with `zsh`:
```
Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: =, *
```
Fix the syntax so the command can be copied and applied straight away.
Second fix, add the missing backslash at the end of the second `set`.
Also fix the wrong quotes, which throws the error: 
```
Error: INSTALLATION FAILED: YAML parse error on testkube/charts/testkube-dashboard/templates/ingress.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string 
```
=> docs: Fix syntax of the api server's ingress annotations

docs/docs/7-integrations/webhooks.md
adding specific webhooks docs to integrations since it's currently only referenced in the contributing section and not showing up on search results
-
-
-
=> docs: add separate webhooks section

test/postman/TestKube-Sanity.postman_collection.json
Fix for random failures caused by `Most recent execution is that one recently run` test: https://github.com/kubeshop/helm-charts/actions/runs/4163212709/jobs/7203392780
Multiple tests may be executed at the same time, so `postman-test-` may not be the last one:
```
results: [
│     {
│       id: '63ea285d6191ca1b38acdb4b',
│       name: 'executor-container-smoke-tests-container-
│ executor-curl-smoke-1047',
│       number: 1047,
│       testName: 'container-executor-curl-smoke',
│       testType: 'container-executor-curl/test',
│       status: 'running',
│       startTime: '2023-02-13T12:09:01.316Z',
│       endTime: '0001-01-01T00:00:00Z',
│       labels: { 'core-tests': 'executors' }
│     },
│     {
│       id: '63ea28576191ca1b38acdb47',
│       name: 'postman-test-k1lm3i-1',
│ …
```
=> fix: postman sanity - recent executions list fixed

docs/docs/using-testkube/triggers.md
Amend the resource type in the example to `deployment` so it aligns with the conditions.
-
-
-
=> docs: amend resource type in example to deployment

pkg/executor/content/fetcher.go, pkg/executor/content/fetcher_test.go, pkg/executor/content/interface.go, pkg/scheduler/test_scheduler.go
During investigation on https://github.com/kubeshop/testkube/issues/3198, I saw that we do not have the option to specify the git type (git-file or git-dir) when we are using test sources via the UI.
This PR addresses that by adding a function to decide on the go what the type of the input is. Unfortunately it is not possible to get the type of a path without cloning the repo, so this means the repo will be cloned twice on execution: once in the api-server to check the type on the go, and once in the init-container. This has the upside that in case the type changes between the creation of the test and the execution, Testkube will be aware of it.
-
-
-
=> fix: check git source when repo type is `git`

test/cypress/executor-tests/cypress-10/cypress/e2e/dummy_test.cy.js, test/cypress/executor-tests/cypress-11/cypress/e2e/smoke.cy.js
=> fix: ENV/param checks reanabled for Cypress tests

docs/docusaurus.config.js, docs/static/CNAME
Algolia search needs to work with the new domain, and we're stuck until the Algolia team updates the domain, which is unpredictable blocker. 
Returning to old link for now until we get new Algolia domain, 
-
-
-
=> docs: remove domain CNAME

cmd/kubectl-testkube/commands/common.go, cmd/kubectl-testkube/commands/common/client.go, cmd/kubectl-testkube/commands/context/set.go, cmd/kubectl-testkube/commands/context/ui.go, cmd/kubectl-testkube/commands/init.go, cmd/kubectl-testkube/commands/upgrade.go, pkg/api/v1/client/factory.go, pkg/ui/ui.go
Agent config is in upgrade context only
-
-
-
=> fix: cloud cli set api uri correctly, removed explicit agent config from context

internal/app/api/v1/server.go
Complaint coming from user on Discord that uploading a file of size 250MB, the api server is returning: 413
-
-
-
=> fix: update default body size limit for http client

cmd/kubectl-testkube/commands/set.go, pkg/api/v1/client/proxy_client.go
As during set clients are not configured yet - so we can't use them. 
Related to issue with `set context`. 
-
-
-
=> fix: remove version check from set command

docs/docs/test-types/executor-ginkgo.md, docs/docs/test-types/executor-jmeter.md, docs/docs/test-types/executor-k6.mdx, docs/docs/test-types/executor-playwright.md, docs/docs/test-types/executor-postman.mdx, docs/docs/test-types/executor-soapui.md, docs/src/css/custom.css
added info sections with blog copy to executor pages: playwright, soapui, k6, postman, ginkgo
-
-
-
=> docs: add info sections to executors

docs/docs/test-types/executor-playwright.md
It is not mandatory to block the browser's opening at the end of the execution of the tests
-
-
-
=> docs: update executor playwright report setting

test/artillery/executor-smoke/crd/crd.yaml, test/container-executor/executor-smoke/crd/playwright.yaml, test/curl/executor-tests/crd/smoke.yaml, test/cypress/executor-tests/crd/crd.yaml, test/gradle/executor-smoke/crd/crd.yaml, test/jmeter/executor-tests/crd/smoke.yaml, test/k6/executor-tests/crd/other.yaml, test/k6/executor-tests/crd/smoke.yaml, test/kubepug/executor-smoke/crd/crd.yaml, test/maven/executor-smoke/crd/crd.yaml, test/maven/executor-smoke/crd/negative.yaml, test/playwright/executor-tests/crd/crd.yaml, test/postman/executor-tests/crd/crd.yaml, test/soapui/executor-smoke/crd/crd.yaml, test/suites/demo-testsuite.json, test/suites/executor-cypress-smoke-tests.json, test/suites/executor-k6-other-tests.json, test/suites/executor-k6-smoke-tests.json, test/suites/executor-postman-smoke-tests.json, test/suites/staging-testsuite.json
Tests updated to `git` source, additional tests added for backwards compatibility checks (postman, k6, and cypress):
- git-file
- git-dir
- TestSource (git-file)
- TestSource (git-dir)
**Merge after #3063**
=> feat: Executor tests updated after merging git-dir and git-file sources to single `git` source

pkg/cloud/data/artifact/scraper_integration_test.go, pkg/executor/agent/agent.go, pkg/executor/scraper/extractor_integration_test.go, pkg/executor/scraper/factory/factory.go, pkg/executor/scraper/filesystem_extractor.go, pkg/executor/scraper/minio_scraper_integration_test.go, pkg/executor/scraper/minio_uploader.go, pkg/executor/scraper/scraper.go
* Updates to Scraper so it has a blueprint Scrape method which all Executors will call, and that will hide any cloud related stuff from Runners.
* Fix and integration test for a special case for filepath.Rel in Filesystem Extractor
* Support for -f|--file in Executor Agent so Executors can easily be run locally 
-
-
-
=> feat: scraper updates and scraper template pattern function

pkg/repository/result/mongo.go, pkg/repository/result/mongo_test.go
https://github.com/kubeshop/testkube/issues/3463
Test result processing stopped when mongodb limit was reached. This fix ensures this will not block it.
-
-
-
=> fix: output too long for mongo

contrib/executor/k6/build/agent/Dockerfile
Updates K6 to 0.43.1.  Also uses the version env-var to the pin the version in a more predictable way.
I built locally and checked the version in the container, looking correct
```
~ $ k6 version
k6 v0.43.1 ((devel), go1.18.10, linux/arm64)
Extensions:
github.com/grafana/xk6-output-prometheus-remote v0.2.0, xk6-prometheus-rw [output]
```
- Updated K6 Version
=> chore: Update K6 Executor to 0.43.1

internal/app/api/v1/graphql.go, pkg/server/httpserver.go
* Close the GraphQL server gracefully when the app should be terminated
* Don't wait 2 seconds for closing the API servers, instead separate the listener and serve to avoid problems
-
-
- https://github.com/kubeshop/testkube/issues/3636
=> fix: Close API server gracefully when signal appeared

cmd/api-server/main.go, internal/app/api/v1/graphql.go, internal/app/api/v1/server.go, internal/graphql/graph/schema.resolvers.go, internal/graphql/server.go
* Change Upgrader config, to support WebSocket connection from different origin
* Unsubscribe from Event Bus, when the GraphQL subscription is disconnected
* Emit the initial state of executors in the beginning
* Expose `/graphql` endpoint in the API
There are multiple improvements that could be done later, i.e.:
* Use Unix sockets for internal connection with the GraphQL server
* Prepare a common handler for transitioning events from EventBus into GraphQL subscriptions
-
-
- https://github.com/kubeshop/testkube/issues/3646
=> fix: Adjust GraphQL server initially

test/cypress/executor-tests/crd/crd.yaml, test/cypress/executor-tests/cypress-10/cypress.config.js, test/cypress/executor-tests/cypress-11/cypress.config.js, test/cypress/executor-tests/cypress-12/cypress.config.js, test/cypress/executor-tests/cypress-8/cypress.json, test/cypress/executor-tests/cypress-9/cypress.json, test/suites/executor-cypress-smoke-tests.json
`video: disabled` moved from cypress project configs to args - can't be overwritten directly
=> feat: Cypress executor tests - additional test with video recording enabled

test/dashboard-e2e/pages/MainPage.ts
Filter tests list before opening execution details
=> fix: Dashboard E2E tests - filter tests list

contrib/executor/k6/build/agent/Dockerfile
Upgraded the K6 executor to v0.44.0
https://github.com/grafana/k6/releases/tag/v0.44.0
> k6 v0.44.0 is here! 🎉 This release includes:
> 
> A new k6/experimental/webcrypto module implementing (partially) the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) specification.
> A sampling option for the experimental tracing module.
> Memory usage improvements.
> Bug fixes and UX improvements.
> Some highlights from the k6/experimental/browser module are:
> 
> locator.click is now asynchronous, which is a breaking change.
> browserContext.addCookies has now been implemented.
> browserType.Connect has been implemented so k6 can now connect to an already running Chrome/Chromium browser instance.
> Web vitals are natively supported when working with the browser …
=> chore: Upgrade K6 executor to v0.44.0

contrib/executor/init/build/agent/Dockerfile
This pull request changes the Init Executor to use Ubuntu as the base image instead of Alpine. The reason for this PR is because myself and other users have seen DNS resolution problems when cloning git repositories. I noticed this issue myself in our cluster with the below configuration:
TestKube Version - **testkube-1.11.156**
Kubernetes Cluster Type - **Kubernetes on AWS instances** (not managed EKS)
Kubernetes Client version: **v1.22.16**
Kubernetes Server version: **v1.21.9**
We also have **CoreDNS** and **Istio** enabled on this. From looking online it seems that Alpine can have DNS resolution problems when running in Kubernetes, see: [Does Alpine Have Known DNS issues within Kubernetes](https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes) …
=> fix: Changing Init Executor image to use Ubuntu instead of Alpine

cmd/kubectl-testkube/commands/common.go, go.mod
Add spinner animation while installing the helm charts by using `testkube init` command
- [✅] tested locally
- [✅] tested on cluster
- [✅] added new dependencies
- #3752
=> feat: add spinner to testkube init

docs/docs/articles/testkube-dashboard-api-endpoint.md, docs/docs/articles/testkube-dashboard.md, docs/sidebars.js
=> docs: create a Testkube Dashboard category in  docs

.github/workflows/test.yaml, cmd/api-server/main.go, contrib/executor/playwright/examples/package.json, contrib/executor/playwright/pkg/runner/playwright_test.go, docs/docs/articles/helm-chart.md, internal/app/api/v1/server.go, internal/config/config.go, pkg/api/v1/testkube/model_artifact_request.go, pkg/api/v1/testkube/model_artifact_update_request.go, pkg/cloud/data/artifact/scraper_integration_test.go, pkg/envs/variables.go, pkg/event/kind/cdevent/listener.go, pkg/event/kind/cdevent/listener_test.go, pkg/event/kind/cdevent/loader.go, pkg/event/kind/cdevent/loader_test.go, pkg/executor/common.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/executor/output/parser_test.go, pkg/executor/scraper/factory/factory.go, pkg/executor/scraper/minio_scraper_integration_test.go, pkg/executor/scraper/scraper.go, pkg/mapper/cdevents/mapper.go, pkg/mapper/cdevents/mapper_test.go
=> feat: dashboard uri for cd event

contrib/executor/init/pkg/runner/runner.go, contrib/executor/scraper/pkg/runner/runner.go, docs/docs/test-types/container-executor.mdx, pkg/executor/client/job.go, pkg/executor/common.go, pkg/executor/containerexecutor/containerexecutor.go, pkg/scheduler/test_scheduler.go
=> feat: default artifacts dir

README.md
The original link pointed to a Github page which doesn't exists.
-
-
-
=> fix: link of Docs at README.md

test/dashboard-e2e/crd/crd.yaml
=> fix: e2e tests - crd - separate DASHBOARD_API_URL

docs/docs/articles/operator-api-reference.md, docs/sidebars.js
Generated using  crd-ref-docs on the [Testkube Operator repo](https://github.com/kubeshop/testkube-operator).  
```
crd-ref-docs --source-path=apis --renderer markdown --max-depth 10
```
This will need to be automated @ypoplavs 
Solves #3537 #3444 
-
-
-
=> docs: add operator api reference

api/v1/testkube.yaml
=> fix: docs pre-run script not supported in container executor

cmd/kubectl-testkube/commands/abort.go, cmd/kubectl-testkube/commands/agent.go, cmd/kubectl-testkube/commands/cloud/login.go, cmd/kubectl-testkube/commands/common/client.go, cmd/kubectl-testkube/commands/common/cloudcontext.go, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/common/validator/cloudcontext.go, cmd/kubectl-testkube/commands/context/set.go, cmd/kubectl-testkube/commands/create.go, cmd/kubectl-testkube/commands/debug.go, cmd/kubectl-testkube/commands/delete.go, cmd/kubectl-testkube/commands/download.go, cmd/kubectl-testkube/commands/get.go, cmd/kubectl-testkube/commands/root.go, cmd/kubectl-testkube/commands/run.go, cmd/kubectl-testkube/commands/update.go, cmd/kubectl-testkube/commands/version.go, cmd/kubectl-testkube/commands/watch.go, cmd/kubectl-testkube/config/data.go, pkg/cloud/client/rest.go, pkg/telemetry/telemetry.go
=> feat: validate cloud context on root cmd

docs/docs/articles/testkube-cli-docker.md, docs/sidebars.js
Testkube CLI dockerized docs
-
-
-
=> docs: Testkube CLI docker

api/v1/testkube.yaml, cmd/api-server/main.go, docs/docs/articles/helm-chart.md, internal/config/config.go, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/events.go, pkg/agent/events_test.go, pkg/agent/logs_test.go, pkg/api/v1/testkube/model_event.go, pkg/event/emitter.go, pkg/event/emitter_integration_test.go, pkg/event/emitter_test.go, pkg/event/kind/slack/loader.go, pkg/event/kind/slack/loader_test.go, pkg/slack/slack.go, pkg/triggers/executor_test.go, pkg/triggers/service_test.go
=> feat: cluster name for events

docs/docs/articles/exposing-testkube-with-ingress-nginx.md
I ran into an issue trying to deploy the sample, and found that testkube-dashboard.ingress had some indentation problems. Fixed those and also tried to fix the tls ones (though I didn't try them in my scenario).
- [ x] tested on cluster
- [ x] updated the docs
-
Docs updates to fix indentations around ingress
-
-
=> docs: fixing indentation around testkube ingress sample

pkg/envs/variables.go, pkg/executor/scraper/factory/factory.go, pkg/scheduler/test_scheduler_test.go
=> fix: add timeout to grpc conn

internal/app/api/v1/testtriggers.go, internal/app/api/v1/webhook.go
Creating triggers and webhooks via yaml was throwing error
-
-
-
=> fix:  wrong struct used to marshal body into release

internal/app/api/v1/testtriggers.go, internal/app/api/v1/webhook.go
Creating triggers and webhooks via yaml was throwing error
-
-
-
=> fix: wrong struct used to marshal body into

docs/docs/articles/creating-tests.md
small fix for the example scripts
-
-
-
=> docs: add hashtag to example script

docs/docs/test-types/container-executor.mdx, test/executors/container-executor-playwright.yaml
Use proper Playwright version in executor. When not set and not detected, `npx` tries to install the latest one.
=> fix: use proper Playwright version in its executors

.github/workflows/release-dev.yaml, .github/workflows/release.yaml
Jobs do not fail when the curl command gets a 4xx or 5xx response. This PR fixes that
-
-
-
=> ci: fail job on unsuccessful push to apt

install.sh
related: #4071, fixes #4229
```
❯ sudo bash ./install.sh
```
- fix: switch shebang to reflect existing code and move to the top
- chore: declare and assign separately to avoid masking return values.
- refactor: split to multiline so it simpler to read and maintain
- fix(install): correct typo in parameter expansion for default value
- fix: add a `tag` variable as download URL require `tag` and `version` (which differ)
=> fix: install script

cmd/kubectl-testkube/commands/crds/tests_crds.go, cmd/kubectl-testkube/commands/root.go
=> fix: remove special chars for yaml

docs/docs/articles/step3-creating-first-test.md
Fixing the following issues with the current step 3 of getting started:
- Remove the Testkube dashboard command which is not needed anymore on cloud.
- Change the Postman example to a K6 one to better highlight the value and for the users to get started faster.
- Change the examples of how users can run tests. 
-
-
-
=> Update Step 3 of creating Tests

docs/docs/articles/step3-creating-first-test.md
* Docs are not building, because `<img>` tags should be self-closed in the context of Docusaurus MD(X) files.
-
-
-
=> fix: make <img> tags self-closing in docs

docs/docs/test-types/executor-ginkgo.md
fixing default commands format for ginkgo
-
-
-
=> docs: fix default commands format

.github/workflows/docker-build-api-executors-tag.yaml, .github/workflows/docker-build-develop.yaml, .github/workflows/docker-build-release.yaml, contrib/executor/jmeterd/build/agent/Dockerfile, contrib/executor/jmeterd/build/slaves/Dockerfile, goreleaser_files/.goreleaser-docker-build-executor-jmeterd-commit-only.yml, goreleaser_files/.goreleaser-docker-build-executor-jmeterd.yml
This PR adds a pipeline for a new jmeterd executor and its slave. 
The Dockerhub repositories are:
kubeshop/testkube-jmeterd-slave
kubeshop/testkube-jmeterd-executor
-
-
-
=> ci: jmeterd executor and slave

contrib/executor/jmeterd/pkg/slaves/client.go
Added following two labels in the slave pods:
```
"testkube.io/managed-by": <MASTER_POD>,
"testkube.io/test-name":  <TEST_NAME>,
```
-
-
-
=> feat: Add labels to the slave pods

api/v1/testkube.yaml, pkg/api/v1/testkube/model_test_suite_execution_extended.go, pkg/repository/testresult/mongo.go
Closes https://github.com/kubeshop/testkube/issues/4410
-
-
-
=> fix: do not store output in test suite execution result

test/dashboard-e2e/crd/crd.yaml
Update CRD for Dashboard tests to match the mono-repository setup (as per https://github.com/kubeshop/testkube-dashboard/pull/898)
-
-
-
=> fix: update CRD for Dashboard tests to match mono-repository setup

pkg/storage/minio/minio.go
…cement (#4444)
Minio creates empty file for folder when AWS S3 is used causing subsequent files to fail downloading.
-
- Added filter for empty file names and skip them
-
=> fix: test artifacts failing due to empty file placement (#4444)

docs/src/css/custom.css
sidebar was not showing on smaller screens for the docs. removed backdrop-filter to fix the issue.
before:
sidebar is behind main content when clicking on hamburger menu
without backdrop filter:
sidebar shows when clicked on
-
-
-
=> docs: fix navbar not showing on small screens

docs/docusaurus.config.js, docs/src/css/custom.css, docs/src/theme/AnnouncementBar/index.js, docs/src/theme/Navbar/index.js, docs/src/theme/Navbar/styles.module.css
- move announcement bar below the navigation bar
- add Testkube Cloud announcement in docs
- fix the search button on mobile devices
| Description | Before | After |
|:-:|-|-|
| Search button | <img width="373" alt="Zrzut ekranu 2023-10-19 o 14 19 56" src="https://github.com/kubeshop/testkube/assets/3843526/7a5e2a73-40de-420c-a565-648cada6c05e"> | <img width="360" alt="Zrzut ekranu 2023-10-19 o 14 20 52" src="https://github.com/kubeshop/testkube/assets/3843526/9b3530f0-a76c-4f6c-97c9-4b55851a94e0"> |
| Description | Screenshot |
|:-:|-|
| Announcement (desktop) | <img width="2055" alt="Zrzut ekranu 2023-10-19 o 14 22 07" src="https://github.com/kubeshop/testkube/assets/3843526/9381d59b-d5b6-4303-9ca2-de54114cf6d1"> |
| Announcement (mobile) | <img width="357" alt="Zrzut ekranu 2023-10-19 …
=> feat: add Testkube Cloud announcement in docs

internal/app/api/v1/testsuites.go, pkg/repository/result/mongo.go, pkg/repository/testresult/mongo.go
* Add projection for getting latest tests / test suites to speed up
* Add filtering by `testsuite.name` for getting total count of test suite executions
We don't have MongoDB migrations mechanism yet, so we need to manually add these indexes:
```js
// Migrations
db.getSiblingDB("testkube").getCollection("testresults").createIndex({"id": "hashed"})
db.getSiblingDB("testkube").getCollection("testresults").createIndex({"testsuite.name": "hashed"})
db.getSiblingDB("testkube").getCollection("results").createIndex({"id": "hashed"})
db.getSiblingDB("testkube").getCollection("results").createIndex({"testname": "hashed"})
// Rollback
db.getSiblingDB("testkube").getCollection("testresults").dropIndex("id_hashed")
db.getSiblingDB("testkube").getCollection("testresults").dropIndex("testsuite.name_hash …
```
=> feat: improve performance for slowest operations / fix: loading total executions number for test suite

internal/app/api/v1/executions_test.go, internal/app/api/v1/tests.go, internal/app/api/v1/testsuites.go, pkg/cloud/data/result/result.go, pkg/cloud/data/result/result_test.go, pkg/cloud/data/testresult/testresult.go, pkg/cloud/data/testresult/testresult_test.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/repository/result/interface.go, pkg/repository/result/mock_repository.go, pkg/repository/result/mongo.go, pkg/repository/result/mongo_numbers.go, pkg/repository/testresult/interface.go, pkg/repository/testresult/mock_repository.go, pkg/repository/testresult/mongo.go
Redesigned MongoDB queries for loading test/test suite executions.
* **Earlier:** there were 4 queries to MongoDB: `aggregate()` to get latest executions ID per `starttime` and `find()` to get these executions, and both the same for `endtime`. Later these were compared based on latest date.
* **Now:** all of that is resolved in a single `aggregate()`
Thanks to that, it works faster. To make it even faster, we would need to persist something like `updatetime` (latest of `starttime`/`endtime`) in the execution, but it can be a further improvement in future.
> **Cloud implementation**
> As for now Cloud API is using similar strategy as OSS before, with loading two sets on both `starttime`/`endtime` and comparing them, I kept the same behavior as it was for the `CloudRepository`.
>
> When the …
=> feat: improve performance of listing tests/test suites/executions

pkg/repository/result/mongo.go
With last PR I have introduced a bug, that limits fetched executions to 1 item. This PR is deleting this limit.
=> fix: return executions for all tests when requested

internal/app/api/v1/testsuites.go
- Right now, maximum results counted in test suites executions totals is the page size (defaults: 100). It should ignore paging filters, and instead return number for totals.
=> fix: total number of test suite executions should ignore paging filters

docs/docs/testkube-cloud/articles/AI-test-insights.md, docs/docs/testkube-cloud/articles/cached-results.md, docs/docs/testkube-cloud/articles/status-pages.md, docs/src/css/custom.css
Added PRO FEATURE badge to Pro Feature pages (AI Test Insights, Cached Test Results, Status Pages)
Will add FREE badge as well to go side by side on same <span> element to those features that are available both in PRO and FREE versions of TK Cloud 
-
-
-
=> docs: add pro feature badge to pro feature pages

docs/docs/articles/creating-first-test.md, docs/docs/articles/getting-started.md, docs/docs/articles/install-cli.mdx, docs/docs/articles/open-source-or-cloud.md, docs/docs/testkube-cloud/articles/testkube-oss.md, docs/sidebars.js
Add 'Open Source or Cloud' doc to the Overview section at the beginning of the documentation.
-
-
-
=> docs: Getting Started Rework

internal/db-migrations/02_execution_search_indexes.down.json, internal/db-migrations/02_execution_search_indexes.up.json, pkg/repository/result/mongo.go, pkg/repository/testresult/mongo.go
* This is making use of the queries covered by indexes. It's achieving constant low-time results for big sets of data.
* It requires indexes though
* without indexes is heavily slow, because its `$lookup`s performance depends on them. Without indexes, the solution is 30x slower than existing one
* ~making as draft until any mechanism to create them automatically will be there (i.e.) https://github.com/kubeshop/testkube/pull/4534~
=> feat: speed up - use covered queries for tests/test suites list

docs/docs/articles/github-actions.md, docs/docs/articles/run-tests-with-github-actions.md
=> docs: update GH action

pkg/executor/agent/agent.go
should fix this first line:
-
-
-
=> fix: result line for websockets

.github/workflows/test.yaml, config/executors.json, contrib/executor/tracetest/Makefile, contrib/executor/tracetest/README.md, contrib/executor/tracetest/pkg/model/result.go, contrib/executor/tracetest/pkg/runner/runner.go, contrib/executor/tracetest/pkg/runner/runner_integration_test.go, contrib/executor/tracetest/pkg/runner/runner_test.go, contrib/executor/tracetest/pkg/runner/tracetest_core_runner.go, contrib/executor/tracetest/pkg/runner/tracetest_runner.go, contrib/executor/tracetest/pkg/testing/docker-compose-tracetest-cloud.yaml, contrib/executor/tracetest/pkg/testing/docker-compose-tracetest-core.yaml, contrib/executor/tracetest/pkg/testing/tracetest-config.yaml, contrib/executor/tracetest/pkg/testing/tracetest-provision.yaml, contrib/executor/tracetest/pkg/testing/tracetest-test-script.yaml
This PRs update Tracetest executor to support both [Tracetest](https://docs.tracetest.io/getting-started/installation/) and [Tracetest Core](https://docs.tracetest.io/core/getting-started/installation/).
-
-
-
=> feat: adding support for tracetest cloud on tracetest executor

internal/app/api/v1/executions_test.go, internal/app/api/v1/tests.go, internal/app/api/v1/testsuites.go, pkg/cloud/data/result/result.go, pkg/cloud/data/result/result_test.go, pkg/cloud/data/testresult/testresult.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/repository/result/interface.go, pkg/repository/result/mock_repository.go, pkg/repository/result/mongo.go, pkg/repository/testresult/interface.go, pkg/repository/testresult/mock_repository.go, pkg/repository/testresult/mongo.go
* Return (empty) pointer to the Execution instead of empty Execution struct
- https://github.com/kubeshop/testkube/issues/4635
=> fix: do not return empty latestExecution with Test/TestSuite

cmd/kubectl-testkube/commands/root.go, cmd/kubectl-testkube/commands/tests/run.go, cmd/kubectl-testkube/commands/testsuites/run.go
- pass the context down to Cobra commands, which is canceled on SIGINT/SIGTERM
- exit CLI on termination signal during test/test suite watch
-
-
=> fix: allow terminating CLI while watching test/test suite run

cmd/kubectl-testkube/commands/testsuites/run.go, go.mod, go.sum, pkg/api/v1/testkube/model_test_suite_execution_extended.go, pkg/ui/table.go
Speed up the table output, as it took a very long time for the test suites with long error messages.
-
- Use newer [**olekukonko/tablewriter**](https://github.com/olekukonko/tablewriter) - it's much faster (1MB of data in 1 second instead of minutes)
- Truncate the error messages to maximum of 100.000 characters (in the table)
- https://github.com/kubeshop/testkube/issues/4610
=> fix: table output performance

docs/docusaurus.config.js
"Edit this page" links on documentation pages were broken because of the change to have the `develop` branch as default. This PR fixes the editUrl in Docusaurus config.
=> fix: editUrl for docs

cmd/api-server/main.go, contrib/executor/init/pkg/runner/runner.go, internal/app/api/v1/executions.go, internal/app/api/v1/server.go, internal/config/config.go, pkg/envs/variables.go, pkg/executor/common.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/executor/scraper/factory/factory.go, pkg/executor/scraper/minio_scraper_integration_test.go, pkg/executor/scraper/minio_uploader.go, pkg/executor/scraper/minio_uploader_integration_test.go, pkg/storage/minio/artifacts_storage_integration_test.go, pkg/storage/minio/minio.go
This adds support to provide `STORAGE_SKIP_VERIFY` environment variable which disables TLS verification in MinIO
-
-
- issue when using MinIO with a S3 storage which has a self-signed certificate
=> feat: add support for skip tls verify in minio

internal/db-migrations/01_create_indexes.down.json, internal/db-migrations/01_create_indexes.up.json, internal/db-migrations/02_execution_search_indexes.down.json, internal/db-migrations/02_execution_search_indexes.up.json, pkg/repository/result/mongo.go, pkg/repository/testresult/mongo.go
Make the Testkube OSS compatible with AWS DocumentDB
- Use `aggregate` on collection instead of database
- Use regular indexes instead of hashed
- https://github.com/kubeshop/testkube/issues/4680
=> fix: avoid hashed indexes and aggregate: 1

cmd/kubectl-testkube/commands/agent.go, docs/docs/cli/testkube.md, docs/docs/cli/testkube_agent.md, docs/docs/cli/testkube_agent_debug.md
=> docs: make agent pro

cmd/api-server/main.go, pkg/repository/result/mongo.go, pkg/repository/result/mongo_integration_test.go, pkg/repository/testresult/mongo.go, pkg/repository/testresult/mongo_test.go
* add simpler implementation of MongoDB queries for DocumentDB
* DocumentDB has pretty weak coverage of MongoDB features - https://www.isdocumentdbreallymongodb.com/
* These won't be performant, but will allow using Testkube until we will fully deprecate DocumentDB
-
-
- https://github.com/kubeshop/testkube/issues/4697
=> fix: add simpler implementation of MongoDB queries for DocumentDB

pkg/scheduler/testsuite_scheduler.go
Jmeter Executor was failing when run in distributed mode because namespace was not propagated when test was executed as part of a testsuite.
This PR fixes propagation of test namespace when run as part of a testsuite.
-
-
-
=> fix: propagate namespace when test is executed as part of a testsuite

contrib/executor/jmeterd/pkg/runner/runner.go, contrib/executor/jmeterd/pkg/slaves/utils.go
Change logic for jmeter so that SLAVES_COUNT == zero or undefined works in standalone mode, and > 0 runs in distributed mode
-
-
-
=> feat: change logic for detecting jmeter run mode 

cmd/api-server/main.go, internal/config/config.go, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/events_test.go, pkg/agent/logs_test.go, pkg/envs/variables.go, pkg/executor/common.go, pkg/executor/containerexecutor/containerexecutor_test.go, pkg/executor/scraper/factory/factory.go
* add config option for skipping cert verify when connecting to cloud/enterprise
* revert .env change
* revert .env change again
* update envvar inconsistent names
* add newline to .env
* rename cloud to pro variable
-
-
-
=> feat: add config option for skipping cert verify when connecting to cloud/enterprise (#4763)

contrib/executor/soapui/build/agent/Dockerfile
Pin starter image version for security checks
Previous SoapUI version used: 5.7.0
New version: 5.7.2
Checked with:
```
$ docker run --entrypoint /bin/sh -it kubeshop/testkube-soapui-executor:6ec1f70
$ ls
EntryPoint.sh  RunProject.sh  SoapUI-5.7.0
```
-
-
-
=> fix: pin soapui starter image version

contrib/executor/init/pkg/runner/runner.go
* The pre-run and post-run scripts were put in the working directory, while it not necessarily was available as a volume.
* Moved all of shell files into `DataDir`
* Move command to separate file so initial `workingDir` will be persisted for post-run script
* Additionally, the failure of pre-run script is not blocking the rest of executing.
* Added `set -e` to fail fast
-
-
- testkube#4719
=> fix: put pre-run and post-run script files in the data volume

contrib/executor/init/pkg/runner/runner.go
* https://demo.testkube.dev/tests/container-executor-postman-smoke/executions/658443dba1e038c8cd41bb36 - arguments are not passed to command script
-
-
-
=> fix: pass command arguments down

docs/docs/articles/running-tests.md
Fix an invalid flag (`--parameter|-p` instead of `--variable|-v`) in the [Passing parameters](https://docs.testkube.io/articles/running-tests/#passing-parameters) section of Testkube docs.
This closes https://github.com/kubeshop/testkube/issues/4844
-
-
-
=> docs: fix invalid flag in running-tests.md

install.sh
This PR updates the `install` script by adding a condition to install latest release if no beta ones are found.
-
-
-
=> fix: add condition to install latest release if no beta found

pkg/repository/result/mongo.go, pkg/repository/testresult/mongo.go
Use `$sort` + `$group` instead of pure `$group`, as the aggregate was planned with `COLLSCAN` instead of `PROJECTION_COVERED` despite being covered by index
-
-
- https://linear.app/kubeshop/issue/TKC-1157/%5Bapi-performance%5D-test-suite-executions-query-performance
| Before | After |
|-|-|
| <img width="583" alt="Zrzut ekranu 2024-01-5 o 15 00 21" src="https://github.com/kubeshop/testkube/assets/3843526/7a8f08c7-5f4d-4eb5-bf1c-df2b8220c5fd"> | <img width="552" alt="Zrzut ekranu 2024-01-5 o 15 01 20" src="https://github.com/kubeshop/testkube/assets/3843526/c4ea029c-3f2f-4a03-a7d2-71b9173c2d20"> |
=> fix: avoid COLLSCAN in favor of PROJECTION_COVERED while counting execution totals

pkg/repository/result/mongo.go, pkg/repository/testresult/mongo.go
-
-
- https://github.com/kubeshop/testkube/pull/4860
=> fix: cherry-pick: avoid COLLSCAN in favor of PROJECTION_COVERED while counting execution totals

docs/docs/articles/deprecations.md, docs/sidebars.js
=> docs: deprecating internal /results route

pkg/slack/slack.go
When configured, the Slack token is shown in plain text in the logs. This is not desired and this PR masks all but the first part of the token.
- Mask slack token in log message
=> fix: mask slack token in log message

build/kubectl-testkube/Dockerfile
This PR aims to simplify writing the testkube commands when using the official image in other CI/CD platforms
-
-
-
=> chore: add symbolic links for 'testkube' and 'tk' for kubeshop/testkube image

cmd/kubectl-testkube/commands/common/flags.go, cmd/kubectl-testkube/commands/common/masterFlags_test.go, cmd/kubectl-testkube/commands/context/set.go
It came up on slack that we marked the flags `--pro-root-domain` and `--cloud-root-domain` deprecated, but not in a backwards-compatible manner. This PR fixes that.
-
-
-
=> fix: accept deprecated domain flags

internal/app/api/v1/executions.go, internal/app/api/v1/testsuites.go
=> fix: fiber doesn't allow to use query string outside handler

cmd/api-server/main.go, internal/app/api/v1/server.go, pkg/executor/client/job.go, pkg/executor/containerexecutor/containerexecutor.go, pkg/executor/output/parser.go, pkg/executor/output/parser_test.go, pkg/logs/client/interface.go, pkg/logs/client/mock_initializedstreampusher.go, pkg/logs/client/mock_stream.go, pkg/logs/client/stream.go, pkg/logs/events/events.go, pkg/logs/events_test.go, pkg/logs/sidecar/proxy.go, pkg/scheduler/test_scheduler.go
* one way to pass and create logs (was messy pointer and non-pointer) 
* passed logs stream as parameter to executors and api
-
-
-
=> fix: use pointer everywhere when passing log chunk

cmd/api-server/main.go, cmd/kubectl-testkube/commands/root.go
* At the moment, when the termination signal is received (i.e. <kbd>Ctrl</kbd>+<kbd>C</kbd>), the application (both API and CLI) starts graceful termination
* It's not possible to stop it, until the graceful termination will end
* Often you may want to kill the application - second signal should kill the application
-
-
-
=> fix: kill application on 2nd termination signal

cmd/kubectl-testkube/commands/common/render/list.go, cmd/kubectl-testkube/commands/common/render/obj.go
The CLI with `--output go --go-template "some-template-here"` was not working.
* The renderer for Lists is trying to convert `interface{}` (with some `[]T` under the hood) to `[]interface{}`, what will never succeed
* Instead, it's using now reflection, to build actual Golang slice
* The renderer for Objects was trying to convert `interface{}` to `[]interface{}` similarly to the List one, despite the fact that we are passing `struct`s inside
* Now, it's just passing the `interface{}` down
=> fix: Go template rendering in CLI

cmd/kubectl-testkube/commands/create.go, cmd/kubectl-testkube/commands/delete.go, cmd/kubectl-testkube/commands/get.go, cmd/kubectl-testkube/commands/testworkflows/create.go, cmd/kubectl-testkube/commands/testworkflows/delete.go, cmd/kubectl-testkube/commands/testworkflows/get.go, cmd/kubectl-testkube/commands/testworkflows/renderer/testworkflow_obj.go, cmd/kubectl-testkube/commands/testworkflowtemplates/create.go, cmd/kubectl-testkube/commands/testworkflowtemplates/delete.go, cmd/kubectl-testkube/commands/testworkflowtemplates/get.go, cmd/kubectl-testkube/commands/testworkflowtemplates/renderer/testworkflow_obj.go, pkg/api/v1/testkube/model_test_workflow_extended.go, pkg/api/v1/testkube/model_test_workflow_template_extended.go, pkg/ui/ui.go
* Add `tk get testworkflow` (`tw`) and `tk get testworkflowtemplate` (`twt`) commands to get list of resources
* Selection by labels is available (`--labels`, `-l`)
* Getting list of CRDs is available (`--crd-only`)
* Add `tk get testworkflow <name>` (`tw <name>`) and `tk get testworkflowtemplate <name>` (`twt <name>`) commands to describe the resources
* Getting CRD is available (`--crd-only`)
* Add `tk delete testworkflow` and `tk delete testworkflowtemplate` commands
* `tk delete tw --all` to delete all entries
* `tk delete tw -l some=value` to delete entries by labels
* `tk delete tw some-name` to delete specific one
* Add `tk create testworkflow` and `tk create testworkflowtemplate` commands
* Only name can be configured by arguments, like `--name some-workflow`
* The rest of the …
=> feat(TKC-1462): add CLI commands for managing TestWorkflows

.github/workflows/docker-build-api-executors-tag.yaml, .github/workflows/docker-build-develop.yaml, .github/workflows/docker-build-release.yaml, build/testworkflow-init/Dockerfile, cmd/tcl/README.md, cmd/tcl/testworkflow-init/data/config.go, cmd/tcl/testworkflow-init/data/emit.go, cmd/tcl/testworkflow-init/data/expressions.go, cmd/tcl/testworkflow-init/data/get.go, cmd/tcl/testworkflow-init/data/state.go, cmd/tcl/testworkflow-init/data/step.go, cmd/tcl/testworkflow-init/data/types.go, cmd/tcl/testworkflow-init/data/utils.go, cmd/tcl/testworkflow-init/main.go, cmd/tcl/testworkflow-init/output/constants.go, cmd/tcl/testworkflow-init/output/output.go, cmd/tcl/testworkflow-init/run/run.go, goreleaser_files/.goreleaser-docker-build-testworkflow-init.yml, internal/config/config.go, pkg/imageinspector/configmapstorage.go, pkg/imageinspector/serialization.go, pkg/tcl/expressionstcl/generic.go, pkg/tcl/expressionstcl/generic_test.go, pkg/tcl/expressionstcl/math.go, pkg/tcl/expressionstcl/parse.go, pkg/tcl/expressionstcl/parse_test.go, pkg/tcl/expressionstcl/utils.go, pkg/tcl/testworkflowstcl/testworkflowresolver/apply.go, pkg/tcl/testworkflowstcl/testworkflowresolver/config.go
Prepare Init Process that will wrap all TestWorkflows operations in the containers. Additionally, it includes some fixes and improvements to the Expressions Engine (force simplifying unknown structs, better boolean prediction).
It supports:
* Skipping container execution
* Passing status to parents/children
* Sharing state across different containers
* Aborting steps
* Negative expectation
* Timeouts (nested already)
* Retry (single step only)
* Computing variables locally, i.e. reading files (`file("/data/some/path")`), reading shared data
In the future, we need to support:
* Nested retries (sharing iterations is already there)
* Obfuscating sensitive data in the output
* Saving the data from the output clauses in the shared state
=> feat(TKC-1580): prepare Init Process for TestWorkflow containers

goreleaser_files/.goreleaser-docker-build-testworkflow-init.yml
* Adjust GoReleaser configuration for TestWorkflow Init Process, as it's failing - https://github.com/kubeshop/testkube/actions/runs/8114485079/job/22180235076
=> fix(TKC-1580): adjust GoReleaser configuration for TestWorkflow Init Process

pkg/storage/minio/minio_connecter.go
The error messages logged whenever `minio` fails to connect are misleading as they are prefixed with `nats`.
-
-
- Misleading error messages when connecting to minio
=> fix: misleading error messages for minio

pkg/api/v1/client/uploads.go
Direct client for copy files did not take all parts of the URI into account when creating a connection
https://github.com/kubeshop/testkube/issues/5118
-
-
-
=> fix: direct client uri fix

Makefile, api/v1/testkube.yaml, build/testworkflow-toolkit/Dockerfile, pkg/api/v1/testkube/model_test_workflow_output.go, pkg/api/v1/testkube/model_test_workflow_status_extended.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go
`libssl1.1` is not available in our current Alpine - https://github.com/kubeshop/testkube/actions/runs/8201841833/job/22431395514
-
-
-
=> fix(TKC-1642): update TestWorkflow Toolkit to use libssl3

api/v1/testkube.yaml, pkg/api/v1/testkube/model_test_workflow_result.go, pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/api/v1/testkube/model_test_workflow_result_summary.go
* add `durationMs` (number) to TestWorkflow results
=> feat: add durationMs to the TestWorkflow's result

pkg/api/v1/testkube/model_test_workflow_result_extended.go
* add missing `durationMs` during cloning TestWorkflow's result
=> fix: add missing durationMs for TestWorkflowResult

pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* Clean up TestWorkflow jobs after finish
=> fix: clean up TestWorkflow jobs after finish

pkg/executor/containerexecutor/containerexecutor.go
Fix #5130 Use on;y scheduler logic
-
-
-
=> fix: remove duplicated logic for container executor

pkg/tcl/apitcl/v1/testworkflowexecutions.go
* `POST /test-workflow-executions/:executionID/abort` was searching by TestWorkflow name, while it didn't exist
=> fix: aborting execution via endpoint without test workflow name

docs/docs/articles/deploying-in-aws.md
I would like contribute to prevent other users from wasting their time.
Turns out ingress setup documentation is not up to date - I couldn't setup testkube with ALB without going through closed tickets - https://github.com/kubeshop/testkube/issues/4850. At some point You have updated api path but probably forgot about documentation. 
-
-
- updated documentation referencing api path from /results/v1 to /v1 in deploying-in-aws.md
=> fix(docs:deploying-in-aws): correct api path from /results/v1 to /v1

pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go
* Make the container's `queuedAt` time == `finishedAt` of the previous - ignore the time Kubernetes used for scheduling the next container
=> feat: fill time gaps in the TestWorkflow clock

pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* when any step is marked as aborted, mark the whole execution as aborted
=> fix: gracefully handle critical pod errors (like OOM) in TestWorkflows

pkg/tcl/testworkflowstcl/testworkflowprocessor/constants.go
* use `version.Version` instead of `common.Version` for determining the current API version
=> fix: use proper application version constant

api/v1/testkube.yaml, go.mod, go.sum, pkg/api/v1/testkube/model_test_workflow_step_artifacts.go, pkg/tcl/mapperstcl/testworkflows/kube_openapi.go, pkg/tcl/mapperstcl/testworkflows/openapi_kube.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* https://github.com/kubeshop/testkube-operator/pull/233
=> fix: add `workingDir` support for TestWorkflow artifacts step

pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go
- for some reason (bug?) GKE sends the SIGKILL when the container is already done successfully, and the Pod becomes stuck
=> fix: handle gracefully OOMKilled errors on GKE

pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go
* Display Termination reason
| <img width="984" alt="Zrzut ekranu 2024-03-14 o 12 32 36" src="https://github.com/kubeshop/testkube/assets/3843526/9f2c500b-464f-4715-a44b-601a6d60e8a1"> | <img width="1054" alt="Zrzut ekranu 2024-03-14 o 12 32 57" src="https://github.com/kubeshop/testkube/assets/3843526/396ab7ff-96cc-4da0-a1c1-3ddabc370f45"> |
|-|-|
=> feat: display abort reason for TestWorkflow execution

README.md, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/common/validator/cloudcontext.go, cmd/kubectl-testkube/commands/pro/connect.go, cmd/kubectl-testkube/commands/pro/disconnect.go, cmd/kubectl-testkube/commands/pro/init.go, docs/docs/articles/testkube-oss.md, docs/docs/cli/testkube_init.md, docs/docs/cli/testkube_install.md, docs/docs/cli/testkube_pro_connect.md
This PR removes the dashboard operations from the `pro connect` and `pro disconnect` commands. Furthermore, it fixes the issue of the `pro disconnect` not updating the context properly, see TKC-1749
-
-
-
=> feat: [TKC-1740] remove dashboard from connect and disconnect commands

test/cypress/executor-tests/crd-workflow/smoke.yaml, test/k6/executor-tests/crd-workflow/smoke.yaml
Negative cases (expected failures):
- test failure, `condition: always` for artifacts (no artifacts)
- test failure, `condition: always` for artifacts (with artifacts)
- resource limits (pod is terminated because of that)
- incorrect workingDir
- incorrect repo path
=> feat: workflow tests - negative cases

api/v1/testkube.yaml, internal/app/api/v1/handlers.go, pkg/api/v1/testkube/model_server_info.go, pkg/telemetry/payload.go, pkg/telemetry/telemetry.go
https://linear.app/kubeshop/issue/TKC-1571/use-fixed-user-id-for-cli-telemetry
-
-
-
=> fix: use cluster/environment ids for cli telemetry

pkg/tcl/testworkflowstcl/testworkflowcontroller/cleanup.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go
* Kubernetes cluster will not necessarily send `DELETED` events for watch - it may send `MODIFIED` with `DeletionTimestamp`
-
-
-
=> fix: (main) manual abort (improve deletion detection)

.github/workflows/release-dev.yaml
The dev releases (with the suffix `-beta00*`) of testkube CLI are pushed to the same APT server the users are using, therefore increasing the risk of delivering broken executables. The purpose of this PR is to disable these.
See this thread: https://testkubeworkspace.slack.com/archives/C06D9EYTQ2J/p1711033378785719
-
-
-
=> ci: disable dev releases to the apt server

cmd/tcl/testworkflow-init/data/expressions.go, cmd/tcl/testworkflow-toolkit/artifacts/walker.go, go.mod, pkg/tcl/expressionstcl/accessor.go, pkg/tcl/expressionstcl/call.go, pkg/tcl/expressionstcl/convert.go, pkg/tcl/expressionstcl/libs/fs.go, pkg/tcl/expressionstcl/libs/fs_test.go, pkg/tcl/expressionstcl/parse.go, pkg/tcl/expressionstcl/parse_test.go, pkg/tcl/expressionstcl/propertyaccessor.go, pkg/tcl/expressionstcl/static.go, pkg/tcl/expressionstcl/stdlib.go, pkg/tcl/expressionstcl/tokenize.go, pkg/tcl/expressionstcl/tokenize_test.go, pkg/tcl/expressionstcl/tokens.go, pkg/tcl/expressionstcl/typechecking.go, pkg/tcl/expressionstcl/utils.go
Add more built-in functionalities for Expressions language - will be required/helpful for more complex queries in Distributed Tests.
* Nested accessors (`a.b.c.d`) are more smart
* Earlier: it was asking machine specifically about `a.b.c.d`,
* Now: it tries to fallback to `a.b.c`, `a.b` and `a` and seeking for inner keys
* Helpful for reading unknown schemas, like Pod schema in the struct
* Wildcard accessor implemented - `a.b.*.d`
* It helps read different common values, like `spawn.slaves.*.ip`
* Spread argument operator implemented (`...`)
* It helps to pass custom arguments, i.e. to sanitize results from another function
* `shellquote(glob("**/*_test.go")...)`
* `glob(string...)`: to find files matching pattern
* Will help take (and slice) list of tests to run, i.e. …
=> feat(expressions): add more functionalities

cmd/kubectl-testkube/commands/common/flags.go, cmd/kubectl-testkube/commands/context/set.go, cmd/kubectl-testkube/config/master.go
Fixes CLI in enterprise - currently composing URIs logic don't fit enterprise use cases. 
It's combersome to mess with localhost based installation 
I've introduced possibility to fully control uris without any logic 
-
-
-
=> fix: allow to fully override URIs in CLI

cmd/tcl/testworkflow-init/data/expressions.go, cmd/tcl/testworkflow-init/data/global.go, cmd/tcl/testworkflow-init/data/state.go, pkg/tcl/expressionstcl/generic.go, pkg/tcl/expressionstcl/generic_test.go, pkg/tcl/expressionstcl/math.go, pkg/tcl/expressionstcl/parse_test.go
* Fix simplifying string enum values (instead of panic)
* Fix simplifying math (as it could result in different equation before)
* Expose expressions machine with internal state, so it can be used by Toolkit
=> fix(expressions): simplifying math and enums, expose common expressions machine for steps

cmd/tcl/testworkflow-init/data/emit.go, cmd/tcl/testworkflow-init/data/state.go, cmd/tcl/testworkflow-init/run/run.go, cmd/tcl/testworkflow-init/utils/outputProcessor.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/cleanup.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/notification.go, pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/processor.go
* Expose the Output printed ([**PrintOutput**](https://github.com/kubeshop/testkube/blob/develop/cmd/tcl/testworkflow-init/data/emit.go#L74-L76)) from TestWorkflow steps into internal state, so it can be used across different steps
* It will be used to pass pod data of services, like auto-created database IP
* Deduplicate empty lines when output appears
* Avoid grace period for deleting resources
=> feat: allow reading dynamically output of TestWorkflows

cmd/tcl/testworkflow-toolkit/commands/execute.go
* pass base Expressions machine for the `matrix` and `shards` computation in `execute` step
=> fix(testworkflows): pass dynamic machine for the matrix & shards in execute step

pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go
I don't have a clue how it can happen, but received panic error from @vsukhin:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x180 pc=0x1fed8ea]
goroutine 316 [running]:
github.com/kubeshop/testkube/pkg/tcl/testworkflowstcl/testworkflowcontroller.WatchJobPreEvents.func1()
/build/pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go:363 +0x1ea
created by github.com/kubeshop/testkube/pkg/tcl/testworkflowstcl/testworkflowcontroller.WatchJobPreEvents in goroutine 312
/build/pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go:349 +0xe5
```
Assuming then that watch events may fall into faulty state, where the value is there, but it's nullish. In that case, we will ignore it waiting for a valid one.
=> fix(testworkflows): handle edge case of nullish event sent

.github/workflows/test.yaml
Based on https://downloads.apache.org//jmeter/binaries listing, only 5.6.3 is available now
=> fix: update JMeter for integration to version which binary is provided by Apache

cmd/kubectl-testkube/commands/get.go
The help text for the --output flag in the CLI suggest that there is type "go-template", when in fact it is just "go".
Compare:
- Flag defined: [cmd/kubectl-testkube/commands/get.go](https://github.com/kubeshop/testkube/blob/develop/cmd/kubectl-testkube/commands/get.go#L57)
- Flag used: https://github.com/kubeshop/testkube/blob/develop/cmd/kubectl-testkube/commands/common/render/obj.go#L13
-
-
- misleading help text for --output flag in Testkube CLI
=> fix: help text refers to invalid option for --output flag

docs/docs/articles/install/install-with-cli.md
Just change the order of `testkube init` options, moving OSS to the bottom.
=> docs: Reverse order of CLI init profiles (OSS last)

.github/dependabot.yml
Most of the GitHub Actions seem to be out of date. Use dependabot to keep them up to date.
-
-
-
=> chore: Add GitHub Actions to dependabot

cmd/kubectl-testkube/commands/init.go, cmd/kubectl-testkube/commands/pro/init.go, cmd/kubectl-testkube/commands/purge.go
This PR tackles multiple minor issues and polishing in the installer:
- `testkube init demo` during Installing Testkube… should give interactive spinner
- `testkube init --list-profiles` does not exist yet -> Changed to --help
- `testkube init agent` does not exist yet -> Alias for testkube pro init
- `testkube dashboard port-forward` -> testkube dashboard 
- `testkube init <profile> --export` does not exist yet -> Supports only demo profile for now
- 🐛 testkube uninstall does not work for some weird reason. All it does it wrap helm uninstall which gives different output. Need to check if "middleware" is running.
- Give help / instructions when Helm install fails. Where to go? What to do?
=> feat(installer): minor improvements

pkg/api/v1/testkube/model_test_workflow_execution_extended.go, pkg/tcl/apitcl/v1/testworkflowexecutions.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/channel.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* use default namespace if execution doesn't have it
* old executions + executions when newest Agent is used with older Pro instance
* make `Channel.PeekMessage` non-blocking
* so it successfully handles timeouts
* sort out `StopController` when it's not needed as context is passed
=> fix(testworkflows): orchestration fixes

config/job-container-template.yml, config/job-scraper-template.yml, config/job-template.yml, config/slave-pod-template.yml, pkg/executor/containerexecutor/templates/job.tmpl
-
- Fix job templates to be able to pull from Git repositories using private-CAs. Covers prebuilt and container executors only, not workflows.
- TKC-1901
- TKC-1911
=> fix: pulling from git servers using private ca

cmd/tcl/testworkflow-toolkit/commands/parallel.go
* it was comparing wrong values to decide if the status should be surfaced
| <img width="1040" alt="Zrzut ekranu 2024-05-21 o 11 23 34" src="https://github.com/kubeshop/testkube/assets/3843526/798d5cfb-c83d-4c7c-ad19-c0b227b538cd"> |
|-|
=> fix(testworkflows): displaying log on parallel step status change

test/integration/crd-workflow/testkube-integration-tests.yaml
* On `testkube-cloud-basic` cluster, it hits `read only filesystem` errors for accessing `/go-cache`. Works fine with `/tmp` though
=> fix: use /tmp host dir for integration tests Go cache

pkg/tcl/testworkflowstcl/testworkflowprocessor/container.go
* Because of that, i.e. cloning private repositories was not working
=> fix(testworkflows): don't resolve environment variables if they are dynamic (i.e. from secrets)

api/v1/testkube.yaml, pkg/api/v1/testkube/model_test_workflow_independent_service_spec.go, pkg/api/v1/testkube/model_test_workflow_independent_step_parallel.go, pkg/api/v1/testkube/model_test_workflow_service_spec.go, pkg/api/v1/testkube/model_test_workflow_step_execute_test_ref.go, pkg/api/v1/testkube/model_test_workflow_step_execute_test_workflow_ref.go, pkg/api/v1/testkube/model_test_workflow_step_parallel.go
OpenAPI definition had errors. This PR fixes those.
```
Semantic error at paths./test-workflows/{id}/executions
Declared path parameter "id" needs to be defined within every operation in the path (missing in "post"), or moved to the path-level parameters object
Jump to line 3525
Semantic error at paths./test-workflow-executions/{executionID}/artifacts
Declared path parameter "executionID" needs to be defined as a path parameter at either the path or operation level
Jump to line 3845
Semantic error at paths./test-workflow-executions/{executionID}/artifacts/{filename}
Declared path parameter "executionID" needs to be defined as a path parameter at either the path or operation level
Jump to line 3892
Semantic error at paths./test-workflow-executions/{executionID}/artifact-archive
Declared …
```
=> fix: fix semantic errors in yaml and generate openapi files

cmd/tcl/testworkflow-toolkit/commands/services.go, cmd/tcl/testworkflow-toolkit/spawn/utils.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/podstate.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/watchinstrumentedpod.go, pkg/triggers/scraper.go
* the Test Workflow was stuck, as it was trying to fetch logs of running service, while it was not finishing, so it was still waiting for logs continuation.
=> fix(testworkflows): fetch logs properly for running services

pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* when tarball content is requested (i.e. by `transfer` clause) there should be mounted EmptyDir volume at that place, if there is no volume yet.
=> fix(testworkflows): mount tarballs when needed (i.e. content.tarball or transfer)

pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/notifier.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/podstate.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/watchers.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/watchinstrumentedpod.go
* When the execution is killed before it's actually started executing, that was locked
* Now, when it receives finish information before start/end, it will wait for 2s for Kubernetes events / other data, and stop otherwise
=> fix(testworkflows): handle TestWorkflow status correctly on immediate kill

.goreleaser-dev.yml, .goreleaser.yml
* `brews[].tap` is replaced with brews[].repository - https://goreleaser.com/deprecations/#brewstap
* `source.rlcp` is now deleted and default - https://goreleaser.com/deprecations/#sourcerlcp
=> fix: adjust GoReleaser configuration for CLI

pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/logs_test.go, pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go
* fix: support non-UTC timezone in Kubernetes logs
* Kubernetes may store the logs with `+03:00` timezone instead of UTC's `Z`
=> fix(testworkflows): support non-UTC timezone in Kubernetes logs

cmd/tcl/testworkflow-toolkit/commands/clone.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* Allow cloning into non-empty directory (where are files mounted)
* Clone to temporary directory, and then copy to the expected one
* Any other solution won't work, as we are not able to stash read-only mounted files, to clone the repository at the same place
=> fix(testworkflows): support overriding repository files with `content.files`

pkg/tcl/apitcl/v1/utils.go
* Only `text/yaml` was reported as a valid YAML type
-
-
-
=> fix: allow application/yaml as accept/content-type for TestWorkflows API

cmd/tcl/testworkflow-toolkit/spawn/utils.go
* `root` label was set incorrectly, so if the TestWorkflow has errored/aborted before end, the pods were left there
=> fix(testworkflows): identify sub-resources from parallel steps and services properly for destroying

pkg/tcl/testworkflowstcl/testworkflowcontroller/notifier.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/constants/constants.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/processor.go, pkg/tcl/testworkflowstcl/testworkflowprocessor/processor_test.go
* Expose `pod` output for all Test Workflows, that contains Pod information, Agent version, and Toolkit/Init Process images
=> feat(testworkflows): add Pod/Agent output on initialization step

cmd/kubectl-testkube/commands/testworkflows/run.go
* Similar to FE, support `+00:00` in Log Output
=> fix(testworkflows): support +00:00 timezone in CLI TestWorkflows logs

cmd/tcl/testworkflow-toolkit/commands/services.go
* in example `volumeMounts` were duplicated = failing pod spec
-
-
-
=> fix(testworkflows): allow passing container settings for services

test/k6/executor-tests/crd-workflow/smoke.yaml
Lower default settings not to rate limit while running them against testkube.io
=> fix: distributed k6 workflows - lower default settings

pkg/expressions/parse_test.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go, pkg/testworkflows/testworkflowprocessor/processor.go
* the labels/annotations were finalized twice, so `{{"{{"}}` was resolved to `{{` and then executed once again, failing the parser.
=> fix: do not finalize labels/annotations twice, breaking escaping

api/v1/testkube.yaml, cmd/kubectl-testkube/commands/testworkflows/run.go, cmd/testworkflow-init/data/emit.go, pkg/api/v1/testkube/model_test_workflow_execution_notification.go, pkg/testworkflows/testworkflowcontroller/controller.go, pkg/testworkflows/testworkflowcontroller/notification.go, pkg/testworkflows/testworkflowcontroller/notifier.go, pkg/testworkflows/testworkflowcontroller/podstate.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go, pkg/testworkflows/testworkflowexecutor/executor.go
* Expose logs about the events like pulling images, temporarily during execution
* They are not part of final logs (except `type: Warning`s, same as now)
* Fixed CLI logs, so they display that a bit better
In future we can hide them on the UI after step is started (`temporary` flag for that, but needs Cloud API update and minor FE changes)
| <img width="1023" alt="Zrzut ekranu 2024-06-19 o 11 16 23" src="https://github.com/kubeshop/testkube/assets/3843526/6a031a87-b463-4baa-82f2-86ba2f0781b7"> | <img width="1012" alt="Zrzut ekranu 2024-06-19 o 11 16 41" src="https://github.com/kubeshop/testkube/assets/3843526/82f048ba-e7c1-477c-b510-aeee6f7642d0"> |
|-|-|
=> feat(testworkflows): expose temporary log lines about the container status

cmd/kubectl-testkube/commands/testworkflows/create.go
=> fix: error handling when creating TW

pkg/testworkflows/testworkflowcontroller/channel.go, pkg/testworkflows/testworkflowcontroller/controller.go, pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/logs_test.go, pkg/testworkflows/testworkflowcontroller/notifier.go, pkg/testworkflows/testworkflowcontroller/utils.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go, pkg/testworkflows/testworkflowexecutor/executor.go
* Batch the log messages, so we don't send a JSON message for every single line
* Batch the results, so we don't save data in MongoDB/Cloud/Kubernetes every time there is a result update
The batching works as follows:
* Wait 50ms after receiving update/log to flush it to User
* Reset the timer on consecutive message, but wait no longer than 100ms to send any update to User
* **Logs only:** it flushes immediately if there is already 64KiB of logs buffered
In the result, the Test Workflows with significant amount of logs are working much better - both the real-time stream is faster, as well as the result computation (so the Test Workflow is marked done almost immediately after it's finished, even when there is a lot of logs).
=> feat(performance): improve Log Processing performance

.github/workflows/docker-build-api-executors-tag.yaml, .github/workflows/release-dev.yaml, .github/workflows/release.yaml, cmd/api-server/main.go, pkg/cloud/data/testworkflow/output.go, pkg/telemetry/payload.go, pkg/testworkflows/testworkflowcontroller/channel.go, pkg/testworkflows/testworkflowcontroller/controller.go, pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/logs_test.go, pkg/testworkflows/testworkflowcontroller/notifier.go, pkg/testworkflows/testworkflowcontroller/utils.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go, pkg/testworkflows/testworkflowexecutor/executor.go, pkg/testworkflows/testworkflowexecutor/testworkflowmetrics.go
=> chore: Release v2.0.7

pkg/testworkflows/testworkflowcontroller/utils.go
* `999999` in Golang time format is not displaying the nanoseconds in case they are 0; it leads to incorrect length while formatting the time for events in logs, so the UI is not able to display them correctly.
=> fix(testworkflows): displaying events

pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/utils.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go, pkg/testworkflows/testworkflowprocessor/container.go
* `TK_SVC_GROUP` (group of services to close) was incorrectly inherited (from lowest container), so the Kill Process worked incorrectly when multiple `services` clauses were used
* `WatchContainerLogs` always used `follow: true`, so for running services it was never finishing, blocking the workflow
=> fix(testworkflows): storing logs for the services

cmd/api-server/main.go, cmd/tcl/testworkflow-toolkit/spawn/utils.go, cmd/testworkflow-toolkit/env/client.go, cmd/testworkflow-toolkit/env/config.go, internal/config/config.go, pkg/cache/cache.go, pkg/cache/inmem.go, pkg/cache/inmem_test.go, pkg/executor/containerexecutor/containerexecutor.go, pkg/imageinspector/secretfetcher.go, pkg/imageinspector/secretfetcher_test.go, pkg/testworkflows/testworkflowexecutor/executor.go, pkg/testworkflows/testworkflowprocessor/container.go
Testkube caches the image pull secrets indefinitely and this can cause issues if the image registry auth gets rotated.
This PR adds support for defining a TTL for the image pull secrets.
-
-
- Issue where customers reported stale image pull credentials being used in Testkube while inspecting image via Skopeo
=> feat: TKC:2213: add support for defining image credentials cache TTL

pkg/testworkflows/testworkflowresolver/analyze.go
Panic occurred, because of reading incorrect field of:
```yaml
parallel:
matrix:
workflowName: ['postman-workflow-smoke', 'k6-workflow-smoke']
description: '{{ matrix.workflowName }} workflow'
template:
name: template-trigger-remote-workflow
config:
apiToken: tkcapi_5b81e9e470b5154ddea1cb4390163b
environmentId: tkcenv_84019fff03aac934
organizationId: tkcorg_539cb664a4446f37
rootDomain: testkube.io
workflowToRun: '{{ matrix.workflowName }}'
```
=> fix: read correctly parallel template

cmd/kubectl-testkube/commands/common/errors.go, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/init.go, cmd/kubectl-testkube/commands/pro/connect.go, cmd/kubectl-testkube/commands/pro/disconnect.go, cmd/kubectl-testkube/commands/pro/init.go, cmd/kubectl-testkube/commands/upgrade.go, pkg/process/exec.go
Define a better user-facing error structure.
Introduce error codes.
Add framework for better error handling in CLI.
Example returned error:
Example code:
```
func lookupKubectlPath() (string, *CLIError) {
kubectlPath, err := exec.LookPath("kubectl")
if err != nil {
return "", NewCLIError(
TKErrMissingDependencyKubectl,
"Required dependency not found: kubectl",
"Install kubectl by following this guide: https://kubernetes.io/docs/tasks/tools/#kubectl",
err,
)
}
return kubectlPath, nil
}
```
-
-
-
=> feat: add support for better error handling in CLI

cmd/testworkflow-toolkit/commands/clone.go
* When `paths` for `content.git` starts with `./` it's ignored by Git - like, i.e. `paths: ["./"]` downloads nothing
* `filepath.Clean` formats the path to a compliant pattern
=> fix: relative paths in sparse cloning

cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/context/set.go
=> fix: populate cloud config without error on noLogin flag

build/logs-server/Dockerfile, pkg/logs/adapter/minio_v2.go
=> fix: logs container using tmp dir

build/logs-server/Dockerfile, pkg/logs/adapter/minio_v2.go
* fix: logs container using tmp dir
* fix: remove chmod
* fix: remove data directory
* fix: remove data directory
-
-
-
=> fix: logs container using tmp dir instead of /data (#5708)

cmd/logs-server/main.go, pkg/logs/adapter/minio_v2.go, pkg/logs/adapter/minio_v2_test.go, pkg/logs/config/logs_config.go
=> fix: use empty path for minio config

cmd/kubectl-testkube/commands/common/render/common.go, cmd/kubectl-testkube/commands/testworkflows/executions.go, cmd/kubectl-testkube/commands/testworkflows/renderer/testworkflowexecution_obj.go, cmd/kubectl-testkube/commands/testworkflows/run.go, cmd/kubectl-testkube/commands/testworkflows/watch.go
=> fix: [TKC-2343] workflow execution url

cmd/tcl/testworkflow-toolkit/spawn/utils.go, pkg/testworkflows/testworkflowexecutor/executor.go
* Expose `dashboard.url` variable, that will either point to OSS URL prefix, or to the Environment's URL prefix
* Expose `organization.id` and `environment.id` (user-facing, not `internal`) variables
- https://linear.app/kubeshop/issue/TKC-2310/%5Bnorauto%5D-%5Bfeature-request%5D-new-workflow-environment-variables-for-org
=> fix(TKC-2310): expose expression variables for simple use of org, env and dashboard

pkg/expressions/generic.go, pkg/testworkflows/testworkflowprocessor/processor.go, pkg/testworkflows/testworkflowprocessor/stage/container.go, pkg/testworkflows/testworkflowprocessor/stage/containerstage.go, pkg/testworkflows/testworkflowprocessor/stage/groupstage.go, pkg/testworkflows/testworkflowprocessor/stage/mock_container.go, pkg/testworkflows/testworkflowprocessor/stage/mock_stage.go, pkg/testworkflows/testworkflowprocessor/stage/stage.go
* When there is information about working directory, user group and command/shell provided for each of the steps, avoid calling the Container Registry for additional metadata.
* additionally `image.command`, `image.args` and `image.workingDir` variables should not be used
```yaml
metadata:
name: workflow-without-inspecting-images
spec:
container:
workingDir: /data
securityContext:
runAsGroup: 1000
job:
activeDeadlineSeconds: 60
steps:
- run:
image: busybox
shell: pwd && tree /data
- run:
image: busybox
command:
- /bin/sh
- -c
args:
- echo 'hello'
- run:
image: busybox
command:
- /bin/sh
- -c
- echo 'hello again'
- run:
image: blah-unknown-image:1234
shell: echo not executed because of unknown image
```
=> feat: avoid getting image metadata from container registry when it is not needed

pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go
* Show `The execution was aborted before.` only for steps that have not started
=> fix: show "execution aborted before" only when the step was not started already

pkg/repository/sequence/mongo.go, pkg/repository/sequence/mongo_integration_test.go
=> fix: support old agent with new cloud migration to new sequence methods

cmd/tcl/testworkflow-toolkit/commands/parallel.go, cmd/testworkflow-init/main.go, cmd/testworkflow-init/orchestration/executions.go, pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/testworkflows/testworkflowcontroller/controller.go, pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/notifier.go, pkg/testworkflows/testworkflowcontroller/podstate.go, pkg/testworkflows/testworkflowcontroller/utils.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go, pkg/testworkflows/testworkflowprocessor/processor.go
=> fix: controlling issues

pkg/testworkflows/testworkflowcontroller/podstate.go
* it's saying that the Pod has been requested for deletion by Kubernetes API, but seems like there are edge cases when situation is different
* googling it is enough for User for now
=> fix: avoid readable message for EvictionByEvictionAPI

cmd/testworkflow-init/orchestration/executions.go, pkg/testworkflows/testworkflowcontroller/podstate.go
* detect Killed Process/Container based on Killed Child Processes
* GKE for some reason is not signaling nor killing the Init Process
* avoid reading step statuses from termination log in case of abort
* Automated heuristics in that case are better
=> fix: properly detect OOMKilled error on GKE

pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/podstate.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go
=> fix: propagate aborted status correctly on GKE's OOMKilled

cmd/tcl/testworkflow-toolkit/commands/services.go
* There was a race condition, where the container may be marked as started, while pod has not registered yet its IP in Testkube
=> fix: ensure there is a service IP available before marking as started

.gitignore, Makefile, README.md, cmd/kubectl-testkube/commands/generate/docs.go
=> docs: updated Readme and cli-docs generation

pkg/testworkflows/testworkflowprocessor/operations.go
* allow fetching artifacts from all mounted volumes, not only `/data`
=> fix: register all mounted directories for the artifacts scrapping

pkg/testworkflows/testworkflowprocessor/action/process_test.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go, pkg/testworkflows/testworkflowprocessor/processor.go
Test Workflows like:
```yaml
metadata:
name: demo-consecutive-always
spec:
steps:
- condition: always
shell: echo hello
- condition: always
shell: exit 1
- condition: always
shell: echo hello
```
were not running the `condition: always` steps in case they are after failure
=> fix: correctly handle consecutive condition: always steps

cmd/tcl/testworkflow-toolkit/commands/execute.go
* `exec` was cleared, so `exec.Id` was not pointing to the execution
=> fix: keep the execution ID for getting next one

pkg/event/kind/webhook/listener.go
=> fix: show webhook target response error output

cmd/testworkflow-init/obfuscator/obfuscator.go, cmd/testworkflow-init/obfuscator/obfuscator_test.go, cmd/testworkflow-init/orchestration/executions.go, cmd/testworkflow-init/output/printer.go
Fix problems with broken pipe
* The init process reported different number of bytes read than received from child
* Child Process received SIGPIPE
-
-
- https://github.com/kubeshop/testkube/issues/5831
=> fix: handle child process stream correctly to avoid broken pipe

cmd/testworkflow-init/constants/commands.go, cmd/testworkflow-init/orchestration/setup.go, pkg/expressions/libs/fs_test.go, pkg/expressions/libs/secret.go, pkg/expressions/libs/secret_test.go, pkg/expressions/utils.go, pkg/testworkflows/testworkflowprocessor/processor.go, pkg/testworkflows/testworkflowprocessor/secretmachine.go, pkg/testworkflows/testworkflowprocessor/secretmachine_test.go, pkg/testworkflows/testworkflowresolver/config.go
* Correctly resolve sensitive configuration (i.e. `something: 'foo'` became `"foo"` before, instead of unquoted `foo`)
* Include sensitive configuration and `secret()` calls as sensitive words
```
metadata:
name: example-sensitive
spec:
config:
something:
type: string
default: blah
sensitive: true
steps:
- shell: echo '{{ secret("example-secret", "example-key") }} {{ config.something }}'
```
```
seeeensitve-value "blah"
```
```
****ue ****ah
```
-
-
=> fix: obfuscate secret() calls, resolve sensitive config

internal/app/api/v1/testworkflowexecutions.go, pkg/repository/testworkflow/mongo.go, pkg/repository/testworkflow/mongo_integration_test.go
Use Or for same tag  for twe values and log stream errors
-
-
-
=> fix: [TKC-2583] tags OR operator for twe

pkg/testworkflows/testworkflowcontroller/logs.go, pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go
* Earlier, for every container we were retrieving the logs twice - just to ensure that we haven't fall into log rotation
* This fix will avoid additional retrieve, in most common case - when we have successfully received final step information
=> fix: avoid retrieving container logs again, when expected information is complete

pkg/testworkflows/testworkflowcontroller/watchinstrumentedpod.go
* when the service has `timeout: 1s` and it fails, "Stop Services" was getting stuck
* modified to not hang depending on the state
=> fix: don't fetch logs for timed out services

cmd/testworkflow-toolkit/commands/clone.go
=> feat: [TKC-2342] clone logs

cmd/testworkflow-init/data/expressions.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go, pkg/testworkflows/testworkflowresolver/apply_test.go
* resolve properly status values, like `passed` or `status`
* earlier, it was not able to resolve it, as undetermined steps were not treat as succeed
* now, as long as the step is not failed, it's considered passed yet
```yaml
metadata:
name: example
spec:
steps:
- shell: exit 0
- condition: always
run:
shell: |
echo {{ passed }}
```
=> fix: determine dynamic status correctly in the execution's expressions

cmd/api-server/main.go, cmd/kubectl-testkube/commands/common/errors.go, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/init.go, cmd/testworkflow-init/obfuscator/obfuscator.go, pkg/agent/agent.go
The idea is to clean long TTL migration jobs when they exist and we're trying to recreate them. 
-
-
-
=> fix: clean completed migration job before reinitialize on-prem demo

api/v1/testkube.yaml, pkg/api/v1/testkube/model_pod_security_context.go, pkg/mapper/testworkflows/kube_openapi.go, pkg/mapper/testworkflows/openapi_kube.go
* recognize `pod.securityContext.fsGroup` in OpenAPI
* earlier it was used, but i.e. not displayed in the UI (as OpenAPI didn't recognize it)
=> fix: allow passing FSGroup to PodSecurityContext in OpenAPI

cmd/testworkflow-toolkit/artifacts/cloud_uploader.go, pkg/cloud/data/testworkflow/output.go
As per Golang's [**Request documentation**](https://pkg.go.dev/net/http#Request):
```go
// For client requests, a value of 0 with a non-nil Body is
// also treated as unknown.
ContentLength int64
```
Because of that, we need to ensure the `request.Body` is `nil` when the `ContentLength` is `0` - otherwise `Content-Length` header won't be sent.
- https://linear.app/kubeshop/issue/TKC-2680/[canton-of-geneva]-error-if-an-artifact-is-empty
=> fix: send Content-Length: 0 to the Object Storage when file is empty

build/kind/entrypoint.sh, build/kind/kind.Dockerfile
=> fix: don't create Kind cluster twice

.github/workflows/release-dev.yaml, .github/workflows/release.yaml, api/v1/testkube.yaml, build/kind/entrypoint.sh, build/kind/kind.Dockerfile, cmd/api-server/main.go, internal/app/api/v1/handlers.go, internal/app/api/v1/server.go, internal/config/config.go, pkg/api/v1/testkube/model_server_info.go, pkg/telemetry/payload.go, pkg/telemetry/sender_sio.go
Pass docker image version for telemetry and server info
-
-
-
=> feat: [TKC-2684] docker image version

pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/testworkflows/testworkflowcontroller/notifier.go
Failure of optional steps is now marking the whole execution to fail.
* It should not fail execution, if optional step fails
```yaml
metadata:
name: optional-failure
spec:
steps:
- optional: true
shell: exit 1
```
=> fix: handle optional steps

pkg/repository/testworkflow/mongo.go
* Earlier, it was putting empty array only on `Insert`, now it will add it in `Update` too
* We haven't been using `repo.Update` before decoupling execution creation
=> fix: set empty `reports` on Execution update too

.github/workflows/release-dev.yaml, .github/workflows/release.yaml, build/kind/entrypoint.sh, build/kind/kind.Dockerfile, cmd/kubectl-testkube/commands/common/flags.go
- add default cloud url to docker image
- use default value for agent uri in docker
-
-
-
=> fix: [TKC-2774] use default cloud url

cmd/tcl/testworkflow-toolkit/commands/services.go, cmd/testworkflow-init/main.go
* Add missing correlation group for services
* So they can be gracefully cleaned up, and logs fetched
* Save the state file (with output) before execution
* So Toolkit can always access service IPs
=> fix: detecting service IPs and fetching logs

cmd/tcl/testworkflow-toolkit/commands/parallel.go, cmd/tcl/testworkflow-toolkit/commands/services.go, pkg/testworkflows/executionworker/registry/controllers.go
* Provide workflow name down
* Simplify artifacts path for parallel workers (`<ref>/<index>` instead of `<ref>/<ref>-<index>`)
* Ensure de-registering controllers in Execution Worker works fine (encountered issue once)
=> fix: provide workflow name to parallel workers, so it will properly build path for artifacts

cmd/testworkflow-init/commands/setup.go, pkg/testworkflows/testworkflowprocessor/action/actiontypes/lite/utils.go, pkg/testworkflows/testworkflowprocessor/action/actiontypes/utils.go, pkg/testworkflows/testworkflowprocessor/action/group.go, pkg/testworkflows/testworkflowprocessor/action/group_test.go, pkg/testworkflows/testworkflowprocessor/action/optimize.go, pkg/testworkflows/testworkflowprocessor/action/process_test.go, pkg/testworkflows/testworkflowprocessor/constants/constants.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go
* Handle container optimization (merging containers) for default images properly
```yaml
spec:
system:
pureByDefault: true
steps:
- run:
image: curlimages/curl:latest
- shell: echo hello
```
Fails with `/.tktw-bin/sh` not found
=> fix: handle container optimization for default images when pure shell script is run at last

cmd/kubectl-testkube/commands/common/client.go
Add User-Agent header when using CLI to send requests to API.
-
-
-
=> feat: add User-Agent header in CLI when sending requests API requests

.dockerignore, .gitignore, build/_local/agent-server.Dockerfile, build/_local/testworkflow-init.Dockerfile, build/_local/testworkflow-toolkit.Dockerfile, build/_local/values.dev.tpl.yaml, docker-bake.hcl, go.mod, go.sum, pkg/event/bus/nats.go, pkg/utils/consts.go, skaffold.yaml
=> chore: reduce startup time and add skaffold

cmd/testworkflow-init/main.go, cmd/testworkflow-init/orchestration/setup.go
* Errors for container data (i.e. setting some environment variable to `{{ unknownFunc }}`) are now not displayed in the step
* This change is pushing the error information down to the first step after
```yaml
metadata:
name: example
spec:
steps:
- container:
env:
- name: XYZ
value: '{{ unknownFunc }}'
shell: echo hello
```
=> fix: assign container computation errors to the 1st step requiring it

pkg/api/v1/testkube/model_test_workflow_result_extended.go
* When there was "skipped" status determined, it was not persisted, but replaced by "aborted" with "unknown failure source" message
=> fix: set correctly group statuses on fatal error

pkg/testworkflows/testworkflowexecutor/executor.go
* avoid updating `status`
* it's already for some time ending with `metadata.resourceVersion: Invalid value: 0x0: must be specified for an update`, so likely the status in the MongoDB is enough, considering that nobody has reported it
=> fix: avoid updating TestWorkflow CRD status

cmd/debug-server/Dockerfile, contrib/executor/ginkgo/build/agent/Dockerfile, contrib/executor/k6/build/agent/Dockerfile, go.mod
Updates `go` to `1.23.2`.
Relates to https://github.com/kubeshop/testkube/issues/5905
-
-
-
=> chore: Bump Go to 1.23

.github/workflows/release-dev.yaml, .github/workflows/release.yaml
=> ci: update certificate for signing MSI

cmd/kubectl-testkube/commands/common/client.go, cmd/kubectl-testkube/commands/common/flags.go, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/context/set.go, cmd/kubectl-testkube/commands/dashboard.go, cmd/kubectl-testkube/commands/docker/init.go, cmd/kubectl-testkube/commands/pro/connect.go, cmd/kubectl-testkube/commands/pro/init.go, cmd/kubectl-testkube/commands/pro/login.go, cmd/kubectl-testkube/config/data.go, cmd/kubectl-testkube/config/master.go, cmd/tcl/kubectl-testkube/devbox/README.md, pkg/cloudlogin/login.go
* Allow custom auth connector (with `--custom-auth`) and all the URLs
* Fix overriding namespace in `testkube dashboard` command
- https://linear.app/kubeshop/issue/TKC-2792/[on-prem-demo]-real-time-logs-and-artifacts-download-not-working
=> fix: allow custom URLs and auth connector to support our Skaffold setup

.github/workflows/release-dev.yaml, .github/workflows/release.yaml
seems like GoReleaser fails to build kubectl-testkube binary now ([job](https://github.com/kubeshop/testkube/actions/runs/11681561402/job/32527400173)). There are no noticeable changes though compared to previous tag ([here](https://github.com/kubeshop/testkube/compare/v2.1.56...v2.1.57)) - except it's now GoReleaser v2.4.4-pro, when earlier it was v2.3.2-pro.
```
/opt/hostedtoolcache/goreleaser-action/2.4.4-pro/x64/goreleaser release -f .goreleaser.yml
• by using this software you agree with its EULA, available at https://goreleaser.com/eula
• running goreleaser v2.4.4-pro
• loading environment variables
• using token from $GITHUB_TOKEN
• getting and validating git state
• git state                                      commit=130be440378c16d656017003c3adbea59834385c branch=HEAD …
```
=> fix: downgrade GoReleaser Pro to v2.3.2, as it fails to build in v2.4.4

pkg/expressions/generic.go, pkg/expressions/parse.go, pkg/expressions/stdlib.go, pkg/testworkflows/testworkflowprocessor/processor.go, pkg/testworkflows/testworkflowprocessor/secretmachine.go, pkg/testworkflows/testworkflowprocessor/secretmachine_test.go, pkg/testworkflows/testworkflowresolver/config.go
```yaml
metadata:
name: example-workflow
spec:
steps:
- name: Run tests
template:
name: example-template
config:
something: '{{ secret("some-secret", "key") }}'
---
kind: TestWorkflowTemplate
metadata:
name: example-template
spec:
config:
something:
type: string
sensitive: true
steps:
- shell: echo {{ config.something }}
```
=> fix: passing secret as sensitive config

cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/crdsync.go
* Correctly detect deletion/update of template/workflow
=> fix: CRD synchronisation in the devbox

cmd/api-server/services/controlplane.go, cmd/tcl/kubectl-testkube/devbox/README.md, cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/agent.go, cmd/tcl/kubectl-testkube/devbox/devutils/cloud.go, cmd/tcl/kubectl-testkube/devbox/devutils/cluster.go, cmd/tcl/kubectl-testkube/devbox/devutils/minio.go, cmd/tcl/kubectl-testkube/devbox/devutils/mongo.go, cmd/tcl/kubectl-testkube/devbox/devutils/pods.go, cmd/tcl/kubectl-testkube/devbox/devutils/resources.go, cmd/testworkflow-toolkit/commands/artifacts.go
=> feat: add support for OSS version in devbox

pkg/imageinspector/cranefetcher.go, pkg/testworkflows/testworkflowprocessor/processor.go
* load image metadata when needed
* there was a typo: when there was group required to determine permissions, it was passing down as unneeded
* obtain image manifests in Crane for specific platform
* it was not checking for the platform
=> fix: load image metadata when needed / load platform-specific manifest with Crane fetcher

cmd/kubectl-testkube/commands/docker/init.go
* Docker Init command was fetching the latest version before it was needed, just to populate the docs
* Because of that, every `testkube` command was fetching the latest version from GitHub too
* Most critical issue - Testkube CLi executed from within air-gapped cluster was failing, as it was not able to reach GitHub
=> fix: avoid checking for latest release on GitHub with every CLI command

cmd/tcl/kubectl-testkube/devbox/devutils/crdsync.go, cmd/tcl/kubectl-testkube/devbox/devutils/resources.go
* it was not working correctly for OSS, because `resourceVersion` was missing.
* also, template was marked as created when it exists but no changes detected
=> fix: CRD synchronisation in the development tool

internal/app/api/deprecatedv1/testsuites.go
* gRPC repository for Test Suites was trying to cast filter to pointer of one structure, while actual struct (not a pointer) was passed (https://github.com/kubeshop/testkube/commit/2d1757038ff415a11e8d58740f14086404fe4d45)
* In Test Workflows we support both
* In Tests we always use pointers
* As the feature is deprecated anyway, just patched to send pointer instead
=> fix(testsuites): build execution filter properly

cmd/kubectl-testkube/commands/common/client.go, cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/config/data.go, cmd/tcl/kubectl-testkube/devbox/README.md
* it was not able to connect to provider again (as it was not using the same auth URI), so it was trying to log in again
=> fix: CLI login with custom auth URL

pkg/testworkflows/testworkflowprocessor/action/containerize.go, pkg/testworkflows/testworkflowprocessor/action/containerize_test.go, pkg/testworkflows/testworkflowprocessor/presets/processor_test.go
* It was incorrectly using default image when the container had pure operation merged forward
```yaml
metadata:
name: example
spec:
steps:
- delay: 1s
run:
image: curlimages/curl:latest
shell: curl -XGET http://testkube.io/
```
It will run both commands with the default init image, instead of `curlimages/curl:latest`
=> fix: merge general-use steps properly

internal/graphql/services/executors.go, internal/graphql/services/executors_test.go, pkg/api/v1/testkube/model_event_extended.go, pkg/api/v1/testkube/model_event_extended_test.go, pkg/event/bus/nats.go, pkg/event/emitter.go, pkg/logs/client/interface.go, pkg/logs/events.go
=> fix: conflicting subscription name with control plane

cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/grafana.go, cmd/tcl/kubectl-testkube/devbox/devutils/prometheus.go
* Add Prometheus / Grafana set to the Development Tool
* It's automatically integrated and started
* Grafana is exposed on random port displayed in DevBox log
* Uses `/metrics` endpoint from the Agent
* Works both for Agent connected to the Control Plane and OSS
=> feat: add Prometheus/Grafana to Development Tool

cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/diagnostics.go, cmd/kubectl-testkube/commands/diagnostics/install.go, cmd/kubectl-testkube/commands/diagnostics/license.go, pkg/diagnostics/validators/license/errors.go, pkg/ui/select.go
=> feat: detect namespace of enterprise installation

cmd/testworkflow-init/data/client.go, pkg/credentials/repository.go
* Otherwise, images that don't use `credential()`, but have incorrect certificates (i.e. in images) for Cloud connection, will fail)
=> fix: make the Cloud connection from the Init Process lazy (connect only when needed)

cmd/testworkflow-init/main.go, cmd/testworkflow-init/orchestration/executions.go, cmd/testworkflow-init/orchestration/processes.go, pkg/api/v1/testkube/model_test_workflow_step_status_extended.go
* Kill nested processes correctly
* Set properly Test Workflow Execution status when step timeout happens
* Make step timeout graceful - allow retries and continuing
- https://linear.app/kubeshop/issue/TKC-3004/step-timeout-the-execution-continues-after-timeout-workflow-is-stuck
=> fix(TKC-3004): kill nested processes on timeout properly

pkg/testworkflows/testworkflowresolver/apply.go, pkg/testworkflows/testworkflowresolver/apply_test.go
* merge templates from last to first, as each other should be overwritten by the latter.
- https://linear.app/kubeshop/issue/TKC-2934
=> fix(TKC-2934): fix order of merging the templates

cmd/api-server/main.go, cmd/api-server/services/controlplane.go, cmd/tcl/kubectl-testkube/devbox/devutils/runneragent.go, pkg/runner/runner.go, pkg/runner/service.go, pkg/testworkflows/testworkflowexecutor/executor.go, pkg/testworkflows/testworkflowexecutor/scheduler.go
* handle Test Workflow adjustments on the runner level
=> feat: support inlined global template in the runner

contrib/executor/cypress/build/agent/Dockerfile.cypress13
fix this issue with amd64 build:
```
0.551 Err:5 https://dl.google.com/linux/chrome/deb stable InRelease
│ 0.551   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 32EE5355A6BC6E42
```
-
-
-
=> fix: update cypress 13 base image

pkg/testworkflows/testworkflowexecutor/prepared.go
* Use tags from request even when there is none defined in the TestWorkflow's spec
=> fix: use execution tags from request if provided

pkg/testworkflows/testworkflowexecutor/executor.go
* TestWorkflowExecutor was using non-existing pro context to determine flow, so finally the scheduling was mixed - part in new and part in old flow
=> fix: condition for determining new flow in the executor

pkg/runner/executionlogswriter.go
* On execution save error, the logs were tried to be saved multiple times (except they were successfully transferred already)
=> fix: mark logs as saved properly

cmd/testworkflow-toolkit/artifacts/junit_post_processor.go
* do not fail the artifacts save when JUnit processing fails
- https://linear.app/kubeshop/issue/TKC-3212/junit-report-parsing-failure-prevents-artifact-saving
=> fix(TKC-3212): avoid failing the artifacts save when JUnit processing failed

.github/workflows/lint.yaml, pkg/resourcepattern/resourcepattern.go, pkg/resourcepattern/resourcepattern_test.go
* Solve the problem when multiple GitOps Agents are based on the same data source (i.e. even rolling update) with different patterns (like `<name>` and `prefix-<name>` may go all forward through `prefix-prefix-<name>`, up to i.e. `prefix-prefix-prefix-prefix-prefix-prefix-prefix-prefix-<name>`
=> fix: avoid circular resolution across different resource patterns

cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/agent.go, cmd/tcl/kubectl-testkube/devbox/devutils/cloud.go, internal/app/api/v1/testworkflows.go, internal/app/api/v1/testworkflowtemplates.go, pkg/newclients/testworkflowclient/cloud.go, pkg/newclients/testworkflowclient/interface.go, pkg/newclients/testworkflowclient/kubernetes.go, pkg/newclients/testworkflowclient/mock_interface.go, pkg/newclients/testworkflowtemplateclient/cloud.go, pkg/newclients/testworkflowtemplateclient/interface.go, pkg/newclients/testworkflowtemplateclient/kubernetes.go, pkg/newclients/testworkflowtemplateclient/mock_interface.go
* Add `--disable-cloud-storage` flag to `testkube devbox` command for debugging
* Fix building ownership for auto-created secrets
* https://linear.app/kubeshop/issue/TKC-3318/creating-workflow-with-repo-credentials-500-secrets-arent-created
=> fix(TKC-3318): auto-secrets creation

pkg/utilization/instrument.go, pkg/utilization/utilisation.go
Nil pointer access if a process cannot be scraped
-
-
-
=> fix: nil pointer access errors when recording metrics

cmd/testworkflow-toolkit/env/client.go
Temporary fix so Workflows can successfully save metrics after each Step by skipping TLS verification
-
-
-
=> fix: temp fix an issue in workflows where metrics scraping fails due to tls verify

pkg/utilization/instrument.go, pkg/utilization/instrument_test.go
Various Kubernetes clusters can have various block devices, this PR fixes accounting for various block devices
-
-
-
=> fix: disk metrics calculation for various block devices

cmd/api-server/main.go, pkg/runner/globaltemplate.go, pkg/runner/runner.go, pkg/runner/service.go
- https://linear.app/kubeshop/issue/TKC-3368/content-from-global-template-not-replicated-in-testworkflow
=> fix(TKC-3368): use global template in new architecture when it's not inline too

pkg/runner/agent.go, pkg/runner/runner.go, pkg/testworkflows/executionworker/executionworkertypes/interface.go
* avoid marking execution as aborted due to existing job, when the execution was successfully started and working
=> fix: safely handle redundant execution start

pkg/repository/testworkflow/mongo.go
* block reassigning running/paused executions
=> fix: allow assigning only queued executions

pkg/cloudlogin/login.go
* When using `testkube login`, automatically close browser window after logged in
=> feat: automatically close login window after successful auth

cmd/kubectl-testkube/commands/testworkflows/executions.go
* It was trying to use execution name for logs endpoint, which doesn't support it.
=> fix: getting execution logs with `get <name>`

cmd/kubectl-testkube/commands/agents/create.go, cmd/kubectl-testkube/commands/agents/install.go, cmd/kubectl-testkube/commands/agents/utils.go, pkg/cloud/client/agents.go
* Runner created without additional options has to be directly called by `id` or `name` (`--target name=my-runner`)
* Runner created with `--group <name>` option will be taken in account only when execution's `--target group=<name>`
* Runner created with `--global` flag will be taken in account for all executions
=> feat: add global/independent/grouped runners

pkg/api/v1/client/interface.go, pkg/api/v1/client/testworkflow.go
* The `/pause` and `/resume` endpoints were not exposed in the API Client
=> fix: add missing Pause/Resume methods to API Client

pkg/mapper/secrets/mapper.go, pkg/mapper/testworkflows/kube_openapi.go
* It's a pointer. It shouldn't be empty, but apparently, it happens.
=> fix: don't expect ManagedFields[n].Time to be existing

cmd/testworkflow-init/orchestration/setup.go
* earlier, if `container.env[k].value` contained `credential()` function - it thrown error
=> fix: using credentials in environment variables

internal/app/api/v1/labels_tags.go, pkg/repository/testworkflow/mongo.go
* perform the grouping on MongoDB
=> fix: avoid getting all the records from the database when fetching list of the execution tags

pkg/expressions/parse_test.go, pkg/expressions/tokenize.go
* add support for simple single-quoted script
* it's useful for cases where you need to pass some string with double quotes, like `map(items, '_.value + "text"')` vs `map(items, "_.value + \"text\"")`
* it's not supported inside of arrays or objects, same as variables (as they are fully parsed as JSON)
=> feat: support single quoted strings in the expressions

cmd/kubectl-testkube/commands/pro/login.go, cmd/tcl/kubectl-testkube/devbox/README.md
* add `tk login [apiUrl]` command to automatically discover all required public URLs
=> feat: add `tk login [apiUrl]` command to automatically discover all required public URLs

cmd/testworkflow-init/data/client.go, cmd/testworkflow-toolkit/env/client.go, pkg/controlplaneclient/client.go, pkg/controlplaneclient/execution_self.go
* there was only execution ID before, that would not be enough to build link back
=> fix: add missing workflow name to the execution's running context

cmd/kubectl-testkube/commands/agents/create.go
=> fix: add --group and --global arguments to `tk create runner` command

pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* When there is global `pod.imagePullSecrets`, use it for `services` and `parallel` automatically
=> feat: pass execution's imagePullSecrets down to services/parallel automatically

pkg/runner/service.go
* when the execution is not found in the cluster, yet it's still marked as on-going, try to recover based on existing data in the DB
* it may fail due to MongoDB revoked the data after it has accepted
* it may fail because of some restart during one of the procedures
* it may fail because of cluster manipulation
* it may fail due to various different reasons
=> fix: improve healing executions when they are not found in the cluster

cmd/api-server/main.go, cmd/api-server/services/executionworker.go, cmd/tcl/testworkflow-toolkit/spawn/utils.go, pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/runner/service.go, pkg/testworkflows/executionworker/controller/controller.go, pkg/testworkflows/executionworker/controller/watchers/commons.go, pkg/testworkflows/executionworker/controller/watchers/executionstate.go, pkg/testworkflows/executionworker/controller/watchers/job.go, pkg/testworkflows/executionworker/controller/watchers/jobevents.go, pkg/testworkflows/executionworker/controller/watchers/pod.go, pkg/testworkflows/executionworker/controller/watchers/podevents.go, pkg/testworkflows/executionworker/controller/watchinstrumentedpod.go, pkg/testworkflows/executionworker/kubernetesworker/interface.go, pkg/testworkflows/executionworker/kubernetesworker/worker.go
* add more detailed log for debugging executions considered aborted
* it will be available in the Agent's logs
* it includes pod, job & events information that were used for considering the "aborted" status
=> feat: add more detailed log for debugging executions considered aborted

contrib/executor/k6/examples/k6-test-failing-script.js, contrib/executor/k6/pkg/runner/runner_integration_test.go, pkg/diagnostics/validators/license/client_test.go, pkg/logs/events_test.go, pkg/logs/service.go
=> fix: automated tests

pkg/api/v1/testkube/model_test_workflow_extended.go, pkg/api/v1/testkube/model_test_workflow_extended_test.go, pkg/api/v1/testkube/model_test_workflow_template_extended.go
* `json.Marshal` of maps is not guaranteed to provide the same order even for single map
=> fix: do stable comparison of TestWorkflow

pkg/runner/service.go, pkg/testworkflows/executionworker/controller/watchinstrumentedpod.go
* when the watching is finished in strange way, do not try to "heal aborted"
* add more logs for edge cases
=> fix: handle more gracefully watcher error

cmd/kubectl-testkube/commands/agents/create.go, cmd/kubectl-testkube/commands/agents/delete.go, cmd/kubectl-testkube/commands/agents/enable.go, cmd/kubectl-testkube/commands/agents/get.go, cmd/kubectl-testkube/commands/agents/install.go, cmd/kubectl-testkube/commands/agents/update.go, cmd/kubectl-testkube/commands/install.go
* enable the commands in `-h`/`--help` without `EXPERIMENTAL` flag
=> feat: enable agent commands without EXPERIMENTAL flag

cmd/kubectl-testkube/commands/testworkflows/run.go, pkg/runner/runner.go, pkg/testworkflows/executionworker/controller/controller.go, pkg/testworkflows/executionworker/kubernetesworker/worker.go
- store and show temp logs to support abnormally terminated execution pods
- tune log watching for delayed test jobs
-
-
-
=> fix: [TKC-3219] show temp logs to support abnormally terminated execution pods

cmd/kubectl-testkube/commands/common/helper.go, cmd/kubectl-testkube/commands/pro/login.go, cmd/kubectl-testkube/config/data.go, pkg/cloudlogin/login.go
* attach by default service URLs (so runners could be installed in different namespaces)
* correctly show errors on callback server (when address is already in use)
* automatically detect address conflict because of demo profile (to automatically replace the callback port)
=> fix: improve demo profile usage

cmd/api-server/main.go, cmd/api-server/services/executionworker.go, cmd/tcl/devbox-mutating-webhook/main.go, cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/agent.go, cmd/tcl/kubectl-testkube/devbox/devutils/cluster.go, cmd/tcl/kubectl-testkube/devbox/devutils/interceptor.go, cmd/tcl/kubectl-testkube/devbox/devutils/namespace.go, cmd/tcl/kubectl-testkube/devbox/devutils/runneragent.go, internal/config/config.go
* add `DEFAULT_EXECUTION_NAMESPACE` to pass default execution namespace
* when it's passed, execution by default will be passed to this namespace (the agent's namespace won't be allowed, unless specified in the additional execution namespaces)
* support it in `tk dev` command (with `-N/--execution-namespace` parameter)
=> feat: allow using different default namespace for execution

cmd/kubectl-testkube/commands/agents/install.go, cmd/kubectl-testkube/commands/agents/utils.go
* use Helm Chart from https://github.com/kubeshop/helm-charts/pull/1016
* allow using different namespace for execution with `-N`/`--execution-namespace`
=> feat: use testkube-runner Helm Chart for `testkube install runner`

pkg/expressions/call.go, pkg/expressions/parse_test.go
* ensure resolved arguments to maximum before calling a function itself
* this is to avoid having `FinalizerFail` on the function, while the arguments are still not resolved
- https://linear.app/kubeshop/issue/TKC-3513
=> fix(TKC-3513): handle properly deep resolution in function arguments (built-in `passed` variable)

cmd/tcl/testworkflow-toolkit/commands/kill.go, cmd/tcl/testworkflow-toolkit/commands/parallel.go, cmd/tcl/testworkflow-toolkit/commands/services.go, cmd/testworkflow-toolkit/artifacts/internalartifactstorage.go, pkg/api/v1/testkube/model_test_workflow_result_extended.go, pkg/runner/runner.go, pkg/runner/service.go, pkg/testworkflows/executionworker/controller/controller.go, pkg/testworkflows/executionworker/kubernetesworker/worker.go
* If the execution crashes (or is aborted), while there are ongoing parallel steps or services, let Agent save them
Just run this:
```yaml
metadata:
name: example-services-crash
spec:
services:
test:
shell: echo heeeloooooo!
steps:
- shell: sleep 10
- shell: echo {{ unknown_variable }}
```
Run this, and abort while the parallel steps will be running:
```yaml
metadata:
name: example-parallel-crash
spec:
steps:
- parallel:
count: 5
steps:
- shell: echo hello {{ index }}
- shell: sleep 60000
```
=> feat: recover missing service/parallel step logs in case of crash

pkg/imageinspector/cranefetcher.go, pkg/imageinspector/cranefetcher_test.go, pkg/imageinspector/inspector.go, pkg/imageinspector/inspector_test.go
support custom default registry names without dot by switching to ExtractRegistry
-
-
-
=> fix: custom default registry name

cmd/api-server/main.go, cmd/tcl/kubectl-testkube/devbox/command.go, cmd/tcl/kubectl-testkube/devbox/devutils/agent.go, cmd/tcl/kubectl-testkube/devbox/devutils/namespace.go, go.mod, internal/config/config.go, pkg/controller/testexecutionexecutor.go, pkg/controller/testsuiteexecutionexecutor.go, pkg/controller/testworkflowexecutionexecutor.go, pkg/controller/testworkflowexecutionexecutor_test.go
These changes add Kubernetes controllers for the `TestWorkflowExecution` CRD as well as the `TestSuiteExecution` and `TestExecution` legacy CRDs.
The controllers mimic the effect of the `testkube-operator` on the CRDs, however as they are integrated into the agent they are able to call the execution functions directly rather than having to go via the API.
Initialisation of the controllers is behind a new `ENABLE_K8S_CONTROLLERS` environment variable as it would not be desirable to have these controllers running at the same time as the `testkube-operator`.
Additionally the Agent will now also attempt to clean up legacy `CronJob` resources when using the newer cronjob scheduler. This is a duplication of the existing logic in the operator, however the two should not conflict and enables …
=> feat: Add Execution CRD control to Agent

cmd/tcl/testworkflow-toolkit/commands/kill.go, cmd/tcl/testworkflow-toolkit/commands/parallel.go, cmd/tcl/testworkflow-toolkit/execute/execute.go, cmd/testworkflow-init/main.go, cmd/testworkflow-toolkit/artifacts/internalartifactstorage.go, cmd/testworkflow-toolkit/commands/artifacts.go, cmd/testworkflow-toolkit/commands/clone.go, cmd/testworkflow-toolkit/env/client.go
Do not fail workflow if resource metrics cannot be saved
-
-
-
=> feat: TKC-3697: do not fail workflow if resource metrics cannot be saved

cmd/testworkflow-init/instructions/emit.go, pkg/utilization/utilisation.go
Store warning in `outputs` field if resource metrics scraping/saving fails.
Example:
```
{
...
"output": [
{
"ref": "rd6cw49",
"name": "resource-metrics-warning",
"value": {
"component": "resource-metrics",
"error": "failed to record metrics",
"reason": "testing error"
}
}
]
}
```
-
-
-
=> feat: TKC-3709: store warning in test workflow execution if resource metrics fail

pkg/api/v1/client/cloud_client.go
This PR fixes TKC-3871. It prevents making requests which have two authentication mechanisms. Some object storage providers handle this gracefully, but others will fail on this.
=> fix: fix artifact double authentication

internal/app/api/v1/secret.go
Secret creation with `TestWorkflow`/`TestWorkflowTemplate` owner references failed with "kind must not be empty" error because the Kubernetes client doesn't populate type metadata fields on retrieved objects.
Implemented proper type metadata handling using the existing [crdcommon.AppendTypeMeta](https://github.com/kubeshop/testkube/blob/26413b80e61e69fcb01a1ff8470332c19b794604/internal/crdcommon/crd.go#L26) utility function to set `GroupVersionKind` on `TestWorkflow` and `TestWorkflowTemplate` objects after retrieval.
=> fix: TestWorkflow/TestWorkflowTemplate Secret Owner References [TKC-3875]

pkg/testworkflows/executionworker/controller/notifier.go
This initialisation ensures that a Control Plane can continue to send more executions to the runner and a slow to start execution does not block other executions from being scheduled to the runner.
=> fix: set executions to RUNNING on start

pkg/repository/testworkflow/interface.go, pkg/repository/testworkflow/mongo/mongo.go
Runners should be able to finish an execution from some additional edge case states.
=> fix: Allow scheduling to be finished from multiple states

pkg/api/v1/testkube/model_test_workflow_status_extended.go
These can be used to identify executions that are currently "in progress".
=> feat: Define "ongoing" statuses

pkg/mcp/api.go, pkg/mcp/client.go, pkg/mcp/server.go, pkg/mcp/tools/descriptions.go, pkg/mcp/tools/executions.go
Adds a "wait_for_executions" tool to the MCP server that waits for the specified executions to finish, helpful when launching multiple executions and wanting the agent/llm to wait 
-
-
-
=> feat: MCP wait_for_executions tool
