- docs/docs/articles/common-issues.md
close: https://github.com/kubeshop/testkube/issues/3941
-
-
-
> docs: update the s3 with IAM setup

- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/tmpl.go
> fix: use executor job template for container executor

- cmd/kubectl-testkube/commands/root.go
> fix: sync telemetry for cli

- docs/docs/test-types/executor-zap.md
> docs: update zap docs

- api/v1/testkube.yaml
See https://discord.com/channels/884464549347074049/1088559756714705067/1088571830639542343
> docs: preRunScript ignored for container executor

- api/v1/testkube.yaml
Reverts kubeshop/testkube#3968
> Revert "docs: preRunScript ignored for container executor"

- api/v1/testkube.yaml
Doc: refine schema for content.type
Aligns with
https://github.com/kubeshop/helm-charts/pull/541
-
-
-
> docs: refine schema for content.type

- pkg/telemetry/sender_sio.go
> fix: use Testkube logs for telemetry

- docs/package-lock.json
- docs/package.json
> docs: update docs dependencies

- docs/docs/articles/test-triggers.md
- docs/docs/articles/webhooks.mdx
- docs/sidebars.js
> docs: small fixes

- cmd/kubectl-testkube/commands/root.go
- pkg/api/v1/client/test.go
> fix: removed header from completion script

- docs/docs/articles/helm-chart.md
Updated docs for helm charts `global` values.
-
-
-
> docs: update docs for helm charts

- .builds-linux.goreleaser.yml
- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
- Makefile
- build/kubectl-testkube/Dockerfile
https://github.com/kubeshop/testkube/issues/1410
-
-
-
> feat: cli docker image

- .github/workflows/docusaurus.yml
- .github/workflows/lint.yaml
- .github/workflows/lint_pr.yaml
- api/v1/testkube.yaml
- docs/docs/articles/scheduling-tests.md
- internal/app/api/v1/executor.go
- internal/app/api/v1/tests.go
- internal/app/api/v1/testsource.go
- internal/app/api/v1/testsuites.go
- internal/app/api/v1/testtriggers.go
- internal/app/api/v1/webhook.go
- pkg/mapper/executors/mapper.go
- pkg/mapper/tests/kube_openapi.go
- pkg/mapper/testsources/mapper.go
- pkg/mapper/testsuites/kube_openapi.go
- pkg/mapper/testtriggers/kube_openapi.go
> feat: yaml content type

- cmd/kubectl-testkube/commands/root.go
> fix: check for nil parent

- cmd/api-server/main.go
- internal/config/config.go
- pkg/mapper/tests/openapi_kube.go
- pkg/reconciler/reconciler.go
> feat: basic reconciler

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-release.yaml
This PR removes creation of release branch in helm-charts repo to simplify release flow.
-
-
-
> ci: remove release branch creation in helm-charts repo

- cmd/kubectl-testkube/commands/config.go
- cmd/kubectl-testkube/commands/dashboard.go
- cmd/kubectl-testkube/commands/get.go
- cmd/kubectl-testkube/commands/root.go
> feat: cloud dashboard command and fixes to cloud header

- cmd/kubectl-testkube/commands/config.go
- cmd/kubectl-testkube/commands/dashboard.go
- cmd/kubectl-testkube/commands/get.go
- cmd/kubectl-testkube/commands/root.go
> feat: cloud dashboard command and fixes to cloud header (#4086)

- internal/app/api/v1/executions.go
> fix: invalid error message

- pkg/api/v1/testkube/model_execution_extended.go
- pkg/api/v1/testkube/model_test_suite_execution_extended.go
- pkg/repository/result/mongo.go
- pkg/repository/testresult/mongo.go
- pkg/utils/utils.go
> fix: escape and unescape dots

- pkg/mapper/testsuites/kube_openapi.go
- pkg/mapper/testsuites/kube_openapi_test.go
Patching test suite by YAML was losing information about steps.
-
-
-
> fix: map test suite YAML to proper update structure

- Makefile
> chore: fix local build

- cmd/api-server/main.go
Closes https://github.com/kubeshop/helm-charts/issues/556
-
-
-
> fix: check config if it is base64 before decoding it

- docs/docs/articles/creating-tests.md
> fix: add hashtag to shebang in example script

- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
> feat: add test labels to jobs and pods

- docs/docs/articles/webhooks.mdx
kubectl was complaining about the fields but did like them in camelCase.
-
-
-
> docs: update example to be appliable on copy-paste

- docs/docs/articles/webhooks.mdx
kubectl was complaining about the fields but did like them in camelCase.
-
-
-
> docs: webhooks docs example release

- docs/docs/articles/common-issues.md
Relating to https://github.com/kubeshop/testkube/issues/3965
-
-
-
> docs: add needed permissions for the S3 IAM role

- cmd/api-server/main.go
- pkg/storage/minio/minio.go
- pkg/storage/storage.go
Closes https://github.com/kubeshop/testkube/issues/3965
-
-
-
> fix: use dedicated function to test minio availability

- .github/workflows/test.yaml
> ci: fix integration tests

- docs/docs/articles/webhooks.mdx
Improved webhook documentation to give clarity.
> feat: improved webhooks.mdx and added section on how to develop and test

- cmd/api-server/main.go
- pkg/reconciler/reconciler.go
> fix: reconciler scraper

- test/suites/staging-testsuite.json
Removed from integration testsuite, will be run seperately (parametrizaiton on test run)
https://github.com/kubeshop/testkube/pull/4186
https://github.com/kubeshop/helm-charts/pull/583
https://github.com/kubeshop/testkube-dashboard/pull/785
> feat: dashboard-e2e-tests - integration testsuite

- cmd/api-server/main.go
- internal/app/api/v1/server.go
> fix: start telemetry async

- docs/docs/articles/artifacts-storage.md
- docs/docs/articles/helm-chart.md
- internal/config/config.go
- pkg/envs/variables.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/executor/scraper/factory/factory.go
> feat: compress artifacts feature

- contrib/container/pytest/Dockerfile
- contrib/container/pytest/README.md
- contrib/container/pytest/container-executor-pytest.yaml
- contrib/container/pytest/failed_sample.py
- contrib/container/pytest/passed_sample.py
- contrib/container/pytest/pytest_test.yaml
- contrib/container/pytest/test_sample.py
> feat: pytest executor

- pkg/telemetry/telemetry.go
> feat: disable analytics.testkube.io calls

- install.sh
Update install script for Darwin
-
-
-
> fix: update install script

- install.sh
> fix: update install script (#4209)

- api/v1/testkube.yaml
- cmd/api-server/main.go
- internal/app/api/v1/handlers.go
- internal/app/api/v1/server.go
- internal/config/config.go
- pkg/api/v1/testkube/model_server_info.go
> feat: helm chart version

- contrib/container/pytest/README.md
- contrib/executor/jmeter/pkg/parser/xjtl.go
- contrib/executor/jmeter/pkg/parser/xjtl_test.go
- contrib/executor/jmeter/pkg/runner/runner.go
- docs/docs/articles/creating-tests.md
- pkg/api/v1/testkube/model_variable_type_extended.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/tmpl.go
Fix #4218 
Usage:
{{- range $key, $value := .Variables }}
{{ if eq ($value.Type_ | vartypeptrtostring) "basic" }}
- name: TEST
value: "TEST"
{{- end }}
{{- end }}
-
-
-
> feat: tostring method

- cmd/kubectl-testkube/commands/telemetry/disable.go
- cmd/kubectl-testkube/commands/telemetry/enable.go
- pkg/README.md
> fix: switch to warning on telemetry error

- api/v1/testkube.yaml
- contrib/executor/cypress/pkg/runner/cypress.go
- pkg/api/v1/testkube/model_execution_status.go
> fix: more cypress statuses

- internal/app/api/v1/testsuites.go
> fix: added perf debug checkpoints for list executions

- pkg/executor/agent/agent.go
> fix: start end test indicator in logs

- pkg/reconciler/reconciler.go
> fix: skip empty step

- docs/docs/articles/deploying-in-aws.md
> fix: add aws s3 bucket examples

- docs/docs/test-types/executor-pytest.mdx
- docs/sidebars.js
> fix: pytest docs

- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor_test.go
> fix: add ci=1 for all jobs

- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/logs.go
Closes https://github.com/kubeshop/testkube/issues/3801
-
-
-
> fix: streaming logs not working

- cmd/kubectl-testkube/commands/debug.go
- cmd/kubectl-testkube/commands/debug/info.go
- contrib/executor/cypress/pkg/runner/cypress.go
- pkg/api/v1/testkube/model_execution_result_extended.go
> fix: debug command and cypress showing failed steps

- api/v1/testkube.yaml
- cmd/api-server/main.go
- docs/docs/articles/webhooks.mdx
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/events.go
- pkg/agent/events_test.go
- pkg/agent/logs_test.go
- pkg/api/v1/testkube/model_event.go
- pkg/event/emitter.go
- pkg/event/emitter_integration_test.go
- pkg/event/emitter_test.go
- pkg/event/kind/slack/loader.go
- pkg/event/kind/slack/loader_test.go
- pkg/slack/slack.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> feat: envs vars for webhook

- contrib/executor/k6/pkg/runner/runner.go
- contrib/executor/k6/pkg/runner/runner_test.go
> fix: use regexp for checks testing

- pkg/agent/agent.go
> feat: hotfix pass org and env to agent

- test/cypress/executor-tests/cypress-12/cypress/e2e/smoke.cy.js
- test/cypress/executor-tests/cypress-12/cypress/e2e/smoke2.cy.js
- test/cypress/executor-tests/cypress-without-envs/cypress/e2e/smoke-without-envs-2.cy.js
- test/cypress/executor-tests/cypress-without-envs/cypress/e2e/smoke-without-envs.cy.js
extended for: https://github.com/kubeshop/testkube/issues/4281
> feat: Cypress test - multi files case

- api/v1/testkube.yaml
- cmd/kubectl-testkube/commands/templates/common.go
- cmd/kubectl-testkube/commands/templates/create.go
- cmd/kubectl-testkube/commands/templates/delete.go
- cmd/kubectl-testkube/commands/templates/get.go
- cmd/kubectl-testkube/commands/templates/update.go
- cmd/kubectl-testkube/commands/testsources/create.go
- cmd/kubectl-testkube/commands/testsources/update.go
- cmd/kubectl-testkube/commands/webhooks/create.go
- cmd/kubectl-testkube/commands/webhooks/update.go
- docs/docs/articles/templates.mdx
- docs/docs/articles/webhooks.mdx
- docs/docs/cli/testkube_create.md
- docs/docs/cli/testkube_create_testsource.md
- docs/docs/cli/testkube_create_webhook.md
- docs/docs/cli/testkube_delete.md
- docs/docs/cli/testkube_get.md
- docs/docs/cli/testkube_update_testsource.md
- docs/docs/cli/testkube_update_webhook.md
- pkg/api/v1/testkube/model_webhook.go
- pkg/api/v1/testkube/model_webhook_create_request.go
- pkg/api/v1/testkube/model_webhook_update_request.go
- pkg/event/kind/webhook/listener.go
> feat: support golang template for webhook uri

- cmd/kubectl-testkube/config/config_test.go
- contrib/executor/zap/pkg/runner/runner_test.go
- pkg/cloud/client/client_mock_test.go
- pkg/repository/storage/mongo.go
> chore: remove refs to deprecated io/ioutil

- cmd/api-server/main.go
- internal/app/api/v1/server.go
- internal/app/api/v1/testsuites.go
- pkg/event/bus/nats.go
- pkg/scheduler/service.go
- pkg/scheduler/testsuite_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> fix: improve abortion check to use nats events

- cmd/kubectl-testkube/commands/common/cloudcontext.go
> fix: show cli context

- contrib/executor/cypress/pkg/runner/cypress.go
- pkg/reconciler/reconciler.go
> fix: use multiple junit reports for cypress

- pkg/event/kind/cdevent/listener_test.go
- pkg/mapper/cdevents/mapper.go
- pkg/mapper/cdevents/mapper_test.go
> fix: adjust cdevents

- contrib/executor/jmeterd/pkg/slaves/client.go
> fix: change jmeterd docker versions

- contrib/executor/jmeterd/Makefile
- contrib/executor/jmeterd/pkg/slaves/client.go
> fix: typo in jmeterd slave image

- pkg/event/kind/cdevent/listener.go
- pkg/mapper/cdevents/mapper.go
> feat: cd event log output

- internal/app/api/v1/executions_test.go
- pkg/executor/client/interface.go
- pkg/executor/client/job.go
- pkg/executor/client/mock_executor.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/executor/containerexecutor/logs.go
- pkg/scheduler/test_scheduler.go
> fix: remove duplicated code executor.ExecuteSync

- pkg/executor/client/job.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/reconciler/reconciler.go
- pkg/triggers/watcher.go
Fix #4204 
Fix #2187 
Fix #4275 
-
-
-
> fix: update execution status in watcher

- config/executors.json
- contrib/executor/jmeterd/examples/gitflow/README.md
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/slaves/client.go
- contrib/executor/jmeterd/pkg/slaves/interface.go
- contrib/executor/jmeterd/pkg/slaves/meta.go
- contrib/executor/jmeterd/pkg/slaves/meta_test.go
- contrib/executor/jmeterd/pkg/slaves/utils.go
- contrib/executor/jmeterd/pkg/slaves/utils_test.go
Refactor jmeterd slaves module and add unit tests
-
-
-
> feat: refactor jmeterd slaves module

- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-release.yaml
- goreleaser_files/.goreleaser-docker-build-executor-jmeterd-commit-only.yml
> ci: add arm64

- internal/app/api/metrics/metrics.go
> feat: add labels to count metrics

- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
> feat: support dirs for soap, postman, curl

- docs/docs/test-types/executor-artillery.mdx
- docs/docs/test-types/executor-curl.mdx
- docs/docs/test-types/executor-cypress.mdx
- docs/docs/test-types/executor-gradle.md
- docs/docs/test-types/executor-jmeter.md
- docs/docs/test-types/executor-k6.mdx
- docs/docs/test-types/executor-kubepug.md
- docs/docs/test-types/executor-maven.md
- docs/docs/test-types/executor-playwright.md
- docs/docs/test-types/executor-soapui.md
- docs/docs/test-types/executor-zap.md
> docs: fix default commands format

- cmd/api-server/main.go
- internal/app/api/metrics/metrics.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/scheduler/service.go
- pkg/scheduler/testsuite_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> feat: metric uri

- pkg/api/v1/testkube/model_test_suite_execution_extended.go
> fix: batch output clean

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_test_suite_execution_extended.go
- pkg/repository/testresult/mongo.go
* fix: do not store output in test suite execution result
* fix: clean execution result in the BatchResults as well
* fix: add apis spec note and check for nil
-
-
-
> fix: do not store output in test suite execution result (#4409)

- docs/sidebars.js
> docs: add sp to sidebars

- api/v1/testkube.yaml
- cmd/api-server/main.go
- cmd/kubectl-testkube/commands/common/render/common.go
- cmd/kubectl-testkube/commands/common/render/obj.go
- cmd/kubectl-testkube/commands/root.go
- cmd/kubectl-testkube/commands/tests/executions.go
- cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
- cmd/kubectl-testkube/commands/tests/renderer/test_obj.go
- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/commands/testsources/renderer/testsource_obj.go
- cmd/kubectl-testkube/commands/testsuites/common.go
- cmd/kubectl-testkube/commands/testsuites/renderer/execution_obj.go
- cmd/kubectl-testkube/commands/testsuites/renderer/testsuite_obj.go
- cmd/kubectl-testkube/commands/testsuites/run.go
- cmd/kubectl-testkube/commands/testsuites/watch.go
- config/slack-template.json
- internal/app/api/v1/handlers.go
- internal/app/api/v1/server.go
- pkg/api/v1/testkube/model_server_info.go
- pkg/event/kind/slack/loader.go
- pkg/event/kind/slack/loader_test.go
- pkg/slack/slack.go
> feat: slack dashboard uri

- .github/workflows/docker-build-develop.yaml
> ci: fix goreleaser build

- docs/docs/articles/deploying-in-aws.md
- docs/docs/test-types/prebuilt-executor.md
> docs: update

- docs/docs/articles/getting-started-overview.md
> docs: update installation video with cloud

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-release.yaml
> ci: fix cache

- Makefile
- contrib/executor/gradle/README.md
- contrib/executor/gradle/pkg/runner/runner.go
https://github.com/kubeshop/testkube/issues/4456
-
-
-
> feat: evaluate environment variables in the args of gradle

- pkg/executor/client/job.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/triggers/watcher.go
> fix: combine error messages

- docs/docs/articles/getting-started-overview.md
Minor fix to resolve broken link when opening Getting Started Page for the firs time.
- N/A
- Changed link
- Changed link
> [Docs] Getting started - Fix Step 1 link

- pkg/executor/client/job.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/repository/result/mongo.go
> fix: exit code and mongo transaction

- docs/docs/articles/deploying-from-private-registries.md
> docs: guide on how to deploy TK from private registry

- pkg/api/v1/client/test.go
> fix: fixing test update cli cloud command

- .github/workflows/test.yaml
> ci: fix kubepug installation

- docs/docs/articles/cd-events.md
- docs/docs/articles/logging.md
- docs/docs/articles/slack-integration.md
- docs/docs/test-types/executor-artillery.mdx
- docs/docs/testkube-cloud/articles/testkube-oss.md
- docs/sidebars.js
> docs: Testkube OSS page and additional screenshot updates

- contrib/executor/postman/build/agent/Dockerfile
> fix: add npm report permissions

- .github/workflows/docker-build-develop.yaml
- contrib/executor/k6/build/agent/Dockerfile
> feat: Update k6s executor image

- docs/docs/articles/templates.mdx
> docs: renamed template crd example name to job-template

- pkg/repository/result/mongo.go
- pkg/repository/testresult/mongo.go
* Make `$project`ion in aggregate to avoid processing too many data
* `$lookup` later the full documents based on IDs
It's performing well both with database with indexes and without.
Besides this improvement, I don't think that we are able to improve it further without creating indexes, but that would require a mechanism for MongoDB migrations. 
As an example, when there are `testsuite.name: hashed`, `starttime: -1` and `endtime: -1` indexes, we are able to get to <150ms for test suite executions query on demo.testkube.dev:
```js
db.getSiblingDB("testkube").aggregate([
{"$documents": [{"name": "asdf7"}, {"name": "dev-suite"}, {"name": "empty-test-suite"}, {"name": "executor-artillery-smoke-tests"}, {"name": "executor-container-curl-smoke-tests"}, {"name": …
```
> feat: speed up aggregates with projection and _id $lookups

- contrib/executor/artillery/pkg/runner/artillery.go
- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/cypress/pkg/runner/cypress.go
- contrib/executor/ginkgo/pkg/runner/runner.go
- contrib/executor/gradle/pkg/runner/runner.go
- contrib/executor/jmeter/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/k6/pkg/runner/runner.go
- contrib/executor/kubepug/pkg/runner/runner.go
- contrib/executor/maven/pkg/runner/runner.go
- contrib/executor/playwright/pkg/runner/playwright.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
- contrib/executor/tracetest/pkg/runner/runner.go
- contrib/executor/zap/pkg/runner/runner.go
> fix: ignore post script error

- contrib/executor/k6/build/agent/Dockerfile
> feat: Update k6s executor image (#4516)

- contrib/executor/jmeterd/pkg/slaves/meta_test.go
> fix: flaky jmeterd test

- contrib/executor/jmeterd/pkg/runner/runner.go
> feat: propagate env vars to jmeterd slaves

- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/slaves/meta_test.go
> fix: propagate env vars to jmeterd slaves (#4541)

- contrib/executor/artillery/pkg/runner/artillery.go
- contrib/executor/artillery/pkg/runner/artillery_helper.go
- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/cypress/pkg/runner/cypress.go
- contrib/executor/ginkgo/pkg/runner/runner.go
- contrib/executor/gradle/pkg/runner/runner.go
- contrib/executor/jmeter/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/mapper.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/k6/pkg/runner/runner.go
- contrib/executor/kubepug/pkg/runner/runner.go
- contrib/executor/maven/pkg/runner/runner.go
- contrib/executor/playwright/pkg/runner/playwright.go
- contrib/executor/postman/pkg/runner/newman/mapper.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
- contrib/executor/tracetest/pkg/runner/runner.go
- contrib/executor/zap/pkg/runner/runner.go
- pkg/executor/env/manager.go
> fix: optional junit options

- contrib/executor/artillery/pkg/runner/artillery.go
- contrib/executor/artillery/pkg/runner/artillery_helper.go
- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/cypress/pkg/runner/cypress.go
- contrib/executor/ginkgo/pkg/runner/runner.go
- contrib/executor/gradle/pkg/runner/runner.go
- contrib/executor/jmeter/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/mapper.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/k6/pkg/runner/runner.go
- contrib/executor/kubepug/pkg/runner/runner.go
- contrib/executor/maven/pkg/runner/runner.go
- contrib/executor/playwright/pkg/runner/playwright.go
- contrib/executor/postman/pkg/runner/newman/mapper.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
- contrib/executor/tracetest/pkg/runner/runner.go
- contrib/executor/zap/pkg/runner/runner.go
- pkg/executor/env/manager.go
> fix: obfuscate args

- docs/docs/articles/running-tests.md
> docs: env vars

- contrib/executor/cypress/build/agent/Dockerfile.cypress10
- contrib/executor/cypress/build/agent/Dockerfile.cypress11
- contrib/executor/cypress/build/agent/Dockerfile.cypress12
- contrib/executor/cypress/build/agent/Dockerfile.cypress8
- contrib/executor/cypress/build/agent/Dockerfile.cypress9
- contrib/executor/cypress/build/agent/Dockerfile.npm
- contrib/executor/cypress/build/agent/Dockerfile.yarn
- contrib/executor/example/build/agent/Dockerfile
- contrib/executor/ginkgo/build/agent/Dockerfile
- contrib/executor/init/build/agent/Dockerfile
- contrib/executor/jmeter/build/agent/Dockerfile
- contrib/executor/jmeterd/build/agent/Dockerfile
- contrib/executor/kubepug/build/agent/Dockerfile
- contrib/executor/postman/build/agent/Dockerfile
- contrib/executor/scraper/build/agent/Dockerfile
- contrib/executor/soapui/build/agent/Dockerfile
- contrib/executor/template/build/agent/Dockerfile
> feat: update executors with curl, openssh, sshpass

- pkg/mapper/tests/openapi_kube.go
> fix: ignore empty secret ref

- docs/docs/articles/test-triggers.mdx
- pkg/triggers/executor.go
- pkg/triggers/executor_test.go
- pkg/triggers/matcher.go
- pkg/triggers/matcher_test.go
- pkg/triggers/watcher_test.go
> feat: pass watcher event to trigger

- contrib/executor/cypress/build/agent/Dockerfile.cypress10
- contrib/executor/cypress/build/agent/Dockerfile.cypress11
- contrib/executor/cypress/build/agent/Dockerfile.cypress12
- contrib/executor/cypress/build/agent/Dockerfile.cypress8
- contrib/executor/cypress/build/agent/Dockerfile.cypress9
- contrib/executor/cypress/build/agent/Dockerfile.npm
- contrib/executor/cypress/build/agent/Dockerfile.yarn
- contrib/executor/example/build/agent/Dockerfile
- contrib/executor/ginkgo/build/agent/Dockerfile
- contrib/executor/init/build/agent/Dockerfile
- contrib/executor/jmeter/build/agent/Dockerfile
- contrib/executor/jmeterd/build/agent/Dockerfile
- contrib/executor/kubepug/build/agent/Dockerfile
- contrib/executor/postman/build/agent/Dockerfile
- contrib/executor/scraper/build/agent/Dockerfile
- contrib/executor/soapui/build/agent/Dockerfile
- contrib/executor/template/build/agent/Dockerfile
> feat: add curl and sshpass to jmeterd

- cmd/kubectl-testkube/commands/testsuites/executions.go
> fix: remove hint

- .github/workflows/docker-build-develop.yaml
- contrib/executor/postman/build/agent/Dockerfile
Resolves https://github.com/kubeshop/testkube/issues/4552
-
-
-
> feat: replace postman image

- pkg/repository/testresult/mongo.go
- fix: aggregate(1) on test suite results
> fix: aggregate(1) on test suite results

- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/commands/tests/watch.go
- cmd/kubectl-testkube/commands/testsuites/run.go
- docs/docs/cli/testkube_run_test.md
- docs/docs/cli/testkube_run_testsuite.md
> fix: support silent mode

- cmd/kubectl-testkube/commands/common/render/common.go
- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/executions.go
- cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/commands/tests/watch.go
- cmd/kubectl-testkube/commands/testsuites/common.go
- cmd/kubectl-testkube/commands/testsuites/run.go
- cmd/kubectl-testkube/commands/testsuites/watch.go
- pkg/api/v1/testkube/model_execution_result_extended.go
> fix: allow download reports for failed

- cmd/kubectl-testkube/commands/common/render/common.go
- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/executions.go
- cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/commands/tests/watch.go
- cmd/kubectl-testkube/commands/testsuites/common.go
- cmd/kubectl-testkube/commands/testsuites/run.go
- cmd/kubectl-testkube/commands/testsuites/watch.go
- pkg/api/v1/testkube/model_execution_result_extended.go
> fix: test suite err check

- contrib/executor/curl/build/agent/Dockerfile
> fix: curl executor using recent deps

- .github/workflows/docker-build-api-executors-tag.yaml
- contrib/executor/cypress/build/agent/Dockerfile.cypress13
Related to error: 
```
could not initialize runner: error creating scraper: error creating cloud loader: context deadline exceeded
```
> fix: update to outdated cypress images

- docs/docs/testkube-enterprise/articles/auth.md
- docs/docs/testkube-enterprise/articles/usage-guide.md
- docs/sidebars.js
> docs: add enterprise

- docs/docs/articles/argocd-integration.md
> docs: argocd cron jobs sync

- cmd/kubectl-testkube/commands/testsuites/common.go
- pkg/scheduler/testsuite_scheduler.go
> feat: download folder test status

- cmd/kubectl-testkube/commands/testsuites/common.go
- pkg/scheduler/testsuite_scheduler.go
> feat: update test staus after completion

- contrib/executor/kubepug/pkg/runner/runner_test.go
> test: update branch name in kubepug tests

- contrib/executor/cypress/build/agent/Dockerfile.cypress13
> fix: cypress image tag

- docs/src/theme/DocCard/index.js
> fix: icons urls in docs

- cmd/api-server/main.go
- cmd/kubectl-testkube/commands/cloud.go
- cmd/kubectl-testkube/commands/common/uri.go
- cmd/kubectl-testkube/commands/pro.go
- cmd/kubectl-testkube/commands/pro/connect.go
- cmd/kubectl-testkube/commands/pro/disconnect.go
- cmd/kubectl-testkube/commands/pro/environments.go
- cmd/kubectl-testkube/commands/pro/init.go
- cmd/kubectl-testkube/commands/pro/login.go
- cmd/kubectl-testkube/commands/pro/organizations.go
- cmd/kubectl-testkube/commands/root.go
- docs/docs/articles/running-tests.md
- internal/config/config.go
git cherry-pick 78190b0e184ea98fa3acb9ce9a7a4479d2036b02
-
-
-
> feat: cloud rename main

- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/commands/testsuites/run.go
> fix: exit code 1 for failed run

- internal/db-migrations/01_create_indexes.down.json
- internal/db-migrations/01_create_indexes.up.json
- internal/db-migrations/02_execution_search_indexes.down.json
- internal/db-migrations/02_execution_search_indexes.up.json
- pkg/repository/result/mongo.go
- pkg/repository/testresult/mongo.go
Cherry pick of https://github.com/kubeshop/testkube/pull/4681
> feat: Release v1.16.9

- pkg/executor/client/common.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/tmpl.go
- pkg/scheduler/test_scheduler.go
- pkg/scheduler/test_scheduler_test.go
> fix: wrong switch usage

- docs/docs/articles/getting-started.md
> docs: update testkube pro installation video

- test/jmeter/executor-tests/crd/smoke.yaml
- test/suites/executor-jmeter-smoke-tests.yaml
> feat: Executor tests - jmeterd

- docs/docs/articles/webhooks.mdx
- pkg/api/v1/testkube/model_execution_status_extended.go
- pkg/api/v1/testkube/model_test_suite_status_extended.go
- pkg/event/kind/webhook/listener.go
> feat: webhook template funcs

- docs/docs/articles/creating-tests.md
- docs/docs/test-types/executor-artillery.mdx
- docs/docs/test-types/executor-curl.mdx
- docs/docs/test-types/executor-cypress.mdx
- docs/docs/test-types/executor-ginkgo.md
- docs/docs/test-types/executor-gradle.md
- docs/docs/test-types/executor-jmeter.md
- docs/docs/test-types/executor-k6.mdx
- docs/docs/test-types/executor-kubepug.md
- docs/docs/test-types/executor-maven.md
- docs/docs/test-types/executor-playwright.md
- docs/docs/test-types/executor-postman.mdx
- docs/docs/test-types/executor-soapui.md
- docs/docs/test-types/executor-zap.md
Add more info on Maven default commands and reference on overwriting these commands
-
-
-
> docs: Add references to the args and command explanations

- contrib/executor/cypress/pkg/runner/cypress.go
- docs/docs/cli/testkube_cloud.md
- pkg/executor/output/parser.go
> fix: remove cypress result output

- pkg/envs/variables.go
- pkg/executor/agent/agent.go
> fix: get rid duplicated env lines in log

- contrib/executor/postman/build/agent/Dockerfile
> feat: change postman dockerfile

- contrib/executor/gradle/build/agent/Dockerfile.jdk11
- contrib/executor/gradle/build/agent/Dockerfile.jdk17
- contrib/executor/gradle/build/agent/Dockerfile.jdk18
- contrib/executor/gradle/build/agent/Dockerfile.jdk8
> fix: recent gradle base image

- contrib/executor/maven/build/agent/Dockerfile.jdk18
> fix: security update for maven jdk18 executor

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-release.yaml
> feat: upgrade alpine image

- goreleaser_files/.goreleaser-docker-build-executor-gradle.yml
> feat: change default gradle image

- contrib/executor/gradle/build/agent/Dockerfile.jdk21
- goreleaser_files/.goreleaser-docker-build-executor-gradle.yml
> fix: set default Gradle to 21

- contrib/executor/gradle/build/agent/Dockerfile.jdk21
> fix: gradle user home need to be set explicitly

- contrib/executor/artillery/build/agent/Dockerfile
Possible braking change for tests 
But needed for security purposes
-
-
-
> fix: artillery executor deps update and rewrite base image

- contrib/executor/cypress/build/agent/Dockerfile.cypress10
- contrib/executor/cypress/build/agent/Dockerfile.cypress12
- contrib/executor/cypress/build/agent/Dockerfile.cypress13
- goreleaser_files/.goreleaser-docker-build-executor-cypress-commit-only.yml
> fix: updated cypress images

- pkg/scheduler/test_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> fix: test execution name

- contrib/executor/gradle/build/agent/Dockerfile.jdk21
> fix: gradle jdk21 alpine - image with less sec issues

- contrib/executor/postman/build/agent/Dockerfile
Pin Postman image to 6.0.0 explicitly. 
-
-
-
> fix: pin postman image [TKC-1052]

- pkg/scheduler/test_scheduler.go
> fix: test eecution name for test suite

- cmd/api-server/main.go
- contrib/executor/init/pkg/runner/runner.go
- docs/docs/articles/helm-chart.md
- internal/config/config.go
- pkg/scheduler/test_scheduler.go
- pkg/scheduler/testsuite_scheduler.go
> feat: install specified executors

- pkg/event/kind/webhook/listener.go
- pkg/utils/text/tostr.go
- pkg/utils/text/tostr_test.go
> feat: added tostr method

- contrib/executor/k6/build/agent/Dockerfile
- pkg/logs/logsserver_test.go
> fix: security k6 docker image bump

- contrib/executor/ginkgo/build/agent/Dockerfile
- contrib/executor/kubepug/build/agent/Dockerfile
- contrib/executor/playwright/build/agent/Dockerfile.npm
- contrib/executor/playwright/build/agent/Dockerfile.pnpm
- contrib/executor/playwright/build/agent/Dockerfile.yarn
- contrib/executor/zap/build/agent/Dockerfile
> fix: zap Dockerfile

- cmd/kubectl-testkube/commands/cloud/connect.go
- cmd/kubectl-testkube/commands/cloud/disconnect.go
- cmd/kubectl-testkube/commands/cloud/init.go
- cmd/kubectl-testkube/commands/cloud/login.go
- cmd/kubectl-testkube/commands/common/flags.go
- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/common/masterFlags_test.go
- cmd/kubectl-testkube/commands/common/uri.go
- cmd/kubectl-testkube/commands/context/set.go
- cmd/kubectl-testkube/commands/init.go
- cmd/kubectl-testkube/commands/pro/connect.go
- cmd/kubectl-testkube/commands/pro/disconnect.go
- cmd/kubectl-testkube/commands/pro/init.go
- cmd/kubectl-testkube/commands/pro/login.go
- cmd/kubectl-testkube/commands/upgrade.go
- cmd/kubectl-testkube/config/data.go
- cmd/kubectl-testkube/config/master.go
- pkg/cloud/client/environments.go
> fix: rewrite cloud uris configs

- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
> fix: rollback changes to pipelines

- .github/workflows/release-log-server.yaml
- .github/workflows/release-log-sidecar.yaml
- build/logs/Dockerfile
- goreleaser_files/.goreleaser-docker-build-logs-server.yml
- goreleaser_files/.goreleaser-docker-build-logs-sidecar.yml
fixing the issues for cicd of logs service
-
-
-
> fix: Main fix cicd logs

- contrib/executor/init/pkg/runner/runner.go
- fix: pre-run/post-run/command scripts are running incorrectly
-
-
-
> fix: pre-run/post-run/command scripts are running incorrectly

- contrib/executor/jmeterd/pkg/runner/helpers.go
- contrib/executor/jmeterd/pkg/runner/helpers_test.go
- contrib/executor/jmeterd/pkg/runner/runner.go
> feat: add support for configurable test file using envvar and edit variables to be set as envvars

- contrib/executor/jmeterd/pkg/runner/helpers.go
- contrib/executor/jmeterd/pkg/runner/helpers_test.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/slaves/client.go
- contrib/executor/jmeterd/pkg/slaves/env.go
- contrib/executor/jmeterd/pkg/slaves/utils.go
> chore: cherry-pick jmeterd changes

- pkg/executor/scraper/factory/factory.go
> feat: improve logging around connecting to agent api

- contrib/executor/jmeterd/pkg/slaves/client.go
- contrib/executor/jmeterd/pkg/slaves/utils.go
> feat: slave pod number env var

- cmd/api-server/main.go
- internal/app/api/v1/executions.go
- internal/app/api/v1/server.go
> fix: passed feature flags in construct function

- internal/app/api/v1/tests.go
- pkg/api/v1/testkube/model_repository_extended.go
- pkg/mapper/tests/openapi_kube.go
> fix: check if repository is empty on conversion from open api

- pkg/executor/common.go
- pkg/logs/client/stream.go
> feat: pass sidecar image from executors json file

- pkg/http/client.go
> fix: initialize transport with default one explicitly

- contrib/executor/jmeterd/pkg/slaves/env.go
> fix: skip runner secrets

- internal/app/api/v1/tests.go
- pkg/api/v1/testkube/model_repository_extended.go
> fix: complete repository empty check

- internal/app/api/v1/tests.go
- pkg/api/v1/testkube/model_repository_extended.go
* fix: complete repository empty check
* fix: extract method for empty check
-
-
-
> fix: complete repository empty check (#4889)

- config/slave-pod-template.yml
> fix: pvc name

- pkg/slack/slack.go
> fix: slack token must be set to initialize Slack Listener

- .builds-linux.goreleaser.yml
- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
Add release tag to `testkube-cli` Docker image. 
-
-
-
> fix: add tag to testkube cli image

- internal/app/api/v1/handlers.go
- pkg/logs/adapter/minio.go
- pkg/logs/adapter/minio_test.go
- pkg/storage/minio/minio.go
- pkg/storage/minio/minio_connecter.go
> feat: add minio log consumer with opts

- contrib/executor/gradle/build/agent/Dockerfile.jdk11
- contrib/executor/gradle/build/agent/Dockerfile.jdk17
- contrib/executor/gradle/build/agent/Dockerfile.jdk18
- contrib/executor/gradle/build/agent/Dockerfile.jdk8
> fix: add gradle home

- pkg/cloud/data/artifact/scraper_integration_test.go
- pkg/cloud/data/artifact/uploader.go
- pkg/cloud/data/artifact/uploader_test.go
- pkg/executor/scraper/factory/factory.go
add support for skipping cert verification of presigned put urls
-
-
-
> feat: add support for skipping cert verification of presigned put urls

- cmd/api-server/main.go
- cmd/logs/main.go
- cmd/sidecar/main.go
- internal/config/config.go
- pkg/event/bus/nats.go
- pkg/event/emitter_integration_test.go
- pkg/logs/config/logs_config.go
- pkg/scheduler/service.go
- pkg/scheduler/test_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> fix: trigger event for logs start

- contrib/executor/k6/pkg/runner/runner.go
> fix: support missing run path

- pkg/logs/events.go
- pkg/scheduler/test_scheduler.go
> fix: execution id not passed to events

- pkg/logs/events.go
- pkg/logs/events_test.go
- pkg/logs/service.go
- pkg/scheduler/test_scheduler.go
> fix: added cooldown time to not stop events too early

- build/sidecar/Dockerfile
> fix: smaller docker file for logs sidecar

- docs/docs/articles/cicd-overview.md
- docs/docs/articles/circleci.md
Created article with examples on how to integrate Testkube with CircleCI.
-
-
-
> docs: add CircleCI article

- DESIGN.md
- README.md
- contrib/executor/artillery/README.md
- contrib/executor/gradle/README.md
- contrib/executor/k6/README.md
- contrib/executor/kubepug/README.md
- contrib/executor/maven/README.md
- contrib/executor/template/README.md
- contrib/executor/tracetest/README.md
- docs/docs/articles/argocd-integration.md
- docs/docs/articles/common-issues.md
- docs/docs/articles/deploying-in-aws.md
- docs/docs/articles/getting-started.md
- docs/docs/testkube-pro/articles/AI-test-insights.md
- docs/docs/testkube-pro/articles/status-pages.md
- docs/docusaurus.config.js
Update docs to contain link to Slack channel.
-
-
-
> docs: Discord-Slack Migration

- .github/workflows/release-dev-log-server.yaml
- .github/workflows/release-dev-log-sidecar.yaml
> ci: update for logs service

- .github/workflows/release-dev-log-server.yaml
- .github/workflows/release-dev-log-sidecar.yaml
> ci: add manifest for logs service

- docs/docs/index.mdx
Added demo video to docs overview
-
-
-
> docs: add demo to docs overview

- pkg/logs/events.go
- pkg/logs/events/events.go
- pkg/logs/events_test.go
- pkg/logs/service.go
- pkg/scheduler/test_scheduler.go
> chore: refactor of stop function

- contrib/executor/jmeterd/pkg/runner/helpers.go
- contrib/executor/jmeterd/pkg/runner/helpers_test.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/runner_test.go
> fix: jmeterd: add sanity checking for test file

- pkg/logs/events.go
> fix: added adapter stop

- pkg/logs/events.go
> fix: adapter stop call after consumer stop

- cmd/logs/main.go
- pkg/logs/adapter/dummy.go
- pkg/logs/adapter/minio.go
- pkg/logs/adapter/minio_test.go
- pkg/logs/config/logs_config.go
- pkg/logs/service_test.go
> feat: add minio adapter for logs

- .github/workflows/release-dev-log-server.yaml
- .github/workflows/release-dev-log-sidecar.yaml
- .github/workflows/release-log-server.yaml
- .github/workflows/release-log-sidecar.yaml
- goreleaser_files/.goreleaser-docker-build-logs-server.yml
- goreleaser_files/.goreleaser-docker-build-logs-sidecar.yml
This PR enables to build Docker images for `log server` and `log sidecar` with a semver tag. Also signs the Docker images 
-
-
-
> ci: logs services fix

- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/runner_test.go
> fix: merge duplicated args

- docs/docs/articles/webhooks.mdx
> docs: Add selected webhooks blog content to webhooks doc.

- contrib/executor/jmeterd/pkg/parser/mapper.go
- contrib/executor/jmeterd/pkg/runner/runner_test.go
> fix: remove custom assertion logic in jmeterd executor

- pkg/logs/client/client.go
- pkg/logs/sidecar/proxy.go
> fix: fixing timeouts

- pkg/logs/client/client.go
> fix: grpc client creates endless loops

- cmd/kubectl-testkube/commands/tests/run.go
- cmd/logs/main.go
- internal/app/api/v1/executions.go
- pkg/logs/client/client.go
- pkg/logs/client/interface.go
- pkg/logs/client/mock_stream.go
- pkg/logs/client/stream.go
- pkg/logs/client/stream_test.go
- pkg/logs/events.go
- pkg/logs/events/events.go
- pkg/logs/events_test.go
- pkg/logs/logsserver.go
- pkg/logs/logsserver_test.go
- pkg/logs/service.go
> fix: log finish handled correctly

- cmd/kubectl-testkube/commands/common/render/common.go
- cmd/kubectl-testkube/commands/tests/executions.go
- cmd/kubectl-testkube/commands/tests/renderer/execution_obj.go
- cmd/kubectl-testkube/commands/tests/run.go
> fix: duplicated logs when watching results in real time

- api/v1/testkube.yaml
- internal/app/api/v1/executor.go
- internal/app/api/v1/server.go
- pkg/executor/client/job.go
> feat: get executor by test type

- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/jmeter/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/helpers.go
- contrib/executor/jmeterd/pkg/runner/helpers_test.go
- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/runner_test.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
> fix: support override mode

- contrib/executor/jmeterd/pkg/runner/runner.go
> fix: use user OUTPUT_DIR

- api/v1/testkube.yaml
- internal/app/api/v1/executor.go
- internal/app/api/v1/server.go
> fix: switch to query instead of path param

- contrib/executor/curl/pkg/runner/runner.go
- contrib/executor/jmeter/pkg/runner/runner.go
- contrib/executor/postman/pkg/runner/newman/newman.go
- contrib/executor/soapui/pkg/runner/runner.go
> fix: return path to script check

- codecov.yaml
Ignore mocks in the CodeCov's code coverage
-
-
-
> chore: ignore mocks in the code coverage

- cmd/api-server/main.go
- pkg/repository/result/mongo.go
> fix: rollback NewMongoREpository construct function to not be changed

- pkg/repository/result/mongo.go
> fix: removed unnecessary values from cloud only constructors

- pkg/slack/slack.go
Closes https://github.com/kubeshop/testkube/issues/4993
-
-
-
> fix: nil pointer in compose slack message

- internal/app/api/metrics/metrics.go
> fix: remove uuid from metrics

- contrib/executor/jmeterd/pkg/runner/runner.go
> fix: rename outout dir

- contrib/executor/jmeterd/pkg/runner/runner.go
- contrib/executor/jmeterd/pkg/runner/runner_test.go
> fix: remove duplicate -n

- contrib/executor/jmeterd/pkg/runner/runner.go
> fix: remove dirs duplication

- pkg/tcl/README.md
remove reference for now
-
-
-
> docs: [TKC-1207] remove FAQ reference

- cmd/api-server/main.go
- go.mod
- go.sum
- internal/config/config.go
- internal/config/procontext.go
- licenses/TCL.txt
- pkg/cloud/data/config/commands.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/tcl/README.md
- pkg/tcl/checktcl/organization_plan.go
- pkg/tcl/checktcl/subscription.go
- pkg/tcl/checktcl/subscription_test.go
Cherry-pick to main to be able to import it nicely on the pro api server
-
-
-
> feat: [TKC-1207] license checker cherry-pick to main

- docs/docs/testkube-pro/articles/status-pages.md
> docs: add status page example to docs

- pkg/crd/templates/testsuite.tmpl
- pkg/tcl/testsuitestcl/steps.go
> fix: small fixes for test step executions

- cmd/api-server/main.go
- pkg/tcl/checktcl/subscription.go
> fix: fix pointer issue

- docs/docs/articles/azure-troubleshooting.md
- docs/docs/articles/azure.md
- docs/sidebars.js
> docs: azure troubleshooting

- pkg/telemetry/sender_sio.go
Sets context app/build information consistent with other build types.
-
- Sets context app/build information on tracked events.
- TKC-1399
> feat: send app/build information in telemetry context.

- cmd/kubectl-testkube/commands/cloud/init.go
- cmd/kubectl-testkube/commands/pro/init.go
- pkg/telemetry/payload.go
- pkg/telemetry/sender_sio.go
- pkg/telemetry/telemetry.go
> feat: enhance init command telemetry

- LICENSE
- licenses/MIT.txt
move MIT license into licenses folder
-
-
-
> docs: [TKC-1208] update licenses folder

- cmd/kubectl-testkube/commands/cloud/init.go
- cmd/kubectl-testkube/commands/pro/init.go
- pkg/telemetry/payload.go
- pkg/telemetry/sender_sio.go
- pkg/telemetry/telemetry.go
> feat: enhance init command telemetry cherry-pick to main (#5026)

- LICENSE
- licenses/MIT.txt
cherry-pick from develop
-
-
-
> docs: license folder main

- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor_test.go
> fix: panic on empty bool env

- cmd/api-server/main.go
- internal/app/api/v1/server.go
- pkg/api/v1/testkube/model_test_suite_base_extended.go
- pkg/crd/templates/testsuite.tmpl
- pkg/tcl/checktcl/organization_plan.go
- pkg/tcl/checktcl/subscription.go
- pkg/tcl/checktcl/subscription_test.go
Small fixes for the test suite step parametrization and subscription check
-
-
-
> fix: [TKC-1055] fix subscription check and templating

- cmd/api-server/main.go
- internal/app/api/v1/server.go
- pkg/api/v1/testkube/model_test_suite_base_extended.go
- pkg/crd/templates/testsuite.tmpl
- pkg/tcl/checktcl/organization_plan.go
- pkg/tcl/checktcl/subscription.go
- pkg/tcl/checktcl/subscription_test.go
cherry-pick from develop
-
-
-
> fix: subscription check main

- docs/docs/articles/run-tests-with-github-actions.md
- docs/sidebars.js
> Docs: information about testkube-run-action being deprecated

- docs/docs/articles/testkube-dependencies.md
Update docs to warn about support for this.
-
-
-
> docs: Update testkube-dependencies.md

- docs/docs/testkube-enterprise/articles/usage-guide.md
> docs: add installation of simplified Testkube Enterprise to the docs

- cmd/logs/main.go
- pkg/logs/client/stream.go
- pkg/logs/config/logs_config.go
- pkg/logs/events.go
- pkg/logs/service.go
> fix: logging adjustments

- docs/docs/testkube-pro/articles/running-parallel-tests-with-test-suite.md
> docs: test suite steps style fixes

- internal/app/api/v1/executions_test.go
- pkg/cloud/data/result/result.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/repository/result/interface.go
- pkg/repository/result/mock_repository.go
- pkg/repository/result/mongo.go
> feat: added GetExecution to featch exection without output

- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
> fix: dont attach logs to the result when v2 enabled

- cmd/api-server/main.go
- cmd/logs/main.go
- config/job-container-template.yml
- config/job-template.yml
- internal/config/config.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/events_test.go
- pkg/agent/logs_test.go
- pkg/envs/variables.go
- pkg/executor/client/common.go
- pkg/executor/client/job.go
- pkg/executor/common.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/executor/scraper/factory/factory.go
- pkg/logs/adapter/cloud_test.go
- pkg/logs/config/logs_config.go
- pkg/scheduler/service.go
- pkg/scheduler/test_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> feat: TKC-1290: add support for custom CA certificates

- test/postman/executor-tests/crd-workflow/smoke.yaml
- test/scripts/executor-tests/run.sh
`./test/scripts/executor-tests/run.sh -c -e workflow -ntestkube-workflows`
> feat: Workflow tests - run script

- pkg/api/v1/client/uploads.go
PR to add fix to release branch
-
-
-
> fix: release copy file direct client uri fix

- api/v1/testkube.yaml
- pkg/tcl/apitcl/v1/testworkflows.go
* allow to preview TestWorkflow definition without inlining templates
> feat: allow to preview TestWorkflow without inlining templates

- pkg/logs/events/events.go
> fix: added default times

- pkg/tcl/testworkflowstcl/testworkflowprocessor/container.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
> fix: run TestWorkflows artifacts step as root, to read FS without problems

- docs/docs/test-types/executor-curl.mdx
> docs: fix typo in curl docs

- pkg/executor/client/common.go
- pkg/executor/containerexecutor/containerexecutor.go
> fix: add field for custom CA in containerexecutor JobOptions (#5137)

- test/cypress/executor-tests/crd-workflow/smoke.yaml
- test/gradle/executor-smoke/crd-workflow/smoke.yaml
- test/jmeter/executor-tests/crd-workflow/smoke.yaml
- test/k6/executor-tests/crd-workflow/smoke.yaml
- test/maven/executor-smoke/crd-workflow/smoke.yaml
- test/playwright/executor-tests/crd-workflow/smoke.yaml
- test/postman/executor-tests/crd-workflow/smoke.yaml
- test/scripts/executor-tests/run.sh
- test/soapui/executor-smoke/crd-workflow/smoke.yaml
- test/test-workflow-templates/cypress.yaml
- test/test-workflow-templates/k6.yaml
- test/test-workflow-templates/postman.yaml
- TestWorkflow tests updated after `testworkflows.testkube.io/v1`
- Trait checkout cases
- checkout on step
- sub-step
- global
- workflow cases - playwright anc cypress artifacts, cypress 13 video recording enabled, cypress 12 video recording (fefault), playwright shell, artifacts double asterisk
> feat: TestWorkflow tests updated after `testworkflows.testkube.io/v1` and extended

- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* Add more logs related to problems with TestWorkflow controller
> chore: add more logs regarding TestWorkflow controller

- internal/app/api/v1/testsuites.go
> fix: list testsuite artifacts

- pkg/triggers/watcher.go
> fix: ignore non test pods

- pkg/skopeo/client.go
> fix: typo for auth selection

- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* When information about the TestWorkflow process is lost (due to an aborted job), try to determine it again.
> fix: handle aborting TestWorkflow executions gracefully

- test/examples/kubecon/test-workflows/cypress.yaml
- test/examples/kubecon/test-workflows/gradle.yaml
- test/examples/kubecon/test-workflows/jmeter.yaml
- test/examples/kubecon/test-workflows/k6.yaml
- test/examples/kubecon/test-workflows/playwright.yaml
- test/examples/kubecon/test-workflows/postman.yaml
- test/examples/kubecon/tests/cypress.yaml
- test/examples/kubecon/tests/gradle.yaml
- test/examples/kubecon/tests/jmeter.yaml
- test/examples/kubecon/tests/k6.yaml
- test/examples/kubecon/tests/playwright.yaml
- test/examples/kubecon/tests/postman.yaml
- test/examples/kubecon/tests/testsuites/k6.yaml
- test/jmeter/executor-tests/crd-workflow/smoke.yaml
- test/k6/executor-tests/crd-workflow/smoke.yaml
- TestWorkflow cases:
- k6 with artifact (report)
- jmeter with artifacts
- Kubecon examples
- Tests - cypress, gradle, jmeter, k6, playwright (container), postman
- Test Workflows - cypress, gradle, jmeter, k6, playwright, postman
> feat: testworkflow cases - k6 and jmeter with artifacts, examples for kubecon

- pkg/api/v1/testkube/model_test_workflow_result_extended.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/controller.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go
- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* make fixed-width timestamp for Kubernetes errors treat as logs
* differ aborted job from problem with retrieving job
* add missing `finishedAt` on fatal error
* include Pod errors in the "Initiializing..." container
> fix: improve Kubernetes error handling of TestWorkflow executions

- cmd/tcl/testworkflow-toolkit/commands/execute.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/constants.go
> feat: expose Test Workflow name for scheduled tests

- internal/app/api/v1/labels.go
- internal/app/api/v1/server.go
- pkg/tcl/apitcl/v1/server.go
* Register TestWorkflow and TestWorkflowTemplate as sources for the global (OSS) `/labels` endpoint
> fix: include TestWorkflow labels in the /labels list

- pkg/executor/containerexecutor/containerexecutor.go
Closes https://github.com/kubeshop/testkube/issues/3109
-
-
-
> fix: container executor negative test

- pkg/executor/content/fetcher_test.go
> fix: git fetcher tests

- cmd/api-server/main.go
- cmd/logs/main.go
- internal/config/config.go
- internal/config/procontext.go
- pkg/agent/agent.go
- pkg/logs/config/logs_config.go
- pkg/logs/events.go
- pkg/scheduler/testsuite_scheduler.go
> fix: logs grpc uris without path

- test/suites/demo-testsuite.json
> fix: delete dashboard test from demo test suite

- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
> fix: clean pvc volume

- cmd/tcl/testworkflow-init/main.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/stagelifecycle.go
* TestWorkflow Processor wasn't passing Retry Policy to TestWorkflow stages
* TestWorkflow Init Process was incorrectly reading that data
> fix: (main) support Retry Policies in TestWorkflows

- docs/docs/testkube-enterprise/articles/usage-guide.md
Docs update to include Custom Certs support for Enterprise installations.
-
-
-
> docs: Enterprise - Include Custom certificates documentation

- cmd/tcl/testworkflow-init/main.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/stagelifecycle.go
* fix: (move to develop) hotfix: support Retry Policies in TestWorkflows (#5199)
> fix: (move to develop) hotfix: support Retry Policies in TestWorkflows (#5199)

- docs/docs/articles/testkube-oss.md
- docs/docs/articles/upgrade.md
- docs/redirects.js
- docs/sidebars.js
> docs: testkube upgrading

- cmd/kubectl-testkube/commands/common/flags.go
- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/common/masterFlags_test.go
- cmd/kubectl-testkube/commands/common/uri.go
- cmd/kubectl-testkube/commands/context/set.go
- cmd/kubectl-testkube/config/master.go
> feat: added logs service params for cloud

- pkg/tcl/apitcl/v1/testworkflowmetrics.go
- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
Refine Test workflow telemetry
-
-
-
> feat: [TKC-1745] add more sophisticated telemetry for workflows

- docs/package.json
> fix: increase available memory for building docs

- api/v1/testkube.yaml
- internal/app/api/v1/handlers.go
- pkg/api/v1/testkube/model_server_info.go
- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
> fix: use cluster/environment ids for cli telemetry (#5215)

- cmd/api-server/main.go
- pkg/tcl/apitcl/v1/server.go
- pkg/tcl/apitcl/v1/testworkflowmetrics.go
- pkg/tcl/apitcl/v1/testworkflows.go
- pkg/tcl/apitcl/v1/testworkflowtemplates.go
- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
cherry-picked the commits
-
-
-
> feat: [TKC-1745] workflow telemetry main

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-log-server.yaml
- .github/workflows/release-log-sidecar.yaml
- .github/workflows/release.yaml
upgrade cosign-installer dependency
-
-
-
> ci: signing issue

- .github/workflows/scorecard.yml
> ci: upgrade scorecard

- cmd/kubectl-testkube/commands/context/set.go
> fix: removed doubled flag

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-log-server.yaml
- .github/workflows/release-log-sidecar.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecard.yml
cherry-pick from develop
-
-
-
> ci: signing issue main

- docs/docs/articles/open-source-or-pro.md
> docs: Update Open Source or Pro Table

- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
> fix: add telemetry cli context (#5226)

- api/v1/testkube.yaml
- cmd/api-server/main.go
- internal/app/api/v1/handlers.go
- internal/app/api/v1/secret.go
- internal/app/api/v1/server.go
- pkg/api/v1/testkube/model_server_info.go
- pkg/secret/client.go
- pkg/secret/mock_client.go
> fix: list secret parameters

- pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* The test step was not failing when shell command failed
> fix: hotfix(main): fail TestWorkflow's shell command on error

- pkg/imageinspector/skopeofetcher.go
- pkg/skopeo/client.go
> fix: use registry for inspection

- internal/app/api/metrics/metrics.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/containerexecutor_test.go
- pkg/scheduler/testsuite_scheduler.go
> feat: execution duration metric

- .github/workflows/release-dev.yaml
cherry-pick to main from https://github.com/kubeshop/testkube/pull/5252
-
-
-
> ci: disable dev releases to the apt server (#5252)

- docs/docs/articles/artifacts.md
> docs: shared /data volume across all pods docs

- cmd/logs/main.go
- pkg/event/kind/websocket/listener.go
- pkg/logs/adapter/minio.go
- pkg/logs/events.go
- pkg/logs/events/events.go
- pkg/logs/logsserver.go
- pkg/logs/service.go
- pkg/logs/service_test.go
- pkg/logs/sidecar/proxy.go
> fix: logging improvements for logs server

- build/logs/Dockerfile
- pkg/logs/adapter/minio_v2.go
- pkg/repository/result/mongo.go
> fix: new alpine image

- build/sidecar/Dockerfile
- pkg/repository/result/mongo.go
> fix: dont attach logs to result output

- .github/workflows/docker-build-release.yaml
> ci: add logs service

- docs/redirects.js
Small change to add redirects from Enterprise docs to Pro On-Prem.
> docs: [TKC-1798] Include redirect(s) from Enterprise to Pro On-Prem

- cmd/api-server/main.go
> fix: subscription checker not being propagated to scheduler

- cmd/api-server/main.go
> feat: cherry-pick: enterprise execution namespace

- cmd/api-server/main.go
- config/job-scraper-template.yml
- config/job-template.yml
- config/slave-pod-template.yml
- internal/config/config.go
- pkg/executor/client/common.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/templates/job.tmpl
- pkg/scheduler/service.go
- pkg/scheduler/test_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> feat: inject custom ca

- cmd/api-server/main.go
- config/job-scraper-template.yml
- config/job-template.yml
- config/slave-pod-template.yml
- internal/config/config.go
- pkg/executor/client/common.go
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/templates/job.tmpl
- pkg/scheduler/service.go
- pkg/scheduler/test_scheduler.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
* feat: add runner custom ca variable
* feat: add runner ca certificate to default job template
* feat: add runner ca certificate to job template
* feat: add runner ca certificate to job scraper template
* feat: add runner ca certificate to slave pod template
-
-
-
> feat: inject custom ca (#5269)

- pkg/tcl/apitcl/v1/testworkflowmetrics.go
cherry-pick from develop
-
-
-
> fix: nil check main

- api/v1/testkube.yaml
- internal/app/api/v1/handlers.go
- pkg/api/v1/testkube/model_server_info.go
> fix: enable secret endpoint flag

- docs/docs/articles/running-parallel-tests-with-test-suite.md
- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/reconciler/reconciler.go
- pkg/triggers/watcher.go
> fix: ignore getting log error

- docs/docs/articles/running-parallel-tests-with-test-suite.md
- pkg/tcl/apitcl/v1/testworkflowmetrics.go
- pkg/tcl/apitcl/v1/testworkflowmetrics_test.go
Catch nil pointers and refactor the workflow metrics code
-
-
-
> fix: workflow telemetry pointer

- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/run.go
- internal/app/api/v1/executions.go
- internal/app/api/v1/tests.go
> fix: [TKC-1151] remove args formatting

- pkg/executor/client/job.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/output/parser.go
- pkg/executor/output/parser_test.go
- pkg/triggers/watcher.go
> fix: clean error message for negative tests

- docs/docs/testkube-pro-on-prem/articles/testkube-pro-on-prem.md
> docs: Remove Pricing Image

- cmd/tcl/testworkflow-toolkit/env/config.go
- pkg/tcl/apitcl/v1/testworkflows.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/container.go
* Expose Pod IP for the Toolkit
* Expose Toolkit/Init image names for the Toolkit
> feat(testworkflows): expose IP and image names for the Toolkit containers

- cmd/tcl/testworkflow-toolkit/commands/execute.go
* Expose real-time status of TestWorkflows and Tests in `execute` step
* Thanks to that, we will be able to display test-suite-like list on the UI
> feat(testworkflows): expose real-time status from `execute` step

- cmd/tcl/testworkflow-toolkit/artifacts/cloud_uploader.go
- cmd/tcl/testworkflow-toolkit/artifacts/direct_uploader.go
- cmd/tcl/testworkflow-toolkit/artifacts/internalartifactstorage.go
- cmd/tcl/testworkflow-toolkit/artifacts/options.go
- cmd/tcl/testworkflow-toolkit/artifacts/uploader.go
- cmd/tcl/testworkflow-toolkit/commands/artifacts.go
- cmd/tcl/testworkflow-toolkit/env/client.go
* Expose tool to save internal artifacts from TestWorkflow Toolkit
* Thanks to that, we will be able to share bigger files like logs of distributed tests, or resource consumption recording
> feat(testworkflows): expose tool to save internal artifacts

- pkg/tcl/testworkflowstcl/testworkflowprocessor/configmapfiles.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/intermediate.go
* Extract logic for generating ConfigMap with files for TestWorkflow
* Deduplicate files
> feat(testworkflows): optimize and extract building ConfigMap with files

- cmd/tcl/testworkflow-init/run/run.go
- cmd/tcl/testworkflow-init/utils/outputProcessor.go
- cmd/tcl/testworkflow-toolkit/common/combinations.go
- cmd/tcl/testworkflow-toolkit/env/config.go
- pkg/imageinspector/skopeofetcher.go
- pkg/tcl/expressionstcl/parse_test.go
- pkg/tcl/expressionstcl/stdlib.go
- pkg/tcl/testworkflowstcl/testworkflowresolver/merge.go
- fix processing output from steps
- fix reading group from image by Skopeo
- fix reading images in Toolkit
- unify code for merging maps
- expose `ReadCount` helper
- rename `shellargs` to `shellparse` as it's more distinguishable from `shellquote`
> fix(testworkflows): various adjustments

- pkg/tcl/testworkflowstcl/testworkflowprocessor/constants/constants.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/processor_test.go
> fix: [TKC-1851]use init image instead of busy-box

- cmd/api-server/main.go
- cmd/tcl/testworkflow-toolkit/env/config.go
- internal/config/config.go
- pkg/tcl/apitcl/v1/server.go
- pkg/tcl/apitcl/v1/testworkflows.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/container.go
* add support for global TestWorkflowTemplate that is automatically included in all executions
* pass the template contents to the Toolkit too, so it will have consistent template through the execution (for parallel workflows)
> feat(testworkflows): add support for global TestWorkflowTemplate that is automatically included in all executions

- cmd/kubectl-testkube/commands/common/render/common.go
- pkg/ui/printers.go
- pkg/ui/ui.go
> fix: print dashboard links last and blue

- test/scripts/executor-tests/run.sh
> feat: ability to test set client in executor tests

- contrib/executor/zap/build/agent/Dockerfile
> fix: new location for zap image

- cmd/api-server/main.go
- internal/app/api/v1/labels.go
> fix: label value duplication

- pkg/mapper/testtriggers/kube_openapi.go
- pkg/mapper/testtriggers/openapi_kube.go
> fix: test trigger mapping

- pkg/tcl/apitcl/v1/testworkflowmetrics.go
- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
- pkg/tcl/testworkflowstcl/utils.go
- pkg/tcl/testworkflowstcl/utils_test.go
> fix: move pkg

- cmd/kubectl-testkube/commands/init.go
> fix: fix license spaces

- cmd/kubectl-testkube/commands/init.go
> chore: release/v1.17.21

- cmd/kubectl-testkube/commands/init.go
> fix: hotfix license key

- cmd/kubectl-testkube/commands/init.go
> fix: release/v1.17.22

- contrib/executor/jmeterd/pkg/slaves/client.go
- pkg/executor/client/job.go
- pkg/executor/common.go
> fix: salve pod template ca secret

- docs/docs/articles/install/advanced-install.md
- docs/docs/articles/install/install-with-cli.md
- docs/docs/articles/templates.mdx
- docs/docs/test-types/prebuilt-executor.md
Small change to use HTTPS instead of HTTP in URLs.
> docs: Change HTTP to HTTPS on URLs (SEO requirement)

- pkg/imageinspector/skopeofetcher.go
- pkg/imageinspector/skopeofetcher_test.go
- pkg/skopeo/client.go
- pkg/skopeo/client_test.go
fix issue with image pull secrets for workflows
-
-
-
> fix: issue with image pull secrets for workflows

- pkg/logs/client/stream.go
> feat: TKC-1956 log message retention time

- pkg/imageinspector/skopeofetcher.go
- pkg/imageinspector/skopeofetcher_test.go
- pkg/skopeo/client.go
- pkg/skopeo/client_test.go
- pkg/utils/consts.go
fix for private registries in test workflows
-
-
-
> feat: cherry-pick: fix for private registries in test workflows

- docs/docs/articles/templates.mdx
- docs/docs/openapi.md
- docs/sidebars.js
Link Pro OpenAPI specification
-
-
-
> docs: link openapi definition

- cmd/kubectl-testkube/commands/dashboard.go
- cmd/kubectl-testkube/commands/init.go
- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
> fix: add more telemetry for on prem installer

- cmd/kubectl-testkube/commands/dashboard.go
- cmd/kubectl-testkube/commands/init.go
- cmd/kubectl-testkube/commands/pro/init.go
- cmd/kubectl-testkube/commands/purge.go
- pkg/telemetry/payload.go
- pkg/telemetry/telemetry.go
> fix: add more telemetry for on prem installer (#5412)

- cmd/kubectl-testkube/commands/init.go
- pkg/telemetry/sender_sio.go
> fix: telemetry mappings

- cmd/kubectl-testkube/commands/init.go
> fix: relax license format to include old offline licenses

- cmd/kubectl-testkube/commands/init.go
- cmd/kubectl-testkube/commands/pro/init.go
> fix: dashboard panic when opening from init

- docs/docs/testkube-pro-on-prem/articles/migrating-from-oss-to-pro.md
- docs/docs/testkube-pro-on-prem/articles/usage-guide.md
Remove all doc references to download.testkube.io (old bash script)
> docs: Remove references to old installer

- pkg/executor/common.go
> feat: added debug info in case of pod disaster

- pkg/executor/common.go
> feat: cherry-pick added debug info in case of pod disaster

- cmd/tcl/testworkflow-toolkit/commands/parallel.go
- pkg/api/v1/testkube/model_test_workflow_result_extended.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/podstate.go
* handle race condition between events and pod state
* fix minor issues
> fix(testworkflows): orchestration fixes

- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/debug.go
- cmd/kubectl-testkube/commands/debug/controlplane.go
- cmd/kubectl-testkube/commands/debug/info.go
- cmd/kubectl-testkube/commands/debug/utils.go
- cmd/kubectl-testkube/commands/init.go
- cmd/kubectl-testkube/commands/pro/init.go
- contrib/executor/k6/pkg/runner/runner_integration_test.go
- pkg/process/exec.go
- pkg/ui/printers.go
- pkg/ui/ui.go
Get all needed pods logs from enterprise api
-
-
-
> feat: Control Plane debug command

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-develop.yaml
cherry pick: add action to cleanup space before building executors (#5442)
-
-
-
> feat: add action to cleanup space before building executors (#5442)

- pkg/tcl/testworkflowstcl/testworkflowresolver/apply.go
* Include TestWorkflowTemplate's `events` in the merged TestWorkflow
> fix: include TestWorkflowTemplate events in the TestWorkflow

- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/debug.go
- cmd/kubectl-testkube/commands/debug/controlplane.go
- cmd/kubectl-testkube/commands/debug/info.go
- cmd/kubectl-testkube/commands/debug/utils.go
- contrib/executor/k6/pkg/runner/runner_integration_test.go
- pkg/process/exec.go
- pkg/ui/printers.go
- pkg/ui/ui.go
> feat: cherry-pick cmd pick to release

- pkg/logs/adapter/cloud_test.go
also limited messages counts a little - as sometimes Github runner lags  
-
-
-
> fix: moved NATS tests to integration test suite

- cmd/logs/main.go
- internal/app/api/v1/executions.go
- internal/app/api/v1/server.go
- internal/app/api/v1/testsuites.go
- internal/template/parser.go
- pkg/agent/agent.go
- pkg/agent/logs.go
- pkg/cloud/data/artifact/uploader.go
- pkg/event/emitter.go
- pkg/event/loader.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/output/parser.go
- pkg/log/trace.go
- pkg/logs/adapter/minio.go
- pkg/logs/adapter/minio_v2.go
- pkg/logs/client/client.go
- pkg/logs/config/logs_config.go
- pkg/logs/events.go
- pkg/logs/logsserver.go
- pkg/logs/service.go
- pkg/scheduler/test_scheduler.go
- pkg/scheduler/testsuite_scheduler.go
- pkg/storage/minio/minio.go
> fix: moved some noisy logs to debug added TRACE level

- cmd/tcl/testworkflow-toolkit/commands/parallel.go
- cmd/tcl/testworkflow-toolkit/commands/services.go
- cmd/tcl/testworkflow-toolkit/env/config.go
- cmd/tcl/testworkflow-toolkit/spawn/utils.go
- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/container.go
- pkg/tcl/testworkflowstcl/testworkflowresolver/apply.go
* use default ServiceAccount for TestWorkflows
* fix small bug with `events`
> Release v1.17.38

- cmd/kubectl-testkube/commands/init.go
- pkg/telemetry/sender_sio.go
> fix: cherry pick telemetry license

- cmd/tcl/testworkflow-toolkit/commands/parallel.go
- pkg/api/v1/testkube/model_test_workflow_result_extended.go
* log status changes of parallel steps in the general logs
> feat: log status of the parallel steps

- cmd/tcl/testworkflow-toolkit/commands/parallel.go
- pkg/api/v1/testkube/model_test_workflow_result_extended.go
* fix for exposing TestWorkflow pauses
* display TestWorkflow parallel steps status change in logs
> Release v1.17.41 - fix for TestWorkflow pauses

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-release.yaml
- contrib/executor/postman/build/agent/Dockerfile.node21
- goreleaser_files/.goreleaser-docker-build-executor-postman-node21.yml
Added build of Postman image base on Node 21. Base image: `node:21-alpine3.19`
-
-
-
> feat: tkc-1987 postman image

- docs/docs/articles/install/quickstart-install.mdx
Add a clarification for On Prem installation.
-
-
-
> docs: update docs for TK Installer

- cmd/tcl/testworkflow-toolkit/artifacts/handler_test.go
- cmd/tcl/testworkflow-toolkit/artifacts/junit_post_processor.go
- cmd/tcl/testworkflow-toolkit/artifacts/junit_post_processor_test.go
- cmd/tcl/testworkflow-toolkit/commands/artifacts.go
- cmd/tcl/testworkflow-toolkit/commands/artifacts_test.go
- docs/docs/articles/test-workflow-templates.md
- test/cypress/executor-tests/crd-workflow/smoke.yaml
- test/k6/executor-tests/crd-workflow/smoke.yaml
* fix: some bugs in the TestWorkflow examples
* fix: artifacts error, while the root is different from working directory
> fix: bugs from TestWorkflow examples / artifacts error

- internal/app/api/v1/testsuites.go
> fix: use tse id param

- pkg/log/log.go
Format log `ts` as RFC3339 time human readable 
-
-
-
> fix: added human readable log format

- api/v1/testkube.yaml
- cmd/kubectl-testkube/commands/webhooks/common.go
- cmd/kubectl-testkube/commands/webhooks/create.go
- cmd/kubectl-testkube/commands/webhooks/update.go
- docs/docs/articles/webhooks.mdx
- docs/docs/cli/testkube_create_webhook.md
- docs/docs/cli/testkube_update_webhook.md
- go.mod
- go.sum
- pkg/api/v1/testkube/model_webhook.go
- pkg/api/v1/testkube/model_webhook_create_request.go
- pkg/api/v1/testkube/model_webhook_extended.go
- pkg/api/v1/testkube/model_webhook_update_request.go
- pkg/event/kind/webhook/listener.go
- pkg/event/kind/webhook/listener_test.go
- pkg/event/kind/webhook/loader.go
- pkg/mapper/webhooks/mapper.go
This PR adds the option to disable webhooks and makes sure that no notification is sent out on a disabled webhook.
-
-
-
> feat: [TKC-1948] disable webhooks

- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/debugger/debugger.go
- cmd/kubectl-testkube/debugger/events.go
- cmd/kubectl-testkube/debugger/job.go
> feat: added simple job and events debug to the test run command to catch up killed pods 

- cmd/kubectl-testkube/commands/context/set.go
- cmd/kubectl-testkube/commands/pro/init.go
> fix: added no-login option for OnPrem to bypass login ask

- cmd/kubectl-testkube/commands/context/set.go
- cmd/kubectl-testkube/commands/pro/init.go
- cmd/kubectl-testkube/commands/tests/run.go
- cmd/kubectl-testkube/debugger/debugger.go
- cmd/kubectl-testkube/debugger/events.go
- cmd/kubectl-testkube/debugger/job.go
> chore: cherry pick - debug killed pods cherry

- pkg/log/log.go
> chore: cherry pick human readable log format

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_test_workflow_independent_service_spec.go
- pkg/api/v1/testkube/model_test_workflow_independent_step_parallel.go
- pkg/api/v1/testkube/model_test_workflow_result.go
- pkg/api/v1/testkube/model_test_workflow_result_extended.go
- pkg/api/v1/testkube/model_test_workflow_result_summary.go
- pkg/api/v1/testkube/model_test_workflow_service_spec.go
- pkg/api/v1/testkube/model_test_workflow_step_execute_test_ref.go
- pkg/api/v1/testkube/model_test_workflow_step_execute_test_workflow_ref.go
- pkg/api/v1/testkube/model_test_workflow_step_parallel.go
> fix(testworkflows): strange duration for fatal errors

- cmd/kubectl-testkube/commands/dashboard.go
- pkg/k8sclient/k8sclient.go
- pkg/telemetry/license.go
- pkg/telemetry/payload.go
- pkg/telemetry/sender_sio.go
- pkg/telemetry/telemetry.go
> fix: add email to the on prem install telemetry

- cmd/kubectl-testkube/commands/dashboard.go
- pkg/k8sclient/k8sclient.go
- pkg/telemetry/license.go
- pkg/telemetry/payload.go
- pkg/telemetry/sender_sio.go
- pkg/telemetry/telemetry.go
> fix: add email to the on prem install telemetry (#5495)

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_test_workflow_independent_service_spec.go
- pkg/api/v1/testkube/model_test_workflow_independent_step_parallel.go
- pkg/api/v1/testkube/model_test_workflow_service_spec.go
- pkg/api/v1/testkube/model_test_workflow_step_execute_test_ref.go
- pkg/api/v1/testkube/model_test_workflow_step_execute_test_workflow_ref.go
- pkg/api/v1/testkube/model_test_workflow_step_parallel.go
> fix: fix semantic errors and generate openapi files (#5497)

- pkg/agent/events.go
Related to removin Cloud -> Agent healthchecker
-
-
-
> fix: agent send healthcheck each 5 seconds

- cmd/kubectl-testkube/commands/dashboard.go
- cmd/kubectl-testkube/config/storage.go
> fix: port-forward minio when opening the dashboard for enterprise

- cmd/kubectl-testkube/commands/dashboard.go
> fix: dashboard undefined error

- docs/docs/articles/istio.md
- docs/sidebars.js
> docs: istio compatibility

- docs/docs/articles/istio.md
- docs/docs/articles/private-ca.md
- docs/sidebars.js
Also includes changes from #5503 to avoid conflicts.
-
-
- TKC-2017
> docs: using private ca

- docs/docs/articles/vault.md
- docs/sidebars.js
> docs: vault integration

- docs/docs/articles/install/install-with-helm.md
> docs: fix endpoints

- contrib/executor/jmeterd/scripts/jmeter-slaves.sh
> fix: slaves env name

- .github/workflows/docker-build-api-executors-tag.yaml
> ci: remove updating of executors

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-release.yaml
- .github/workflows/release-dev-log-server.yaml
- .github/workflows/release-dev-log-sidecar.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release-log-server.yaml
- .github/workflows/release-log-sidecar.yaml
- .github/workflows/release.yaml
update alpine image in CI to v3.20.0
-
-
-
> chore: update alpine image in CI to v3.20.0

- docs/docs/articles/test-workflow-templates.md
The existing link for Postman is directed to Cypress.yaml, fixed that.
> docs: Update test-workflow-templates.md

- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
* https://goreleaser.com/deprecations/?h=skip+publish#-skip
-
-
-
> fix: adjust GoReleaser skip-publish command

- cmd/kubectl-testkube/commands/debug/controlplane.go
- cmd/kubectl-testkube/commands/executors/common.go
- pkg/api/v1/client/testsuite.go
make function comments match function names
-
-
-
> chore: make function comments match function names

- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
> Release v1.17.56

- .builds-darwin.goreleaser.yml
- .builds-linux.goreleaser.yml
- .builds-windows.goreleaser.yml
- .goreleaser-dev.yml
- .goreleaser.yml
- goreleaser_files/.goreleaser-docker-build-api.yml
- goreleaser_files/.goreleaser-docker-build-executor-cypress.yml
- goreleaser_files/.goreleaser-docker-build-executor-gradle.yml
- goreleaser_files/.goreleaser-docker-build-executor-jmeter.yml
- goreleaser_files/.goreleaser-docker-build-executor-jmeterd.yml
- goreleaser_files/.goreleaser-docker-build-executor-maven.yml
- goreleaser_files/.goreleaser-docker-build-executor-playwright.yml
- goreleaser_files/.goreleaser-docker-build-executor-postman-node21.yml
- goreleaser_files/.goreleaser-docker-build-executor.yml
- goreleaser_files/.goreleaser-docker-build-logs-services.yml
- goreleaser_files/.goreleaser-docker-build-testworkflow.yml
* Based on [**upgrading notes**](https://goreleaser.com/blog/goreleaser-v2/#upgrading) that should be enough
-
-
-
> fix: main: adjust version of GoReleaser configuration

- .builds-darwin.goreleaser.yml
- .builds-linux.goreleaser.yml
- .builds-windows.goreleaser.yml
- .goreleaser-dev.yml
- .goreleaser.yml
- goreleaser_files/.goreleaser-docker-build-api.yml
- goreleaser_files/.goreleaser-docker-build-executor-cypress.yml
- goreleaser_files/.goreleaser-docker-build-executor-gradle.yml
- goreleaser_files/.goreleaser-docker-build-executor-jmeter.yml
- goreleaser_files/.goreleaser-docker-build-executor-jmeterd.yml
- goreleaser_files/.goreleaser-docker-build-executor-maven.yml
- goreleaser_files/.goreleaser-docker-build-executor-playwright.yml
- goreleaser_files/.goreleaser-docker-build-executor-postman-node21.yml
- goreleaser_files/.goreleaser-docker-build-executor.yml
- goreleaser_files/.goreleaser-docker-build-logs-services.yml
- goreleaser_files/.goreleaser-docker-build-testworkflow.yml
* Now, GoReleaser works fine on `main`, so the changes need to be copied to `develop` too 👍
> fix: cherry-pick from main: GoReleaser fixes

- pkg/tcl/testworkflowstcl/testworkflowcontroller/logs.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/logs_test.go
- pkg/tcl/testworkflowstcl/testworkflowcontroller/utils.go
> Release v1.17.59 - hotfix for non-UTC clusters

- cmd/kubectl-testkube/commands/init.go
> fix: add more install telemetry

- cmd/logs-sidecar/main.go
- pkg/logs/config/logs_config.go
- pkg/logs/sidecar/proxy.go
> fix: slave pods logs handled through fixed POD_NAME env variable

- cmd/logs-sidecar/main.go
- pkg/logs/sidecar/proxy.go
> fix: logs proxy for slaves followup - split subject with pod name

- pkg/executor/common.go
- pkg/logs/sidecar/proxy.go
> fix: get pods by name in logs proxy instead of labels

- cmd/api-server/main.go
- internal/config/config.go
- pkg/event/server.go
- pkg/event/server_test.go
> feat: added embedded nats server

- cmd/api-server/main.go
- internal/config/config.go
- pkg/event/server.go
- pkg/event/server_test.go
* feat: added embedded nats server
* chore: added comments to the code
-
-
-
> feat: added embedded nats server (#5564)

- cmd/kubectl-testkube/commands/common/helper.go
> feat: added embedded nats server option to CLI

- cmd/kubectl-testkube/commands/common/helper.go
> feat: embedded nats option in cli cherry

- pkg/tcl/testworkflowstcl/testworkflowprocessor/processor.go
- pkg/tcl/testworkflowstcl/testworkflowprocessor/processor_test.go
* There were plenty of environment variables added regarding the services
> feat(testworkflows): disable service links that pollute environment variables

- pkg/executor/output/parser.go
- pkg/executor/output/parser_test.go
> fix: parsing output result

- pkg/event/bus/nats.go
> chore: added logging to nats publish

- cmd/kubectl-testkube/commands/testworkflows/create.go
- docs/docs/articles/creating-test-suites.md
- docs/docs/articles/webhooks.mdx
> docs: [TKC-1948] disable webhooks on resources docs

- docs/docs/articles/test-workflows-content.md
- docs/sidebars.js
* Migrate https://github.com/kubeshop/testkube-docs/pull/13
> docs: backport Test Workflow's content documentation

- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
* At the moment, every log line was also causing the CR to be updated, despite it had no change.
> fix(testworkflows): avoid updating TestWorkflow CR when there is no actual result change

- docs/docs/articles/metrics.md
- internal/app/api/metrics/metrics.go
- pkg/triggers/matcher.go
- pkg/triggers/matcher_test.go
- pkg/triggers/watcher.go
- pkg/triggers/watcher_test.go
> feat: testtrigger metrics

- docs/docs/testkube-pro-on-prem/articles/auth.md
> docs: update/fix on-prem auth docs

- docs/docs/articles/test-workflow-migration.md
- docs/sidebars.js
> docs: test workflow migration

- cmd/kubectl-testkube/commands/testworkflows/executions.go
- cmd/kubectl-testkube/commands/testworkflows/run.go
- pkg/api/v1/testkube/model_test_workflow_signature_extended.go
* It was skipping steps without logs for finished tests
> fix(testworkflows): ensure all steps (even empty) are shown in a correct order in CLI

- contrib/executor/jmeterd/pkg/runner/helpers.go
- internal/app/api/metrics/metrics.go
- pkg/triggers/matcher.go
- pkg/triggers/watcher.go
> fix: [TKC-2135] expand test flag

- cmd/api-server/main.go
- contrib/executor/jmeterd/pkg/runner/helpers.go
- docs/docs/articles/metrics.md
- internal/app/api/metrics/metrics.go
- internal/app/api/v1/testsuites.go
- pkg/tcl/apitcl/v1/testworkflowexecutions.go
- pkg/tcl/testworkflowstcl/testworkflowexecutor/executor.go
- pkg/triggers/matcher.go
- pkg/triggers/matcher_test.go
- pkg/triggers/scraper.go
- pkg/triggers/watcher.go
- pkg/triggers/watcher_test.go
> feat: twe and trigger metrics

- docs/docs/articles/install/install-with-helm.md
Fix small typo in property name for license configuration.
> docs: Fix enterprise license key

- docs/docs/articles/webhooks.mdx
> docs: update list of test suite execution attributes

- cmd/api-server/main.go
- docs/docs/articles/webhooks.mdx
- internal/app/api/v1/server.go
- internal/config/config.go
- internal/config/procontext.go
- pkg/event/kind/webhook/listener.go
- pkg/event/kind/webhook/listener_test.go
- pkg/event/kind/webhook/loader.go
- pkg/event/kind/webhook/loader_test.go
- pkg/event/kind/webhook/templatevars.go
Add variables for commands and URLs for the webhooks templates
-
-
-
> feat: [TKC-1947] add urls and command variables

- cmd/tcl/testworkflow-toolkit/spawn/utils.go
- pkg/testworkflows/testworkflowprocessor/utils.go
* 'fetch' operation for parallel steps
> fix(testworkflows): 'fetch' operation for parallel steps

- cmd/tcl/testworkflow-toolkit/spawn/utils.go
- pkg/testworkflows/testworkflowprocessor/utils.go
> release: v2.0.1 - bugfix

- cmd/api-server/main.go
- internal/config/config.go
- pkg/executor/client/job.go
- pkg/executor/common.go
- pkg/executor/common_test.go
- pkg/executor/containerexecutor/containerexecutor.go
- pkg/executor/containerexecutor/logs.go
In case of sidecar containers, i.e. istio-proxy, logs from main containers get fetched in parallel and log output is messy.
This PR introduces whitelisting of containers.
-
-
-
> feat: whitelist containers for which logs should be extracted

- cmd/api-server/main.go
- cmd/testworkflow-toolkit/artifacts/handler.go
- cmd/testworkflow-toolkit/commands/artifacts.go
- cmd/testworkflow-toolkit/commands/artifacts_test.go
- cmd/testworkflow-toolkit/env/config.go
- internal/app/api/metrics/metrics.go
- pkg/api/v1/testkube/model_test_workflow_execution_extended.go
- pkg/api/v1/testkube/model_test_workflow_step_extended.go
- pkg/api/v1/testkube/model_test_workflow_step_parallel_extended.go
- pkg/event/kind/cdevent/listener.go
- pkg/event/kind/webhook/listener.go
- pkg/mapper/cdevents/mapper.go
- pkg/mapper/cdevents/mapper_test.go
- pkg/testworkflows/testworkflowexecutor/executor.go
- pkg/testworkflows/testworkflowprocessor/container.go
> feat: check for test workflow execution for execute action

- cmd/kubectl-testkube/commands/testworkflows/run.go
- pkg/testworkflows/testworkflowprocessor/constants/constants.go
- pkg/testworkflows/testworkflowprocessor/operations.go
> fix: user friendly oss feature error messages

- cmd/logs-server/main.go
> fix: Logs server issue with already created KV store

- pkg/api/v1/client/direct_client.go
> fix: missed transport

- cmd/kubectl-testkube/commands/common/helper.go
- pkg/api/v1/client/direct_client.go
> feat: Release/v2.0.5

- cmd/tcl/testworkflow-toolkit/spawn/utils.go
> fix: [TKC-2226] add cdevents var to spawn package

- .github/workflows/sandbox.yaml
> ci: add dispatch to sandbox

- .github/workflows/sandbox.yaml
> ci: add dispatch (#5667)

- .github/workflows/sandbox.yaml
> ci: fix a typo in CI for sandbox

- .github/workflows/sandbox.yaml
> ci: fix typo ci

- .github/workflows/sandbox-deletion.yaml
> ci: add sandbox deletion

- pkg/testworkflows/testworkflowresolver/apply.go
* Use the `template` correctly
> fix: template in parallel steps

- pkg/testworkflows/testworkflowprocessor/container.go
- pkg/testworkflows/testworkflowprocessor/processor.go
- pkg/testworkflows/testworkflowprocessor/utils.go
- pkg/testworkflows/testworkflowresolver/apply.go
> chore: Release v2.0.13

- pkg/ui/printers.go
> feat: lighten colors in UI

- internal/app/api/v1/events.go
> fix: locals not anymore printable

- internal/app/api/v1/server.go
> fix: TestkubeAPI receiver doesnt mutate state

- cmd/kubectl-testkube/commands/common/flags.go
> fix: correctly use --ui-prefix and --logs-prefix data

- cmd/testworkflow-init/orchestration/setup.go
* Open the working directory when it is expected
-
-
-
> fix: setting up working directory with atomic instructions

- cmd/kubectl-testkube/commands/common/validator/version.go
> fix: show version only in pretty mode

- test/cypress/executor-tests/crd-workflow/smoke.yaml
- test/integration/crd-workflow/testkube-integration-tests.yaml
> fix: integration tests and matrix test with artifacts for Cypress

- cmd/kubectl-testkube/commands/common/validator/version.go
> fix: show version only in pretty mode (#5748)

- cmd/testworkflow-toolkit/artifacts/cloud_uploader.go
- pkg/testworkflows/testworkflowcontroller/notifier.go
> fix: concurrency problems when having a lot of parallel updates

- cmd/tcl/testworkflow-toolkit/commands/services.go
* https://github.com/kubeshop/testkube/pull/5766
> chore: Release v2.1.1

- pkg/telemetry/sender_sio.go
> fix: add mapping for error code in error telemetry

- pkg/telemetry/sender_sio.go
> feat: cherry-pick: add mapping for error code in error telemetry (#5769)

- pkg/repository/config/mongo_test.go
> fix: flaky mongo test

- cmd/testworkflow-toolkit/commands/clone.go
- pkg/testworkflows/testworkflowprocessor/action/process_test.go
- pkg/testworkflows/testworkflowprocessor/operations.go
- pkg/testworkflows/testworkflowprocessor/presets/processor_test.go
- pkg/testworkflows/testworkflowprocessor/processor.go
> chore: Release v2.1.4

- cmd/kubectl-testkube/commands/context/set.go
> fix: allow to override api uri

- api/v1/testkube.yaml
- internal/app/api/v1/labels_tags.go
- internal/app/api/v1/server.go
- pkg/cloud/data/testworkflow/execution.go
- pkg/cloud/data/testworkflow/execution_models.go
- pkg/repository/testworkflow/interface.go
- pkg/repository/testworkflow/mock_repository.go
- pkg/repository/testworkflow/mongo.go
> feat: test workflow tags

- cmd/kubectl-testkube/commands/testworkflows/run.go
- cmd/kubectl-testkube/commands/testworkflows/run_test.go
> fix: workflows timestamps size for valid timestamps

- api/v1/testkube.yaml
- internal/app/api/v1/labels_tags.go
- internal/app/api/v1/server.go
- pkg/cloud/data/testworkflow/execution.go
- pkg/cloud/data/testworkflow/execution_models.go
- pkg/repository/testworkflow/interface.go
- pkg/repository/testworkflow/mock_repository.go
- pkg/repository/testworkflow/mongo.go
* feat: test workflow tags
* feat: test workflow tags api spec
* feat: add test workflow api method routes
---------
-
-
-
> feat: Release/v2.1.11

- cmd/api-server/main.go
- internal/app/api/v1/server.go
- pkg/agent/events.go
- pkg/api/v1/testkube/model_event_extended.go
- pkg/event/emitter.go
- pkg/event/emitter_integration_test.go
- pkg/event/emitter_test.go
- pkg/event/kind/webhook/listener.go
- pkg/event/kind/webhook/listener_test.go
- pkg/event/kind/webhook/loader.go
- pkg/event/kind/webhook/loader_test.go
- pkg/logs/events_test.go
- pkg/repository/config/mongo_test.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> fix: sensitive data in events

- cmd/tcl/testworkflow-toolkit/commands/execute.go
- cmd/testworkflow-toolkit/commands/clone.go
- cmd/testworkflow-toolkit/commands/tarball.go
- cmd/testworkflow-toolkit/commands/utils.go
* To handle temporary DNS problems, retry cloning on failure
> fix: retry cloning Git repository on failure

- cmd/api-server/main.go
- cmd/kubectl-testkube/commands/testworkflows/run.go
- cmd/kubectl-testkube/commands/testworkflows/run_test.go
- internal/app/api/v1/server.go
- pkg/agent/events.go
- pkg/event/emitter.go
- pkg/event/emitter_integration_test.go
- pkg/event/emitter_test.go
- pkg/event/kind/webhook/listener.go
- pkg/event/kind/webhook/listener_test.go
- pkg/event/kind/webhook/loader.go
- pkg/event/kind/webhook/loader_test.go
- pkg/logs/events_test.go
- pkg/triggers/executor_test.go
- pkg/triggers/service_test.go
> chore: cherry pick hotfixes

- cmd/testworkflow-init/obfuscator/obfuscator.go
- cmd/testworkflow-init/obfuscator/obfuscator_test.go
- cmd/testworkflow-init/orchestration/executions.go
- cmd/testworkflow-init/output/printer.go
> fix: handle child process stream correctly to avoid broken pipe (#5835)

- cmd/kubectl-testkube/commands/testworkflows/create.go
> fix: allow to use create --update like in helm

- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/run.go
> fix: [TKC-2519] format test cli args

- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/tests/run.go
> fix: format test cli args

- pkg/storage/minio/minio.go
- test/postman/hello-postman.postman_collection.json
This workaround doesn't fully fix an issue, but reduce memory pressure
-
-
-
> fix: [TKC-2564]  reduce memory pressure

- pkg/repository/testworkflow/filter.go
- pkg/repository/testworkflow/interface.go
- pkg/repository/testworkflow/mongo.go
> feat: add names filter

- pkg/repository/testworkflow/minio_output_repository.go
* use proper reader for reading the buffered content
> fix: store logs properly in OSS in Minio

- pkg/telemetry/payload.go
- pkg/telemetry/sender_sio.go
- pkg/telemetry/telemetry.go
add telemetry for container env
-
-
-
> feat: [TKC-2622] container env

- pkg/expressions/libs/fs.go
* expose information about current `workingDir`
> feat: add workingDir expression to access the current working directory

- .github/workflows/release.yaml
- build/kind/entrypoint.sh
> build: fix arhc for docker agent

- cmd/kubectl-testkube/commands/common/flags.go
- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/common/masterFlags_test.go
- cmd/kubectl-testkube/commands/context/set.go
- cmd/kubectl-testkube/commands/init.go
- cmd/kubectl-testkube/commands/pro/connect.go
- cmd/kubectl-testkube/commands/pro/docker.go
- cmd/kubectl-testkube/commands/pro/init.go
- cmd/kubectl-testkube/commands/pro/login.go
- cmd/kubectl-testkube/commands/upgrade.go
> fix: save container name

- test/postman/executor-tests/postman-executor-smoke-negative.postman_collection.json
- test/postman/executor-tests/postman-executor-smoke-without-envs.postman_collection.json
- test/postman/executor-tests/postman-executor-smoke.postman_collection.json
> fix: postman test host

- test/suites/test-workflows/junit-workflow.yaml
Sandbox test after `recurse: true`, junit workflow suite fixed
> fix: junit workflow suite fixed

- cmd/tcl/testworkflow-toolkit/commands/execute.go
> fix: workflow name in rc

- cmd/kubectl-testkube/commands/testworkflows/run.go
> fix: don't panic in cli logs

- .github/workflows/docker-build-api-executors-tag.yaml
> ci: add dispatch to release job

- cmd/tcl/testworkflow-toolkit/commands/execute.go
> fix: [TKC-2857]  list selector test workflows and check for empty list

- .builds-darwin.goreleaser.yml
- .builds-linux.goreleaser.yml
- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
> fix: CI fixes for diagnostics

- pkg/controlplane/server.go
> fix: misssed control plabe methods

- pkg/mapper/testworkflows/kube_openapi.go
> fix: [TKC-3029] add mapping for services for twt spec

- pkg/expressions/parse_test.go
- pkg/expressions/static.go
> fix: [TKC-3038]  support brace escaping

- test/testkube/enterprise-installation-expect-file.exp
- test/testkube/enterprise-installation.yaml
https://app.testkube.dev/organization/testkube/environment/testkube-cloud-test-dev/dashboard/test-workflows/enterprise-installation-test/overview/677fda4b8a21fef33c25e634/
> feat: Enterprise installation workflow

- pkg/event/kind/webhook/listener.go
> fix: [TKC-3140] using env for uri

- pkg/controlplaneclient/metadata.go
> feat: expose the Agent version to Control Plane

- cmd/api-server/main.go
- cmd/kubectl-testkube/commands/agents/create.go
- cmd/kubectl-testkube/commands/agents/delete.go
- cmd/kubectl-testkube/commands/agents/enable.go
- cmd/kubectl-testkube/commands/agents/get.go
- cmd/kubectl-testkube/commands/agents/install.go
- cmd/kubectl-testkube/commands/agents/update.go
- cmd/kubectl-testkube/commands/agents/utils.go
- cmd/kubectl-testkube/commands/common/agents.go
- cmd/kubectl-testkube/commands/common/environments.go
- cmd/kubectl-testkube/commands/common/helper.go
- cmd/kubectl-testkube/commands/create.go
- cmd/kubectl-testkube/commands/delete.go
- cmd/kubectl-testkube/commands/disable.go
- cmd/kubectl-testkube/commands/enable.go
- cmd/kubectl-testkube/commands/get.go
- cmd/kubectl-testkube/commands/install.go
- cmd/kubectl-testkube/commands/root.go
- cmd/kubectl-testkube/commands/testworkflows/run.go
- cmd/kubectl-testkube/commands/update.go
- cmd/tcl/kubectl-testkube/devbox/devutils/cloud.go
- pkg/cloud/client/agents.go
- pkg/cloud/client/environments.go
- pkg/cloud/client/organizations.go
- pkg/cloud/client/rest.go
- pkg/controlplaneclient/client.go
- pkg/controlplaneclient/metadata.go
- pkg/testworkflows/testworkflowexecutor/scheduler.go
> feat: add initial CLI for managing the agents

- pkg/cloud/client/environments.go
> fix: enabling new architecture

- cmd/kubectl-testkube/commands/common/environments.go
> fix: fix label within login command

- pkg/repository/testworkflow/mongo.go
> fix: use lowercase keys in records, the same as for other serialization

- pkg/testworkflows/testworkflowexecutor/prepared.go
- pkg/testworkflows/testworkflowexecutor/scheduler.go
> fix: prefix execution group names properly

- .github/workflows/docker-build-develop.yaml
- contrib/executor/cypress/build/agent/Dockerfile.cypress10
- contrib/executor/cypress/build/agent/Dockerfile.cypress11
- contrib/executor/cypress/build/agent/Dockerfile.cypress12
- contrib/executor/cypress/build/agent/Dockerfile.cypress13
- contrib/executor/cypress/build/agent/Dockerfile.cypress8
- contrib/executor/cypress/build/agent/Dockerfile.cypress9
- goreleaser_files/.goreleaser-docker-build-executor-cypress.yml
> fix: cypress issue

- pkg/controlplaneclient/runner.go
- pkg/controlplaneclient/utils.go
- pkg/runner/agent.go
> fix: avoid blocking runner requests loop on external problem

- .github/workflows/lint.yaml
- internal/app/api/deprecatedv1/executions.go
- internal/app/api/v1/testworkflowexecutions.go
- pkg/cloud/data/artifact/artifacts_storage.go
- pkg/storage/artifacts.go
- pkg/storage/artifacts_mock.go
- pkg/storage/minio/artifacts_storage.go
> fix: [TKC-2959] support archive downloading

- cmd/kubectl-testkube/commands/testworkflows/run.go
> fix: TKC-3272 tk run tw watch repeat in case of failure

- pkg/controlplaneclient/execution.go
> fix: update execution output the old way, if the Control Plane doesn't support a new one

- pkg/utilization/core/group.go
> fix: nil pointer access when grouping test metrics

- cmd/kubectl-testkube/commands/testworkflows/run.go
> fix: log retry logic

- pkg/utilization/instrument.go
This safety guard is because if a network interface is removed, the bytes sent and received will be removed from the calculation, and we can end up with lower values than the previous ones.
Issue: https://github.com/shirou/gopsutil/issues/511
-
-
-
> fix: issue with network and disk rate calculations

- pkg/utilization/instrument.go
> fix: network test metrics

- .github/workflows/new-build.yaml
> ci: fix condition

- pkg/utilization/format.go
- pkg/utilization/instrument.go
- pkg/utilization/utilisation.go
> feat: fix disk metrics calculation and reorganize code

- internal/template/parser.go
> fix: ignore error

- pkg/runner/agent.go
> fix: avoid error when redundant start execution commands are sent

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_executions_metrics_executions.go
- pkg/repository/testworkflow/mongo.go
> feat: add group ID and runner ID to metrics

- docker-bake.hcl
> chore: fix build args

- pkg/repository/testworkflow/mongo.go
> fix: use MatchedCount instead of ModifiedCount for Assign()

- .github/workflows/docker-build-api-executors-tag.yaml
- contrib/executor/cypress/build/agent/Dockerfile.cypress13
> feat: update cypress version

- pkg/testworkflows/testworkflowexecutor/scheduler.go
> fix: fix nil panic

- .github/workflows/docker-build-api-executors-tag.yaml
- .github/workflows/new-build.yaml
- .github/workflows/release-dev.yaml
- .github/workflows/release.yaml
- .github/workflows/sandbox.yaml
- Makefile
- build/_local/testworkflow-init.Dockerfile
- build/_local/testworkflow-toolkit.Dockerfile
- docker-bake.hcl
- test/executors/container-executor-large-artifacts.yaml
- test/special-cases/test-workflows/junit-reports.yaml
Roll back Alpine version to solve git clone ssl error.
-
- 
- Roll back alpine to previous version.
> fix: rollback alpine upgrade to solve git clone ssl error

- cmd/api-server/main.go
- cmd/api-server/services/executionworker.go
- cmd/tcl/testworkflow-toolkit/spawn/utils.go
- pkg/testworkflows/executionworker/controller/controller.go
- pkg/testworkflows/executionworker/controller/watchers/executionstate.go
- pkg/testworkflows/executionworker/controller/watchers/job.go
- pkg/testworkflows/executionworker/controller/watchers/pod.go
- pkg/testworkflows/executionworker/kubernetesworker/interface.go
- pkg/testworkflows/executionworker/kubernetesworker/worker.go
- pkg/testworkflows/executionworker/registry/controllers.go
- pkg/testworkflows/testworkflowconfig/config.go
- pkg/testworkflows/testworkflowprocessor/bundle.go
- pkg/testworkflows/testworkflowprocessor/constants/constants.go
- pkg/testworkflows/testworkflowprocessor/utils.go
* add runner ID to the execution deployment to avoid conflicts in same namespac
> feat: add runner ID to the execution deployment to avoid conflicts in same namespac

- pkg/controlplaneclient/utils.go
- pkg/runner/executionsaver.go
- pkg/runner/runner.go
- pkg/runner/service.go
* mark the execution as aborted, if it has been deleted meanwhile
* double ensure that the Update won't happen after Finish
* ensure Monitor error log
> fix: recover externally aborted execution job

- pkg/tcl/testworkflowstcl/testworkflowprocessor/operations.go
* start services correctly
* when there is no imagePullSecrets, they won't start now
> fix: start services correctly

- pkg/runner/runner.go
> fix: add retries for getting the execution, increase monitor retries

- internal/app/api/v1/testworkflows.go
> fix: [TKC-3459] use runner target for rerun

- go.mod
- go.sum
- pkg/utils/utils.go
> fix: [TKC-3467] upgrade sprig version

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_test_workflow_execution_summary.go
- pkg/repository/testworkflow/mongo.go
> feat: add resource aggregations to workflow execution summary

- cmd/tcl/kubectl-testkube/devbox/command.go
- cmd/tcl/kubectl-testkube/devbox/devutils/agent.go
- cmd/tcl/kubectl-testkube/devbox/devutils/namespace.go
> feat: add support for --enable-test-triggers and --enable-cronjobs

- cmd/tcl/kubectl-testkube/devbox/command.go
- cmd/tcl/kubectl-testkube/devbox/devutils/cluster.go
* The cluster architecture may be different than a node that is scheduled. Add workaround to handle it in development tool.
> feat: allow forcing OS/Arch for devbox

- internal/app/api/deprecatedv1/executions.go
- internal/app/api/v1/testworkflowexecutions.go
> fix: remove file closing

- pkg/repository/testworkflow/mongo.go
* avoid `$sort` when it's not important (in some cases, it's like 20 seconds down to <100ms)
```json
[
{"$match": {
"workflow.name": "postman-workflow-smoke-cron-trigger-test",
"scheduledat": {
"$gte": ISODate("2025-04-01T07:12:00.887Z")
}
}},
{"$sort": {"statusat": -1}},
{"$skip": 0},
{"$limit": 2147483647},
{"$group": {
"_id": "$result.status",
"count": {"$sum": 1}
}}
]
```
```json
[
{"$match": {
"workflow.name": "postman-workflow-smoke-cron-trigger-test",
"scheduledat": {
"$gte": ISODate("2025-04-01T07:12:00.887Z")
}
}},
{"$group": {
"_id": "$result.status",
"count": {"$sum": 1}
}}
]
```
> fix: improve the performance of getting totals if time is not important

- pkg/testworkflows/testworkflowprocessor/action/containerize.go
- pkg/testworkflows/testworkflowprocessor/processor.go
> fix: one more global dedup

- cmd/kubectl-testkube/commands/agents/create.go
- cmd/kubectl-testkube/commands/agents/install.go
- cmd/kubectl-testkube/commands/agents/utils.go
- cmd/tcl/kubectl-testkube/devbox/command.go
- cmd/tcl/kubectl-testkube/devbox/devutils/cloud.go
- pkg/cloud/client/agents.go
* https://github.com/kubeshop/testkube-cloud-api/pull/1927
> feat: add --floating argument for creating runners

- cmd/tcl/testworkflow-toolkit/execute/execute.go
> fix: build target in `execute` correctly

- pkg/testworkflows/testworkflowexecutor/testworkflowfetcher.go
- pkg/testworkflows/testworkflowexecutor/testworkflowtemplatefetcher.go
* use `sync.Map` to avoid concurrent write errors
> fix: concurrency issues with fetchers

- pkg/event/kind/webhook/templatevars.go
> fix: [TKC-3501] remove duplicated https://

- cmd/kubectl-testkube/commands/agents/create.go
- cmd/kubectl-testkube/commands/agents/utils.go
> fix: display correct runner installation command

- pkg/expressions/README.md
Describe:
* Methods
* Reasoning behind
* Machines
* Standard Library
* Operating with structs
> chore: add README for expressions

- cmd/kubectl-testkube/commands/agents/get.go
- cmd/kubectl-testkube/commands/agents/install.go
- cmd/kubectl-testkube/commands/agents/utils.go
- cmd/kubectl-testkube/commands/common/agents.go
- pkg/cloud/client/agents.go
* show deletion information on `get runner <runner-name>` command
> fix: display deleted agents better

- cmd/testworkflow-toolkit/commands/clone.go
* by default Git will create files that don't have group r/w permissions
* because of that, FS Group won't necessarily work
> fix: allow r/w for group for cloned repositories

- pkg/cronjob/scheduler.go
> fix: add log line

- cmd/testworkflow-init/constants/commands.go
- cmd/testworkflow-init/main.go
- cmd/testworkflow-init/orchestration/setup.go
- pkg/testworkflows/testworkflowconfig/config.go
- pkg/testworkflows/testworkflowprocessor/action/containerize.go
- pkg/testworkflows/testworkflowprocessor/presets/processor_test.go
- pkg/testworkflows/testworkflowprocessor/processor.go
> fix: [TKC-3639] mask secret volume data

- pkg/runner/runner.go
Abort execution if monitor times out and assume they are stuck running.
-
-
-
> feat: TKC-3697: abort executions stuck in running state

- test/testkube/installation-tests/crd/enterprise-installation.yaml
Update multi-namespace installation test after breaking change
> fix: Installation tests for multi namespace - updated after breaking change

- pkg/repository/testworkflow/mongo.go
change GetFinished function for workflow executions to use scheduledat
-
-
-
> fix: change GetFinished function for workflow executions to use scheduledat

- api/v1/testkube.yaml
- pkg/api/v1/testkube/model_test_workflow_execution_health.go
> fix: update health metrics in API to simplify flip rate calculations

- build/_local/testworkflow-init.Dockerfile
> fix: testworkflwo-init dockerfile for debug

- test/special-cases/edge-cases-random.yaml
- test/suites/cron/dev/trigger-small-suite-on-deployment.yaml
> fix: remove namespace from TWs

- .gitignore
Added depot-build-meta.json to .gitignore
> chore: add depot build meta to .gitignore

- pkg/utilization/core/parsers.go
Simplify parser logic when appending metrics lines.
-
-
-
> fix: panic when parsing resource metrics due to array out of index

- Makefile
- cmd/api-server/main.go
- cmd/testworkflow-toolkit/commands/artifacts.go
- cmd/testworkflow-toolkit/commands/clone.go
- cmd/testworkflow-toolkit/commands/clone_test.go
- cmd/testworkflow-toolkit/commands/utils.go
- test/integration/components/toolkit/clone_test.go
Refactor git clone, separate logic into smaller functions, add unit and integration tests
-
-
-
> chore: refactor toolkit clone logic, add unit and integration tests

- pkg/api/v1/testkube/model_test_workflow_status_extended.go
> fix: add missing paused and canceled statuses to parser

- .golangci.yml
> feat: relax golangci-lint rules around package comments and exports

- cmd/api-server/services/controlplane.go
- internal/app/api/v1/testworkflowwithexecutions.go
- pkg/cloud/data/testworkflow/execution.go
- pkg/cloud/data/testworkflow/execution_models.go
- pkg/repository/testworkflow/interface.go
- pkg/repository/testworkflow/mock_repository.go
- pkg/repository/testworkflow/mongo.go
> feat: add sortBy param to get latest workflow execution

- pkg/cloud/data/testworkflow/commands.go
- pkg/cloud/data/testworkflow/execution.go
- pkg/cloud/data/testworkflow/execution_models.go
- pkg/repository/testworkflow/interface.go
- pkg/repository/testworkflow/mock_repository.go
- pkg/repository/testworkflow/mongo.go
> feat: implement Count method & cmd for workflow executions

- cmd/kubectl-testkube/commands/testworkflows/run.go
check error on init step
-
-
-
> fix: [TKC-4004] check init error

- pkg/testworkflows/testworkflowexecutor/executor.go
> fix: erroneous execution notifications for executions that are not yet completed

- pkg/agent/client/client.go
To avoid overloading a server and potentially work around transient network issues our gRPC client should have a sensible backoff configuration. The configuration set here is take from the gRPC documentation example. It is probably not perfect but it is a good starting point that we can iterate from.
Docs: https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md
I have tested this backoff configuration locally with a non-responsive gRPC server (credentials mismatch between client and server) and observed the following backoff behaviour (gathered using `GODEBUG` for http2 connections), note the timestamps on the connection attempt packets:
```
2025/08/11 15:06:25 IDLE: Connecting
2025/08/11 15:06:25 http2: Framer 0x1400024a000: wrote SETTINGS len=0
2025/08/11 15:06:26 http2: …
```
> feat: backoff gRPC connections

- pkg/database/postgres/queries/executions.sql
- pkg/database/postgres/sqlc/executions.sql.go
- pkg/database/postgres/sqlc/executions.sql_test.go
Reverts kubeshop/testkube#6600
> revert: Execution sorting order

- .github/workflows/lint.yaml
- .github/workflows/test.yaml
- build/_local/agent-server.Dockerfile
- build/_local/testworkflow-init.Dockerfile
- build/_local/testworkflow-toolkit.Dockerfile
- build/new/api-server.Dockerfile
- build/new/tw-init.Dockerfile
- build/new/tw-toolkit.Dockerfile
- cmd/debug-server/Dockerfile
- cmd/kubectl-testkube/commands/common/render/common.go
- cmd/kubectl-testkube/commands/help.go
- cmd/kubectl-testkube/commands/tests/common.go
- cmd/kubectl-testkube/commands/testworkflows/run.go
- contrib/executor/ginkgo/build/agent/Dockerfile
- contrib/executor/k6/build/agent/Dockerfile
- go.mod
- pkg/event/server.go
- pkg/executor/output/parser.go
- pkg/helm/chart.go
- pkg/semver/version.go
- pkg/testworkflows/testworkflowresolver/secrets.go
Some new vet issues are also resolved in the
code as part of the change to 1.25.
> chore: Bump Go version to latest

- .github/workflows/new-build.yaml
- .github/workflows/release.yaml
This PR adds pushing images to Google Artifact Registry.
-
-
-
> ci: push images to gar

- pkg/mcp/api.go
- pkg/mcp/client.go
- pkg/mcp/server.go
- pkg/mcp/tools/artifacts.go
- pkg/mcp/tools/dashboard.go
- pkg/mcp/tools/descriptions.go
- pkg/mcp/tools/executions.go
- pkg/mcp/tools/labels.go
- pkg/mcp/tools/resource_groups.go
- pkg/mcp/tools/workflows.go
- Added MCP tool for updating a workflow definition
- Added MCP tool for aborting an execution
- Moved all descriptions to descriptions.go
-
-
-
> feat: Tools for updating and aborting Workflows

- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/logs.go
- pkg/runner/agent.go
Rather than having streams killed if one of them
needs to reconnect, instead streams should be
individually retried and reconnected so that
a single failure does not kill all of them.
> fix: Reconnect gRPC streams individually
